import type { FoaLessonDefinition, FoaLocale } from "../tutorials/foa-contracts.js";
import type { PanelApi } from "../shared/api.js";
import {
  createFoaTransitionRuntime63,
  createFoaTransitionRuntime70,
  type FoaTransitionRuntimeFrame,
  type FoaTransitionRuntimePrototype,
} from "../tutorials/foa-transition-runtime-63-70.js";
import {
  assertFoaTransitionRuntime7580Anchors,
  createFoaTransitionRuntime75,
  createFoaTransitionRuntime80,
  FOA_LESSON_80_DEFAULT_OPEN_GRID,
  type FoaTransitionRuntime7580Event,
  type FoaTransitionRuntime7580Timeline,
} from "../tutorials/foa-transition-runtime-75-80.js";
import {
  createFoaTransitionTraceBinding63,
  createFoaTransitionTraceBinding70,
  createFoaTransitionTraceBinding75,
  createFoaTransitionTraceBinding80,
} from "../tutorials/foa-transition-trace-bindings.js";
import {
  createTaskLessonMotionController,
  type TaskLessonMotionController,
} from "./task-lesson-motion.js";
import {
  createFoaTransitionStageTraceController,
  type FoaTransitionStageTraceController,
  type FoaTransitionStageTraceState,
  type FoaTransitionTraceBinding,
} from "./foa-transition-trace-controller.js";

export const FOA_TRANSITION_PROTOTYPE_ORDERS = Object.freeze([63, 70, 75, 80] as const);
export type FoaTransitionPrototypeStageOrder = (typeof FOA_TRANSITION_PROTOTYPE_ORDERS)[number];

export interface FoaTransitionPrototypeStageOptions {
  readonly locale: FoaLocale;
  readonly reducedMotion?: boolean | undefined;
  readonly traceApi?: Pick<PanelApi, "startTrace" | "readTrace" | "cancelTrace"> | undefined;
  readonly onFrameChange?: ((selection: FoaTransitionFrameSelection) => void) | undefined;
}

export interface FoaTransitionFrameSelection {
  readonly frameId: string;
  readonly frameIndex: number;
  readonly sourceAnchorId: string;
  readonly sourceLine: number;
  readonly sourceText: string;
  readonly provenance: "teaching-model" | "real-trace";
}

export interface FoaTransitionPrototypeStage {
  readonly order: FoaTransitionPrototypeStageOrder;
  setLocale(locale: FoaLocale): void;
  setReducedMotion(reducedMotion: boolean): void;
  reset(): void;
  destroy(): void;
}

interface Copy {
  readonly heading: string;
  readonly teachingModel: string;
  readonly unverified: string;
  readonly evidenceDetail: string;
  readonly verifyTrace: string;
  readonly verifyAgain: string;
  readonly verifyingTrace: string;
  readonly realTrace: string;
  readonly verified: string;
  readonly traceIdle: string;
  readonly traceVerifying: string;
  readonly traceVerified: string;
  readonly traceFailed: string;
  readonly traceUnavailable: string;
  readonly input: string;
  readonly apply: string;
  readonly previous: string;
  readonly play: string;
  readonly pause: string;
  readonly next: string;
  readonly step: string;
  readonly source: string;
  readonly verifiedSource: string;
  readonly output: string;
  readonly value: string;
  readonly sortedValues: string;
  readonly target: string;
  readonly disks: string;
  readonly openCells: string;
  readonly obstacle: string;
  readonly invalidInteger: string;
  readonly invalidSortedValues: string;
  readonly layoutPaused: string;
  readonly pointerLink: string;
  readonly searchRange: string;
  readonly callStack: string;
  readonly pathCounts: string;
  traceEvents(count: number): string;
}

const COPY: Readonly<Record<FoaLocale, Copy>> = Object.freeze({
  zh: {
    heading: "运行状态样板",
    teachingModel: "教学推演",
    unverified: "真实数据待验证",
    evidenceDetail: "当前状态由确定性课程模型生成，不是实际 C 进程变量采样。",
    verifyTrace: "验证真实 Trace",
    verifyAgain: "重新验证",
    verifyingTrace: "正在验证",
    realTrace: "真实 Trace",
    verified: "证据一致",
    traceIdle: "按当前输入编译并运行一次受限影子 Trace。",
    traceVerifying: "正在核对运行事件",
    traceVerified: "实际运行、状态事件与输出已一致。",
    traceFailed: "证据不完整或不一致；继续显示教学推演。",
    traceUnavailable: "当前环境不支持真实 Trace。",
    input: "实验输入（不改项目源码）",
    apply: "应用",
    previous: "上一步",
    play: "播放",
    pause: "暂停",
    next: "下一步",
    step: "步骤",
    source: "对应 C 代码",
    verifiedSource: "已验证 C 代码",
    output: "输出",
    value: "本次输入",
    sortedValues: "有序整数（空格分隔）",
    target: "目标值",
    disks: "圆盘数",
    openCells: "可通行格",
    obstacle: "障碍",
    invalidInteger: "请输入允许范围内的整数。",
    invalidSortedValues: "请输入 2–12 个非递减整数。",
    layoutPaused: "面板过窄，已暂停播放；拉宽面板后可继续。",
    pointerLink: "对象链接与字段写回",
    searchRange: "二分查找区间",
    callStack: "递归调用栈",
    pathCounts: "网格路径依赖",
    traceEvents: (count) => `${String(count)} 个事件`,
  },
  en: {
    heading: "Runtime state prototype",
    teachingModel: "Teaching simulation",
    unverified: "Real data not verified",
    evidenceDetail:
      "The current state is generated by a deterministic lesson model, not sampled from the C process.",
    verifyTrace: "Verify real Trace",
    verifyAgain: "Verify again",
    verifyingTrace: "Verifying",
    realTrace: "Real Trace",
    verified: "Evidence consistent",
    traceIdle: "Compile and run one bounded shadow Trace with the current input.",
    traceVerifying: "Checking runtime events",
    traceVerified: "The real run, state events, and output are consistent.",
    traceFailed: "Evidence is incomplete or inconsistent; the teaching simulation remains active.",
    traceUnavailable: "Real Trace is unavailable in this environment.",
    input: "Experiment input (does not edit project source)",
    apply: "Apply",
    previous: "Previous",
    play: "Play",
    pause: "Pause",
    next: "Next",
    step: "Step",
    source: "Matching C source",
    verifiedSource: "Verified C source",
    output: "Output",
    value: "Current input",
    sortedValues: "Sorted integers (space separated)",
    target: "Target",
    disks: "Disk count",
    openCells: "Open cell",
    obstacle: "Obstacle",
    invalidInteger: "Enter an integer in the allowed range.",
    invalidSortedValues: "Enter 2–12 non-decreasing integers.",
    layoutPaused: "Playback paused because the panel is too narrow. Widen it to continue.",
    pointerLink: "Object link and field write",
    searchRange: "Binary-search interval",
    callStack: "Recursive call stack",
    pathCounts: "Grid path dependencies",
    traceEvents: (count) => `${String(count)} events`,
  },
});

type PrototypeModel = FoaTransitionRuntimePrototype | FoaTransitionRuntime7580Timeline;
type PrototypeFrame = FoaTransitionRuntimeFrame | FoaTransitionRuntime7580Event;

interface VisualRenderer {
  readonly elements: readonly HTMLElement[];
  render(frame: PrototypeFrame, commitState?: boolean): ActiveConnection | null;
  consumePresenceTransition?(): VisualPresenceTransition | null;
  applyLocale(locale: FoaLocale): void;
  destroy(): void;
}

interface VisualPresenceTransition {
  readonly entering: readonly HTMLElement[];
  readonly exiting: readonly HTMLElement[];
  finalize(): void;
}

interface ActiveConnection {
  readonly from: HTMLElement;
  readonly to: HTMLElement;
  readonly label: string;
  readonly eventId: string;
}

interface EdgeGeometry {
  readonly startX: number;
  readonly startY: number;
  readonly endX: number;
  readonly endY: number;
  readonly controlX: number;
  readonly controlY: number;
  readonly length: number;
}

type ResolvedFrameSource = Omit<FoaTransitionFrameSelection, "provenance">;

let stageSequence = 0;

export function isFoaTransitionPrototypeStageOrder(
  order: number,
): order is FoaTransitionPrototypeStageOrder {
  return FOA_TRANSITION_PROTOTYPE_ORDERS.includes(order as FoaTransitionPrototypeStageOrder);
}

export function createFoaTransitionPrototypeStage(
  host: HTMLElement,
  lesson: Pick<FoaLessonDefinition, "order" | "code">,
  options: FoaTransitionPrototypeStageOptions,
): FoaTransitionPrototypeStage {
  if (!isFoaTransitionPrototypeStageOrder(lesson.order)) {
    throw new RangeError(`FOA lesson ${String(lesson.order)} has no transition prototype`);
  }

  const order = lesson.order;
  const ownerDocument = host.ownerDocument;
  const element = (tagName: string, className = ""): HTMLElement => {
    const node = ownerDocument.createElement(tagName);
    node.className = className;
    return node;
  };
  const button = (action: string, listener: () => void, primary = false): HTMLButtonElement => {
    const node = ownerDocument.createElement("button");
    node.type = "button";
    node.className = primary ? "button button--primary" : "button";
    node.dataset.transitionAction = action;
    node.addEventListener("click", listener);
    return node;
  };
  const stageId = `foa-transition-${String(++stageSequence)}`;
  let locale = options.locale;
  let requestedReducedMotion = options.reducedMotion ?? false;
  const reducedMotionQuery =
    ownerDocument.defaultView?.matchMedia?.("(prefers-reduced-motion: reduce)") ?? null;
  let systemReducedMotion = reducedMotionQuery?.matches === true;
  let reducedMotion = requestedReducedMotion || systemReducedMotion;
  let destroyed = false;
  let model: PrototypeModel = createDefaultModel(order);
  assertModelAnchors(lesson.code.text, model);
  let frameIndex = 0;
  let playing = false;
  let playbackTimer: number | null = null;
  let layoutRequest: number | null = null;
  let tokenAnimation: Animation | null = null;
  let renderRevision = 0;
  let pendingCommit: (() => void) | null = null;
  let renderer: VisualRenderer | null = null;
  let currentConnection: ActiveConnection | null = null;
  let motion: TaskLessonMotionController = createTaskLessonMotionController({ reducedMotion });
  let traceController: FoaTransitionStageTraceController | null = null;
  let traceState: FoaTransitionStageTraceState = Object.freeze({
    status: options.traceApi === undefined ? "unavailable" : "idle",
    eventCount: 0,
    failureCode: null,
    model: null,
  });
  const localizedUpdates: Array<() => void> = [];
  const inputLocalizedUpdates: Array<() => void> = [];
  const removeReducedMotionListener = subscribeToMediaQuery(reducedMotionQuery, (matches) => {
    systemReducedMotion = matches;
    applyReducedMotionPreference();
  });

  const root = element("section", "foa-transition-prototype");
  root.dataset.lessonOrder = String(order);
  root.dataset.provenance = "teaching-model";
  root.dataset.traceStatus = "unverified";
  root.dataset.reducedMotion = String(reducedMotion);
  root.dataset.layout = "ready";
  root.tabIndex = -1;
  root.setAttribute("aria-labelledby", `${stageId}-heading`);
  root.addEventListener("keydown", (event) => {
    const InputConstructor = ownerDocument.defaultView?.HTMLInputElement;
    if (InputConstructor !== undefined && event.target instanceof InputConstructor) return;
    if (event.key === " ") {
      event.preventDefault();
      togglePlayback();
    } else if (event.key === "ArrowLeft") {
      event.preventDefault();
      stepTo(frameIndex - 1);
    } else if (event.key === "ArrowRight") {
      event.preventDefault();
      stepTo(frameIndex + 1);
    }
  });
  root.addEventListener("scroll", () => scheduleLayout(), true);

  const header = element("header", "foa-transition-prototype__header");
  const heading = element("strong", "foa-transition-prototype__heading");
  heading.id = `${stageId}-heading`;
  bindText(heading, () => `${copy().heading} · ${visualTitle(order, locale)}`);
  const evidence = element("div", "foa-transition-prototype__evidence");
  const provenance = element("span", "foa-transition-prototype__badge");
  provenance.dataset.kind = "simulation";
  evidence.title = copy().evidenceDetail;
  header.append(heading, evidence);
  evidence.append(provenance);

  const inputPanel = ownerDocument.createElement("form");
  inputPanel.className = "foa-transition-prototype__input";
  inputPanel.noValidate = true;
  inputPanel.addEventListener("submit", (event) => {
    event.preventDefault();
    inputControls
      .querySelector<HTMLButtonElement>('[data-transition-action="apply-input"]')
      ?.click();
  });
  const inputTitle = element("strong", "foa-transition-prototype__input-title");
  bindText(inputTitle, () => copy().input);
  const inputControls = element("div", "foa-transition-prototype__input-controls");
  const inputError = element("p", "foa-transition-prototype__input-error");
  inputError.hidden = true;
  const traceVerification = element("div", "foa-transition-prototype__trace-verification");
  const verifyTrace = button("verify-real-trace", () => {
    void traceController?.start();
  });
  const traceMessage = element("span", "foa-transition-prototype__trace-message");
  traceMessage.setAttribute("aria-live", "polite");
  traceVerification.append(verifyTrace, traceMessage);
  inputPanel.append(inputTitle, inputControls, traceVerification, inputError);
  configureInputs();

  const canvas = element("section", "foa-transition-prototype__canvas");
  canvas.dataset.order = String(order);
  canvas.setAttribute("aria-label", visualTitle(order, locale));
  const visual = element("div", "foa-transition-prototype__visual");
  const edgeSvg = ownerDocument.createElementNS("http://www.w3.org/2000/svg", "svg");
  edgeSvg.classList.add("foa-transition-prototype__edges");
  edgeSvg.setAttribute("aria-hidden", "true");
  edgeSvg.setAttribute("overflow", "visible");
  const edgeDefinitions = ownerDocument.createElementNS("http://www.w3.org/2000/svg", "defs");
  const marker = ownerDocument.createElementNS("http://www.w3.org/2000/svg", "marker");
  marker.id = `${stageId}-arrow`;
  marker.setAttribute("viewBox", "0 0 10 10");
  marker.setAttribute("refX", "9");
  marker.setAttribute("refY", "5");
  marker.setAttribute("markerWidth", "7");
  marker.setAttribute("markerHeight", "7");
  marker.setAttribute("orient", "auto-start-reverse");
  const markerShape = ownerDocument.createElementNS("http://www.w3.org/2000/svg", "path");
  markerShape.setAttribute("d", "M 0 0 L 10 5 L 0 10 z");
  markerShape.setAttribute("class", "foa-transition-prototype__arrowhead");
  marker.append(markerShape);
  edgeDefinitions.append(marker);
  const edgeGroup = ownerDocument.createElementNS("http://www.w3.org/2000/svg", "g");
  const token = element("span", "foa-transition-prototype__token");
  token.hidden = true;
  const relation = element("p", "foa-transition-prototype__relation-label");
  relation.hidden = true;
  relation.setAttribute("aria-live", "polite");
  edgeSvg.append(edgeDefinitions, edgeGroup);
  canvas.append(visual, edgeSvg, token, relation);

  const narration = element("div", "foa-transition-prototype__narration");
  const summary = element("p", "foa-transition-prototype__summary");
  const sourceLine = element("div", "foa-transition-prototype__source");
  const sourceLabel = element("span");
  const sourceEntry = element("div", "foa-transition-prototype__source-line");
  const sourceLineNumber = element("span", "foa-transition-prototype__source-line-number");
  const sourceCode = ownerDocument.createElement("code");
  sourceCode.className = "foa-transition-prototype__source-line-code";
  sourceEntry.append(sourceLineNumber, sourceCode);
  sourceLine.append(sourceLabel, sourceEntry);
  const output = element("div", "foa-transition-prototype__output");
  const outputLabel = element("span");
  bindText(outputLabel, () => copy().output);
  const outputValue = ownerDocument.createElement("output");
  output.append(outputLabel, outputValue);
  summary.setAttribute("aria-live", "polite");
  narration.append(summary, sourceLine, output);

  const controls = element("div", "foa-transition-prototype__controls");
  const previous = button("previous", () => stepTo(frameIndex - 1));
  bindText(previous, () => copy().previous);
  const play = button("play", togglePlayback, true);
  const next = button("next", () => stepTo(frameIndex + 1));
  bindText(next, () => copy().next);
  const progressLabel = element("label", "foa-transition-prototype__progress-label");
  const progressText = element("span");
  const progress = ownerDocument.createElement("input");
  progress.type = "range";
  progress.min = "0";
  progress.step = "1";
  progress.dataset.transitionProgress = "";
  progress.addEventListener("input", () => stepTo(Number(progress.value), false));
  progressLabel.append(progressText, progress);
  controls.append(previous, play, next, progressLabel);

  const layoutWarning = element("p", "foa-transition-prototype__layout-warning");
  bindText(layoutWarning, () => copy().layoutPaused);
  layoutWarning.hidden = true;

  // Keep the rare fail-safe message in document flow. An overlay hid the very narration/output
  // that the warning asked the learner to inspect.
  inputPanel.append(layoutWarning);
  root.append(header, inputPanel, canvas, narration, controls);
  host.append(root);
  rebuildRenderer();
  applyLocale();
  renderFrame(false);
  traceController = createFoaTransitionStageTraceController({
    api: options.traceApi,
    getBinding: createTraceBinding,
    onStateChange: applyTraceState,
  });

  const resizeObserver = createResizeObserver(ownerDocument, () => scheduleLayout());
  resizeObserver?.observe(canvas);

  return Object.freeze({
    order,
    setLocale(nextLocale: FoaLocale): void {
      assertLive();
      locale = nextLocale;
      applyLocale();
      renderer?.applyLocale(locale);
      renderFrame(false);
    },
    setReducedMotion(nextReducedMotion: boolean): void {
      assertLive();
      requestedReducedMotion = nextReducedMotion;
      applyReducedMotionPreference();
    },
    reset(): void {
      assertLive();
      traceController?.invalidate();
      pause();
      model = createDefaultModel(order);
      frameIndex = 0;
      configureInputs();
      rebuildRenderer();
      applyLocale();
      renderFrame(false);
    },
    destroy(): void {
      if (destroyed) return;
      destroyed = true;
      traceController?.destroy();
      traceController = null;
      pause();
      if (layoutRequest !== null) cancelFrame(ownerDocument, layoutRequest);
      resizeObserver?.disconnect();
      removeReducedMotionListener();
      settlePendingFrame();
      tokenAnimation?.cancel();
      renderer?.destroy();
      motion.destroy();
      root.remove();
    },
  });

  function copy(): Copy {
    return COPY[locale];
  }

  function bindText(target: HTMLElement, value: () => string): void {
    localizedUpdates.push(() => {
      const text = value();
      target.textContent = text;
      target.title = text;
    });
  }

  function applyLocale(): void {
    root.dataset.locale = locale;
    root.setAttribute("aria-label", `${copy().heading}: ${visualTitle(order, locale)}`);
    canvas.setAttribute("aria-label", visualTitle(order, locale));
    evidence.title = copy().evidenceDetail;
    for (const update of localizedUpdates) update();
    for (const update of inputLocalizedUpdates) update();
    play.textContent = playing ? copy().pause : copy().play;
    play.title = play.textContent;
    renderTraceState();
    renderer?.applyLocale(locale);
  }

  function applyReducedMotionPreference(): void {
    const next = requestedReducedMotion || systemReducedMotion;
    if (reducedMotion === next && root.dataset.reducedMotion === String(next)) return;
    reducedMotion = next;
    root.dataset.reducedMotion = String(reducedMotion);
    settlePendingFrame();
    tokenAnimation?.cancel();
    tokenAnimation = null;
    token.hidden = true;
    motion.setReducedMotion(reducedMotion);
    renderFrame(false);
  }

  function configureInputs(): void {
    inputControls.replaceChildren();
    inputLocalizedUpdates.length = 0;
    inputError.hidden = true;
    inputError.textContent = "";
    if (order === 63) configureCounterInput();
    else if (order === 70) configureSearchInput();
    else if (order === 75) configureDiskInput();
    else configureGridInput();
  }

  function configureCounterInput(): void {
    const input = numericInput(-999, 999, Number(modelInput("initialValue") ?? 4));
    const field = labelledControl(() => copy().value, input);
    const apply = inputButton(() => {
      try {
        replaceModel(createFoaTransitionRuntime63(parseIntegerInput(input.value)));
      } catch {
        showInputError(copy().invalidInteger);
      }
    });
    inputControls.append(field, apply);
  }

  function configureSearchInput(): void {
    const currentValues = String(modelInput("values") ?? "[1, 3, 5, 7, 9]")
      .replace(/[\[\],]/gu, " ")
      .trim()
      .replace(/\s+/gu, " ");
    const values = ownerDocument.createElement("input");
    values.type = "text";
    values.value = currentValues;
    values.inputMode = "numeric";
    values.autocomplete = "off";
    const target = numericInput(
      Number.MIN_SAFE_INTEGER,
      Number.MAX_SAFE_INTEGER,
      Number(modelInput("target") ?? 7),
    );
    const apply = inputButton(() => {
      const parsed = values.value
        .trim()
        .split(/[\s,]+/u)
        .filter(Boolean)
        .map(Number);
      try {
        replaceModel(createFoaTransitionRuntime70(parsed, parseIntegerInput(target.value)));
      } catch {
        showInputError(copy().invalidSortedValues);
      }
    });
    inputControls.append(
      labelledControl(() => copy().sortedValues, values),
      labelledControl(() => copy().target, target),
      apply,
    );
  }

  function configureDiskInput(): void {
    const initial = prototype75Input(model);
    const input = numericInput(0, 12, initial);
    const apply = inputButton(() => {
      try {
        replaceModel(createFoaTransitionRuntime75(parseIntegerInput(input.value)));
      } catch {
        showInputError(copy().invalidInteger);
      }
    });
    inputControls.append(
      labelledControl(() => copy().disks, input),
      apply,
    );
  }

  function configureGridInput(): void {
    const grid = currentOpenGrid(model);
    const group = element("div", "foa-transition-prototype__grid-input");
    group.setAttribute("role", "group");
    const cells: HTMLButtonElement[] = [];
    for (let row = 0; row < 3; row += 1) {
      for (let column = 0; column < 3; column += 1) {
        const cell = button(`grid-${String(row)}-${String(column)}`, () => {
          if ((row === 0 && column === 0) || (row === 2 && column === 2)) return;
          grid[row]![column] = grid[row]![column] === 1 ? 0 : 1;
          cell.dataset.open = String(grid[row]![column] === 1);
          cell.setAttribute("aria-pressed", String(grid[row]![column] === 1));
          replaceModel(createFoaTransitionRuntime80(grid), false);
          // The input button is the learner's editing cursor. Preserve the same DOM node so
          // keyboard users can toggle several cells without focus falling back to <body>.
          cell.focus({ preventScroll: true });
        });
        cell.className = "foa-transition-prototype__grid-toggle";
        cell.dataset.row = String(row);
        cell.dataset.column = String(column);
        cell.dataset.open = String(grid[row]![column] === 1);
        cell.setAttribute("aria-pressed", String(grid[row]![column] === 1));
        cell.disabled = (row === 0 && column === 0) || (row === 2 && column === 2);
        const label = grid[row]![column] === 1 ? copy().openCells : copy().obstacle;
        cell.textContent = `${String(row)},${String(column)} · ${String(grid[row]![column])}`;
        cell.title = `${String(row)},${String(column)} · ${label}`;
        cells.push(cell);
        group.append(cell);
      }
    }
    inputLocalizedUpdates.push(() => {
      for (const cell of cells) {
        const row = Number(cell.dataset.row);
        const column = Number(cell.dataset.column);
        const label = cell.dataset.open === "true" ? copy().openCells : copy().obstacle;
        cell.textContent = `${String(row)},${String(column)} · ${cell.dataset.open === "true" ? "1" : "0"}`;
        cell.title = `${String(row)},${String(column)} · ${label}`;
      }
    });
    inputControls.append(group);
  }

  function numericInput(minimum: number, maximum: number, value: number): HTMLInputElement {
    const input = ownerDocument.createElement("input");
    input.type = "number";
    input.min = String(minimum);
    input.max = String(maximum);
    input.step = "1";
    input.value = String(value);
    input.inputMode = "numeric";
    return input;
  }

  function labelledControl(labelText: () => string, control: HTMLElement): HTMLLabelElement {
    const label = ownerDocument.createElement("label");
    label.className = "foa-transition-prototype__field";
    const text = element("span");
    inputLocalizedUpdates.push(() => {
      text.textContent = labelText();
    });
    label.append(text, control);
    return label;
  }

  function inputButton(listener: () => void): HTMLButtonElement {
    const apply = button("apply-input", listener, true);
    inputLocalizedUpdates.push(() => {
      apply.textContent = copy().apply;
      apply.title = apply.textContent;
    });
    apply.textContent = copy().apply;
    return apply;
  }

  function showInputError(message: string): void {
    inputError.textContent = message;
    inputError.hidden = false;
    inputError.focus?.();
  }

  function replaceModel(next: PrototypeModel, reconfigure = true): void {
    traceController?.invalidate();
    assertModelAnchors(lesson.code.text, next);
    pause();
    model = next;
    frameIndex = 0;
    inputError.hidden = true;
    if (reconfigure) configureInputs();
    rebuildRenderer();
    applyLocale();
    renderFrame(false);
  }

  function createTraceBinding(): FoaTransitionTraceBinding {
    if (order === 63) {
      return createFoaTransitionTraceBinding63(Number(modelInput("initialValue") ?? 4));
    }
    if (order === 70) {
      const values = String(modelInput("values") ?? "[1, 3, 5, 7, 9]")
        .replace(/[\[\],]/gu, " ")
        .trim()
        .split(/\s+/u)
        .filter(Boolean)
        .map(Number);
      return createFoaTransitionTraceBinding70(values, Number(modelInput("target") ?? 7));
    }
    if (order === 75) return createFoaTransitionTraceBinding75(prototype75Input(model));
    return createFoaTransitionTraceBinding80(currentOpenGrid(model));
  }

  function applyTraceState(nextState: FoaTransitionStageTraceState): void {
    if (destroyed) return;
    const wasVerified = traceState.status === "verified";
    traceState = nextState;
    renderTraceState();
    const nextModel =
      nextState.status === "verified" && nextState.model !== null
        ? nextState.model
        : wasVerified
          ? createTraceBinding().model
          : null;
    if (nextModel !== null) {
      assertModelAnchors(lesson.code.text, nextModel);
      pause();
      model = nextModel;
      frameIndex = 0;
      rebuildRenderer();
      renderFrame(false);
    }
    renderTraceState();
  }

  function renderTraceState(): void {
    root.dataset.traceStatus = traceState.status;
    root.dataset.provenance = traceState.status === "verified" ? "real-trace" : "teaching-model";
    root.dataset.modelProvenance =
      "frames" in model
        ? typeof model.evidence.provenance === "string"
          ? "teaching-model"
          : model.evidence.provenance.kind
        : model.provenance.kind;
    if (traceState.failureCode === null) delete root.dataset.traceFailure;
    else root.dataset.traceFailure = traceState.failureCode;
    const isVerified = traceState.status === "verified";
    provenance.dataset.kind = isVerified ? "real" : "simulation";
    provenance.textContent = isVerified
      ? `${copy().realTrace} · ${copy().verified}`
      : `${copy().teachingModel} · ${copy().unverified}`;
    verifyTrace.disabled = traceState.status === "verifying" || traceState.status === "unavailable";
    verifyTrace.textContent =
      traceState.status === "verifying"
        ? copy().verifyingTrace
        : traceState.status === "verified"
          ? copy().verifyAgain
          : copy().verifyTrace;
    const eventSuffix =
      traceState.eventCount > 0 ? ` · ${copy().traceEvents(traceState.eventCount)}` : "";
    traceMessage.textContent =
      traceState.status === "unavailable"
        ? copy().traceUnavailable
        : traceState.status === "verifying"
          ? `${copy().traceVerifying}${eventSuffix}`
          : traceState.status === "verified"
            ? `${copy().traceVerified}${eventSuffix}`
            : traceState.status === "failed"
              ? copy().traceFailed
              : copy().traceIdle;
    evidence.title = isVerified ? copy().traceVerified : copy().evidenceDetail;
    verifyTrace.title = verifyTrace.textContent;
    traceMessage.title = traceMessage.textContent;
  }

  function rebuildRenderer(): void {
    renderer?.destroy();
    visual.replaceChildren();
    renderer = createRenderer(order, visual, model, locale);
    progress.max = String(Math.max(0, frames().length - 1));
  }

  function renderFrame(animate = true): void {
    settlePendingFrame();
    const timeline = frames();
    if (timeline.length === 0) return;
    const revision = ++renderRevision;
    frameIndex = Math.max(0, Math.min(frameIndex, timeline.length - 1));
    const frame = timeline[frameIndex]!;
    const before = motion.capture(renderer?.elements ?? []);
    const connection = renderer?.render(frame, false) ?? null;
    currentConnection = connection;
    const summaryText = frameSummary(frame, locale);
    summary.textContent = summaryText;
    summary.title = summaryText;
    const selection = resolveFrameSourceSelection(lesson.code.text, model, frame, frameIndex);
    const verified = traceState.status === "verified";
    sourceLabel.textContent = verified ? copy().verifiedSource : copy().source;
    sourceLabel.title = sourceLabel.textContent;
    sourceLineNumber.textContent = String(selection.sourceLine);
    sourceLineNumber.title = `${locale === "zh" ? "行" : "line"} ${String(selection.sourceLine)}`;
    sourceCode.textContent = selection.sourceText.trim();
    sourceCode.dataset.sourceAnchorId = frame.sourceAnchorId;
    sourceCode.dataset.modelRule = frameRule(model, frame, locale);
    sourceCode.title = `${sourceCode.textContent} · ${sourceCode.dataset.modelRule}`;
    sourceLine.dataset.provenance = verified ? "real-trace" : "teaching-model";
    root.dataset.activeSourceAnchorId = selection.sourceAnchorId;
    root.dataset.activeSourceLine = String(selection.sourceLine);
    options.onFrameChange?.({
      ...selection,
      provenance: verified ? "real-trace" : "teaching-model",
    });
    progress.value = String(frameIndex);
    progressText.textContent = `${copy().step} ${String(frameIndex + 1)} / ${String(timeline.length)}`;
    previous.disabled = frameIndex === 0;
    next.disabled = frameIndex >= timeline.length - 1;
    const commit = (): void => {
      if (destroyed || revision !== renderRevision) return;
      pendingCommit = null;
      const commitBefore = motion.capture(renderer?.elements ?? []);
      renderer?.render(frame, true);
      const presence = renderer?.consumePresenceTransition?.() ?? null;
      outputValue.textContent = frameOutput(frame);
      outputValue.title = outputValue.textContent;
      let transition: Promise<void> | null = null;
      if (presence !== null && animate && !reducedMotion) {
        transition = Promise.all([
          motion.animatePresence(presence.entering, "shift", "enter", { left: 0, top: 12 }),
          motion.animatePresence(presence.exiting, "shift", "exit", { left: 0, top: 12 }),
        ]).then(() => presence.finalize());
      } else {
        presence?.finalize();
      }
      if (animate && presence === null) {
        transition = motion.animateFrom(
          commitBefore.size > 0 ? commitBefore : before,
          renderer?.elements ?? [],
          motionKind(frame),
        );
      }
      // Draw against the presentation geometry immediately, but only run the collision gate after
      // the semantic transition settles. Measuring an intentional push/pop midpoint marked the
      // stable lesson as unsafe and left it permanently in the fallback layout.
      scheduleLayout(connection, false, undefined, transition === null);
      if (transition !== null) {
        void transition.finally(() => {
          if (!destroyed && revision === renderRevision) scheduleLayout();
        });
      }
    };
    const shouldAnimateConnection =
      animate && connection !== null && !reducedMotion && typeof token.animate === "function";
    if (shouldAnimateConnection) {
      pendingCommit = commit;
      scheduleLayout(connection, true, commit);
    } else {
      commit();
      scheduleLayout(connection, false);
    }
  }

  function stepTo(nextIndex: number, animate = true): void {
    if (destroyed) return;
    settlePendingFrame();
    motion.finish();
    const bounded = Math.max(0, Math.min(nextIndex, frames().length - 1));
    if (bounded === frameIndex && nextIndex === frameIndex) return;
    frameIndex = bounded;
    renderFrame(animate);
    if (playing && frameIndex >= frames().length - 1) pause(false);
  }

  function togglePlayback(): void {
    if (playing) pause();
    else startPlayback();
  }

  function startPlayback(): void {
    if (playing) return;
    if (frameIndex >= frames().length - 1) {
      frameIndex = 0;
      renderFrame(false);
    }
    playing = true;
    motion.play();
    tokenAnimation?.play();
    play.textContent = copy().pause;
    root.dataset.playing = "true";
    scheduleNextFrame();
  }

  function scheduleNextFrame(): void {
    clearPlaybackTimer();
    if (!playing) return;
    playbackTimer =
      ownerDocument.defaultView?.setTimeout(
        () => {
          playbackTimer = null;
          if (!playing) return;
          if (frameIndex >= frames().length - 1) {
            pause(false);
            return;
          }
          stepTo(frameIndex + 1);
          scheduleNextFrame();
        },
        playbackDelay(frames()[Math.min(frameIndex + 1, frames().length - 1)]!),
      ) ?? null;
  }

  function pause(pauseAnimations = true): void {
    playing = false;
    clearPlaybackTimer();
    if (pauseAnimations) {
      motion.pause();
      tokenAnimation?.pause();
    }
    play.textContent = copy().play;
    delete root.dataset.playing;
  }

  function clearPlaybackTimer(): void {
    if (playbackTimer === null) return;
    ownerDocument.defaultView?.clearTimeout(playbackTimer);
    playbackTimer = null;
  }

  function scheduleLayout(
    connection: ActiveConnection | null = null,
    playSemanticToken = false,
    onTokenArrival?: (() => void) | undefined,
    validate = true,
  ): void {
    // A scroll/resize can arrive between scheduling the semantic transfer and the next frame.
    // Keep that causally significant request; dropping its arrival callback would leave the model
    // forever in preview state. The existing request still measures the latest geometry.
    if (
      layoutRequest !== null &&
      pendingCommit !== null &&
      !playSemanticToken &&
      onTokenArrival === undefined
    ) {
      return;
    }
    if (layoutRequest !== null) cancelFrame(ownerDocument, layoutRequest);
    layoutRequest = requestFrame(ownerDocument, () => {
      layoutRequest = null;
      drawConnection(connection ?? currentConnection, playSemanticToken, onTokenArrival);
      if (validate) validateLayout();
    });
  }

  function drawConnection(
    connection: ActiveConnection | null,
    playSemanticToken = false,
    onTokenArrival?: (() => void) | undefined,
  ): void {
    edgeGroup.replaceChildren();
    if (connection === null || !root.isConnected) {
      tokenAnimation?.cancel();
      tokenAnimation = null;
      token.hidden = true;
      relation.hidden = true;
      relation.textContent = "";
      onTokenArrival?.();
      return;
    }
    const geometry = connectionGeometry(
      canvas,
      connection.from,
      connection.to,
      order === 70 || order === 80,
    );
    if (geometry === null) {
      token.hidden = true;
      relation.hidden = true;
      relation.textContent = "";
      onTokenArrival?.();
      return;
    }
    const bounds = canvas.getBoundingClientRect();
    edgeSvg.setAttribute("viewBox", `0 0 ${String(bounds.width)} ${String(bounds.height)}`);
    edgeSvg.setAttribute("width", String(bounds.width));
    edgeSvg.setAttribute("height", String(bounds.height));
    const path = ownerDocument.createElementNS("http://www.w3.org/2000/svg", "path");
    path.setAttribute(
      "d",
      `M ${String(geometry.startX)} ${String(geometry.startY)} Q ${String(geometry.controlX)} ${String(geometry.controlY)} ${String(geometry.endX)} ${String(geometry.endY)}`,
    );
    path.setAttribute("class", "foa-transition-prototype__edge");
    path.setAttribute("marker-end", `url(#${stageId}-arrow)`);
    const title = ownerDocument.createElementNS("http://www.w3.org/2000/svg", "title");
    title.textContent = connection.label;
    path.append(title);
    edgeGroup.append(path);
    relation.hidden = false;
    relation.textContent = connection.label;
    relation.title = connection.label;
    relation.dataset.eventId = connection.eventId;
    if (playSemanticToken) animateToken(geometry, connection.eventId, onTokenArrival);
    else positionTokenAtConnectionEnd(geometry, connection.eventId);
  }

  function animateToken(
    geometry: EdgeGeometry,
    eventId: string,
    onTokenArrival?: (() => void) | undefined,
  ): void {
    tokenAnimation?.cancel();
    token.dataset.tokenEventId = eventId;
    if (geometry.length < 24) {
      token.hidden = true;
      onTokenArrival?.();
      return;
    }
    token.hidden = false;
    const endTransform = tokenTransform(geometry.endX, geometry.endY);
    token.style.transform = endTransform;
    if (reducedMotion || typeof token.animate !== "function") {
      onTokenArrival?.();
      return;
    }
    tokenAnimation = token.animate(bezierTokenKeyframes(geometry), {
      duration: 620,
      easing: "cubic-bezier(0.2, 0.8, 0.2, 1)",
      fill: "none",
    });
    tokenAnimation.addEventListener(
      "finish",
      () => {
        tokenAnimation = null;
        onTokenArrival?.();
      },
      { once: true },
    );
  }

  function positionTokenAtConnectionEnd(geometry: EdgeGeometry, eventId: string): void {
    if (tokenAnimation !== null) return;
    token.dataset.tokenEventId = eventId;
    token.hidden = geometry.length < 24 || reducedMotion;
    token.style.transform = tokenTransform(geometry.endX, geometry.endY);
  }

  function settlePendingFrame(): void {
    if (pendingCommit === null) return;
    tokenAnimation?.cancel();
    tokenAnimation = null;
    const commit = pendingCommit;
    pendingCommit = null;
    commit();
  }

  function validateLayout(): void {
    const essentials = root.querySelectorAll<HTMLElement>(
      ".foa-transition-prototype__essential, .foa-transition-prototype__evidence, .foa-transition-prototype__field, .foa-transition-prototype__progress-label, .foa-transition-prototype__output, .foa-transition-prototype__grid-toggle",
    );
    const nodes = [...essentials];
    const textOverflow = nodes.some(
      (node) =>
        (node.clientWidth > 0 && node.scrollWidth > node.clientWidth + 1) ||
        (node.clientHeight > 0 && node.scrollHeight > node.clientHeight + 1),
    );
    const visibleNodes = nodes.filter((node) => {
      const rectangle = node.getBoundingClientRect();
      return (
        rectangle.width > 0 && rectangle.height > 0 && isVisibleInsideLocalScroller(node, rectangle)
      );
    });
    const overlap = visibleNodes.some((left, index) =>
      visibleNodes.slice(index + 1).some((right) => {
        if (left.contains(right) || right.contains(left)) return false;
        return rectanglesOverlap(left.getBoundingClientRect(), right.getBoundingClientRect());
      }),
    );
    const visualBounds = visual.getBoundingClientRect();
    const visualScrollable =
      visual.scrollWidth > visual.clientWidth + 1 || visual.scrollHeight > visual.clientHeight + 1;
    const outside =
      !visualScrollable &&
      visibleNodes.some((node) => {
        if (!visual.contains(node)) return false;
        const localScroller =
          typeof node.closest === "function"
            ? node.closest<HTMLElement>(".foa-transition-prototype__array")
            : null;
        if (
          localScroller !== null &&
          (localScroller.scrollWidth > localScroller.clientWidth + 1 ||
            localScroller.scrollHeight > localScroller.clientHeight + 1)
        ) {
          return false;
        }
        const rectangle = node.getBoundingClientRect();
        return (
          rectangle.left < visualBounds.left - 1 ||
          rectangle.right > visualBounds.right + 1 ||
          rectangle.top < visualBounds.top - 1 ||
          rectangle.bottom > visualBounds.bottom + 1
        );
      });
    const invalid = textOverflow || overlap || outside;
    root.dataset.layout = invalid ? "safe" : "ready";
    layoutWarning.hidden = !invalid;
    if (invalid) pause();
  }

  function frames(): readonly PrototypeFrame[] {
    return "frames" in model ? model.frames : model.events;
  }

  function modelInput(key: string): unknown {
    return "modelInput" in model ? model.modelInput[key] : undefined;
  }

  function assertLive(): void {
    if (destroyed) throw new Error("FOA transition prototype stage has been destroyed");
  }
}

function createRenderer(
  order: FoaTransitionPrototypeStageOrder,
  host: HTMLElement,
  model: PrototypeModel,
  locale: FoaLocale,
): VisualRenderer {
  if (order === 63)
    return createPointerRenderer(host, model as FoaTransitionRuntimePrototype, locale);
  if (order === 70)
    return createSearchRenderer(host, model as FoaTransitionRuntimePrototype, locale);
  if (order === 75)
    return createStackRenderer(host, model as FoaTransitionRuntime7580Timeline, locale);
  return createGridRenderer(host, model as FoaTransitionRuntime7580Timeline, locale);
}

function createPointerRenderer(
  host: HTMLElement,
  model: FoaTransitionRuntimePrototype,
  initialLocale: FoaLocale,
): VisualRenderer {
  let locale = initialLocale;
  const input = visualNode(host, "pointer-input", "input");
  const link = visualNode(host, "pointer-link", "link");
  const counter = visualNode(host, "pointer-record", "counter");
  const field = visualNode(host, "pointer-field", "value");
  field.classList.add("foa-transition-prototype__field-node");
  counter.append(field);
  host.append(input, link, counter);
  return Object.freeze({
    // The two object labels are stable. Animating their whole containers makes the text cross
    // even though only a relation value changed, so continuity is carried by the line and token.
    elements: Object.freeze([]),
    render(frame: PrototypeFrame, commitState = true): ActiveConnection | null {
      const item = frame as FoaTransitionRuntimeFrame;
      setActive(input, item.activeObjectIds.includes("63.object.input"));
      setActive(link, item.activeObjectIds.includes("63.object.link"));
      setActive(counter, item.activeObjectIds.includes("63.object.counter"));
      setActive(field, item.activeObjectIds.includes("63.object.counter.value"));
      const inputValue = item.state.inputValue;
      const target = item.state.linkTarget;
      const value = item.state.counterValue;
      if (commitState) {
        input.querySelector("output")!.textContent = String(inputValue ?? "—");
        link.querySelector("output")!.textContent = target === null ? "—" : String(target);
        field.querySelector("output")!.textContent = String(value ?? "—");
      }
      if (item.activeRelationIds.includes("63.relation.input-write")) {
        return {
          from: input,
          to: field,
          label:
            locale === "zh"
              ? `输入 ${String(inputValue ?? "—")} → counter.value`
              : `input ${String(inputValue ?? "—")} → counter.value`,
          eventId: item.id,
        };
      }
      if (item.activeRelationIds.includes("63.relation.field-access")) {
        const change = item.changes.find(({ objectId }) => objectId === "63.object.counter.value");
        return {
          from: link,
          to: field,
          label:
            change === undefined
              ? locale === "zh"
                ? "link->value 定位 counter.value"
                : "link->value resolves counter.value"
              : locale === "zh"
                ? `link->value：${String(change.before)} → ${String(change.after)}`
                : `link->value: ${String(change.before)} → ${String(change.after)}`,
          eventId: item.id,
        };
      }
      if (item.activeRelationIds.includes("63.relation.object-link")) {
        return {
          from: link,
          to: counter,
          label: relationLabel(model, "63.relation.object-link", locale),
          eventId: item.id,
        };
      }
      return null;
    },
    applyLocale(nextLocale: FoaLocale): void {
      locale = nextLocale;
      setNodeLabel(input, nextLocale === "zh" ? "本次输入" : "current input");
      setNodeLabel(link, nextLocale === "zh" ? "指针 link" : "pointer link");
      setNodeLabel(counter, nextLocale === "zh" ? "对象 counter" : "object counter");
      setNodeLabel(field, nextLocale === "zh" ? "字段 value" : "field value");
    },
    destroy(): void {},
  });
}

function createSearchRenderer(
  host: HTMLElement,
  model: FoaTransitionRuntimePrototype,
  initialLocale: FoaLocale,
): VisualRenderer {
  let locale = initialLocale;
  const frame = model.frames[0]!;
  const values = parseStateValues(frame.state.values);
  const target = visualNode(host, "search-target", "target");
  const row = documentFor(host).createElement("div");
  row.className = "foa-transition-prototype__array";
  row.tabIndex = 0;
  const bounds = documentFor(host).createElement("div");
  bounds.className = "foa-transition-prototype__bounds";
  const lowNode = visualNode(host, "search-low", "low");
  const highNode = visualNode(host, "search-high", "high");
  bounds.append(lowNode, highNode);
  const cells = values.map((value, index) => {
    const cell = visualNode(host, `search-cell-${String(index)}`, String(index));
    cell.classList.add("foa-transition-prototype__array-cell");
    cell.dataset.index = String(index);
    cell.querySelector("output")!.textContent = String(value);
    row.append(cell);
    return cell;
  });
  host.append(target, row, bounds);
  return Object.freeze({
    elements: Object.freeze([target, ...cells, lowNode, highNode]),
    render(nextFrame: PrototypeFrame, commitState = true): ActiveConnection | null {
      const item = nextFrame as FoaTransitionRuntimeFrame;
      const low = Number(item.state.low);
      const high = Number(item.state.high);
      const mid = item.state.mid === null ? null : Number(item.state.mid);
      if (commitState) {
        target.querySelector("output")!.textContent = String(item.state.target ?? "—");
        lowNode.querySelector("output")!.textContent = String(low);
        highNode.querySelector("output")!.textContent = String(high);
      }
      setActive(target, item.activeObjectIds.includes("70.object.target"));
      setActive(lowNode, item.activeObjectIds.includes("70.object.low"));
      setActive(highNode, item.activeObjectIds.includes("70.object.high"));
      for (const cell of cells) {
        const index = Number(cell.dataset.index);
        if (commitState) {
          cell.dataset.inRange = String(index >= low && index < high);
          cell.dataset.low = String(index === low);
          cell.dataset.mid = String(mid !== null && index === mid);
          cell.dataset.high = String(index === high - 1);
        }
        setActive(cell, mid !== null && index === mid);
        if (commitState) {
          const markers = [
            index === low ? "low" : "",
            mid !== null && index === mid ? "mid" : "",
            index === high - 1 ? "high−1" : "",
          ].filter(Boolean);
          cell.querySelector("span")!.textContent =
            markers.length > 0 ? markers.join(" · ") : String(index);
        }
      }
      if (mid !== null) keepChildVisible(row, cells[mid]!);
      if (mid !== null && item.activeRelationIds.includes("70.relation.compare")) {
        return {
          from: target,
          to: cells[mid]!,
          label: relationLabel(model, "70.relation.compare", locale),
          eventId: item.id,
        };
      }
      if (mid !== null && item.activeRelationIds.includes("70.relation.true")) {
        return {
          from: cells[mid]!,
          to: lowNode,
          label: relationLabel(model, "70.relation.true", locale),
          eventId: item.id,
        };
      }
      if (mid !== null && item.activeRelationIds.includes("70.relation.false")) {
        return {
          from: cells[mid]!,
          to: highNode,
          label: relationLabel(model, "70.relation.false", locale),
          eventId: item.id,
        };
      }
      return null;
    },
    applyLocale(nextLocale: FoaLocale): void {
      locale = nextLocale;
      row.setAttribute(
        "aria-label",
        nextLocale === "zh" ? "有序数组，可横向滚动" : "Sorted array, horizontally scrollable",
      );
      setNodeLabel(target, nextLocale === "zh" ? "目标 target" : "target");
      setNodeLabel(lowNode, "low");
      setNodeLabel(highNode, "high");
    },
    destroy(): void {},
  });
}

function createStackRenderer(
  host: HTMLElement,
  model: FoaTransitionRuntime7580Timeline,
  initialLocale: FoaLocale,
): VisualRenderer {
  let locale = initialLocale;
  const depth = Math.max(0, ...model.events.map((event) => event.stackFrames.length));
  const list = documentFor(host).createElement("ol");
  list.className = "foa-transition-prototype__stack";
  const frames = Array.from({ length: depth }, (_, index) => {
    const item = visualNode(host, `stack-${String(index)}`, `depth ${String(index)}`);
    const row = documentFor(host).createElement("li");
    row.append(item);
    list.append(row);
    return item;
  });
  let presenceTransition: VisualPresenceTransition | null = null;
  host.append(list);
  return Object.freeze({
    elements: Object.freeze(frames),
    render(nextFrame: PrototypeFrame, commitState = true): ActiveConnection | null {
      const event = nextFrame as FoaTransitionRuntime7580Event;
      const entering: HTMLElement[] = [];
      const exiting: HTMLElement[] = [];
      for (const [index, node] of frames.entries()) {
        const stackFrame = event.stackFrames.find((candidate) => candidate.depth === index);
        delete node.dataset.pending;
        if (commitState) {
          const parent = node.parentElement!;
          const wasHidden = parent.hidden;
          if (stackFrame === undefined) {
            if (!wasHidden) {
              node.dataset.presence = "exiting";
              exiting.push(node);
            }
          } else {
            parent.hidden = false;
            if (wasHidden || node.dataset.presence === "exiting") {
              node.dataset.presence = "entering";
              entering.push(node);
            }
          }
          setActive(node, stackFrame?.frameId === event.activeFrameId);
          if (stackFrame !== undefined) {
            node.querySelector("span")!.textContent = `depth ${String(stackFrame.depth)}`;
            node.querySelector("output")!.textContent =
              stackFrame.returnValue === null
                ? `moves(${String(stackFrame.argument)})`
                : `moves(${String(stackFrame.argument)}) → ${String(stackFrame.returnValue)}`;
          }
        } else {
          setActive(node, stackFrame?.frameId === event.activeFrameId);
          if (stackFrame?.frameId === event.activeFrameId) {
            node.parentElement!.hidden = false;
            node.dataset.pending = "true";
            node.querySelector("span")!.textContent = `depth ${String(stackFrame.depth)}`;
            if (node.querySelector("output")!.textContent === "—") {
              node.querySelector("output")!.textContent = `moves(${String(stackFrame.argument)})`;
            }
          }
        }
      }
      if (commitState) {
        presenceTransition =
          entering.length === 0 && exiting.length === 0
            ? null
            : Object.freeze({
                entering: Object.freeze(entering),
                exiting: Object.freeze(exiting),
                finalize(): void {
                  for (const node of exiting) {
                    if (node.dataset.presence !== "exiting") continue;
                    node.parentElement!.hidden = true;
                    delete node.dataset.presence;
                  }
                  for (const node of entering) {
                    if (node.dataset.presence === "entering") delete node.dataset.presence;
                  }
                },
              });
      }
      const activeStackFrame = event.stackFrames.find(
        (candidate) => candidate.frameId === event.activeFrameId,
      );
      const active =
        activeStackFrame === undefined ? null : (frames[activeStackFrame.depth] ?? null);
      const caller =
        activeStackFrame === undefined || activeStackFrame.depth <= 0
          ? null
          : (frames[activeStackFrame.depth - 1] ?? null);
      return active !== null && caller !== null
        ? {
            from: event.kind === "call-exit" ? active : (caller as HTMLElement),
            to: event.kind === "call-exit" ? (caller as HTMLElement) : active,
            label:
              event.kind === "call-exit"
                ? locale === "zh"
                  ? "返回上一层"
                  : "return to caller"
                : locale === "zh"
                  ? "进入下一层调用"
                  : "enter next call",
            eventId: event.id,
          }
        : null;
    },
    consumePresenceTransition(): VisualPresenceTransition | null {
      const transition = presenceTransition;
      presenceTransition = null;
      return transition;
    },
    applyLocale(nextLocale: FoaLocale): void {
      locale = nextLocale;
    },
    destroy(): void {},
  });
}

function createGridRenderer(
  host: HTMLElement,
  model: FoaTransitionRuntime7580Timeline,
  initialLocale: FoaLocale,
): VisualRenderer {
  let locale = initialLocale;
  const grid = documentFor(host).createElement("div");
  grid.className = "foa-transition-prototype__matrix";
  const cells: HTMLElement[][] = [];
  for (let row = 0; row < 3; row += 1) {
    const rowCells: HTMLElement[] = [];
    for (let column = 0; column < 3; column += 1) {
      const cell = visualNode(
        host,
        `matrix-${String(row)}-${String(column)}`,
        `${String(row)},${String(column)}`,
      );
      cell.classList.add("foa-transition-prototype__matrix-cell");
      cell.dataset.row = String(row);
      cell.dataset.column = String(column);
      grid.append(cell);
      rowCells.push(cell);
    }
    cells.push(rowCells);
  }
  host.append(grid);
  return Object.freeze({
    elements: Object.freeze(cells.flat()),
    render(nextFrame: PrototypeFrame, commitState = true): ActiveConnection | null {
      const event = nextFrame as FoaTransitionRuntime7580Event;
      for (const cell of cells.flat()) {
        const row = Number(cell.dataset.row);
        const column = Number(cell.dataset.column);
        if (commitState) {
          cell.querySelector("output")!.textContent = String(event.matrix[row]?.[column] ?? 0);
        }
        setActive(cell, event.activeCell?.row === row && event.activeCell.column === column);
        cell.dataset.skipped = String(
          event.kind === "cell-skip" &&
            event.activeCell?.row === row &&
            event.activeCell.column === column,
        );
      }
      const dependency = event.dependencies[0];
      if (dependency === undefined) return null;
      return {
        from: cells[dependency.from.row]![dependency.from.column]!,
        to: cells[dependency.to.row]![dependency.to.column]!,
        label:
          locale === "zh" ? `传递 ${String(dependency.value)}` : `pass ${String(dependency.value)}`,
        eventId: event.id,
      };
    },
    applyLocale(nextLocale: FoaLocale): void {
      locale = nextLocale;
    },
    destroy(): void {},
  });
}

function visualNode(host: HTMLElement, id: string, label: string): HTMLElement {
  const node = documentFor(host).createElement("div");
  node.className = "foa-transition-prototype__node foa-transition-prototype__essential";
  node.dataset.teachingTokenId = id;
  node.dataset.active = "false";
  const title = documentFor(host).createElement("span");
  title.textContent = label;
  const value = documentFor(host).createElement("output");
  value.textContent = "—";
  node.append(title, value);
  return node;
}

function setNodeLabel(node: HTMLElement, text: string): void {
  const label = node.querySelector("span");
  if (label !== null) {
    label.textContent = text;
    label.title = text;
  }
}

function setActive(node: HTMLElement, active: boolean): void {
  node.dataset.active = String(active);
  node.dataset.state = active ? "active" : "idle";
}

function createDefaultModel(order: FoaTransitionPrototypeStageOrder): PrototypeModel {
  if (order === 63) return createFoaTransitionRuntime63();
  if (order === 70) return createFoaTransitionRuntime70();
  if (order === 75) return createFoaTransitionRuntime75();
  return createFoaTransitionRuntime80();
}

function assertModelAnchors(source: string, model: PrototypeModel): void {
  if ("anchors" in model) {
    assertFoaTransitionRuntime7580Anchors(source, model);
    return;
  }
  for (const anchor of model.sourceAnchors) {
    const first = source.indexOf(anchor.exact);
    if (first < 0 || source.indexOf(anchor.exact, first + 1) >= 0) {
      throw new RangeError(`FOA transition source anchor ${anchor.id} must occur exactly once`);
    }
  }
}

function visualTitle(order: FoaTransitionPrototypeStageOrder, locale: FoaLocale): string {
  const copy = COPY[locale];
  if (order === 63) return copy.pointerLink;
  if (order === 70) return copy.searchRange;
  if (order === 75) return copy.callStack;
  return copy.pathCounts;
}

function frameSummary(frame: PrototypeFrame, locale: FoaLocale): string {
  return "summary" in frame ? frame.summary[locale] : frame.label[locale];
}

function frameOutput(frame: PrototypeFrame): string {
  if ("state" in frame) {
    const output = frame.state.output;
    return output === null || output === undefined || output === "" ? "—" : String(output);
  }
  return frame.output ?? "—";
}

function frameRule(model: PrototypeModel, frame: PrototypeFrame, locale: FoaLocale): string {
  if ("frames" in model) {
    const item = frame as FoaTransitionRuntimeFrame;
    if (model.lessonOrder === 63) {
      const input = item.state.inputValue ?? "?";
      const value = item.state.counterValue ?? "?";
      if (item.phase === "create") return "counter record created";
      if (item.phase === "initialise") return `counter.value ← input (${String(input)})`;
      if (item.phase === "bind") return "link → counter";
      if (item.phase === "resolve") return "link->value ↦ counter.value";
      if (item.phase === "write") return `counter.value ← ${String(value)}`;
      return `stdout ← ${String(value)}`;
    }
    const low = String(item.state.low ?? "?");
    const mid = String(item.state.mid ?? "?");
    const high = String(item.state.high ?? "?");
    if (item.phase === "initialise") return `range ← [${low}, ${high})`;
    if (item.phase === "calculate") return `mid ← ${low} + floor((${high} - ${low}) / 2)`;
    if (item.phase === "compare") return `values[${mid}] < target`;
    if (item.phase === "branch") {
      return item.branchOutcome === true ? `low ← ${mid} + 1` : `high ← ${mid}`;
    }
    return `lower_bound ← ${low}`;
  }

  const event = frame as FoaTransitionRuntime7580Event;
  if (model.lessonOrder === 75) {
    const active = event.stackFrames.find(({ frameId }) => frameId === event.activeFrameId);
    if (event.kind === "call-enter") return `push moves(${String(active?.argument ?? "?")})`;
    if (event.kind === "call-exit") {
      return `pop moves(${String(active?.argument ?? "?")}) → ${String(active?.returnValue ?? "?")}`;
    }
    return `stdout ← ${event.output ?? "?"}`;
  }
  const dependency = event.dependencies[0];
  if (event.kind === "dependency-read" && dependency !== undefined) {
    return `paths[${String(dependency.to.row)}][${String(dependency.to.column)}] += paths[${String(dependency.from.row)}][${String(dependency.from.column)}]`;
  }
  if (event.kind === "array-write" && event.activeCell !== null) {
    const value = event.matrix[event.activeCell.row]?.[event.activeCell.column] ?? "?";
    return `paths[${String(event.activeCell.row)}][${String(event.activeCell.column)}] ← ${String(value)}`;
  }
  if (event.kind === "cell-skip" && event.activeCell !== null) {
    return locale === "zh"
      ? `跳过障碍 (${String(event.activeCell.row)}, ${String(event.activeCell.column)})`
      : `skip obstacle (${String(event.activeCell.row)}, ${String(event.activeCell.column)})`;
  }
  return `stdout ← ${event.output ?? "?"}`;
}

function motionKind(frame: PrototypeFrame): "pick-key" | "compare" | "shift" | "insert" | "settle" {
  if ("phase" in frame) {
    if (frame.phase === "compare") return "compare";
    if (frame.phase === "write") return "insert";
    if (frame.phase === "branch") return "shift";
    return "settle";
  }
  if (frame.kind === "dependency-read") return "compare";
  if (frame.kind === "array-write") return "insert";
  if (frame.kind === "call-enter" || frame.kind === "call-exit") return "shift";
  return "settle";
}

function relationLabel(
  model: FoaTransitionRuntimePrototype,
  relationId: string,
  locale: FoaLocale,
): string {
  return model.relations.find(({ id }) => id === relationId)?.label[locale] ?? relationId;
}

function parseStateValues(value: unknown): readonly number[] {
  return String(value)
    .replace(/[\[\]]/gu, "")
    .split(",")
    .map((item) => Number(item.trim()))
    .filter(Number.isFinite);
}

function parseIntegerInput(value: string): number {
  const normalized = value.trim();
  if (!/^-?\d+$/u.test(normalized)) throw new TypeError("Expected an integer input");
  const parsed = Number(normalized);
  if (!Number.isSafeInteger(parsed))
    throw new RangeError("Integer input is outside the safe range");
  return parsed;
}

function prototype75Input(model: PrototypeModel): number {
  if (!("events" in model)) return 4;
  const first = model.events.find((event) => event.kind === "call-enter");
  return first?.stackFrames[0]?.argument ?? 4;
}

function currentOpenGrid(model: PrototypeModel): number[][] {
  if (!("events" in model) || model.lessonOrder !== 80) {
    return FOA_LESSON_80_DEFAULT_OPEN_GRID.map((row) => [...row]);
  }
  const skipped = new Set(
    model.events
      .filter((event) => event.kind === "cell-skip" && event.activeCell !== null)
      .map((event) => `${String(event.activeCell!.row)}:${String(event.activeCell!.column)}`),
  );
  return Array.from({ length: 3 }, (_, row) =>
    Array.from({ length: 3 }, (_, column) =>
      skipped.has(`${String(row)}:${String(column)}`) ? 0 : 1,
    ),
  );
}

function connectionGeometry(
  canvas: HTMLElement,
  from: HTMLElement,
  to: HTMLElement,
  constrainToVisibleCanvas = false,
): EdgeGeometry | null {
  const canvasRect = canvas.getBoundingClientRect();
  const fromRect = from.getBoundingClientRect();
  const toRect = to.getBoundingClientRect();
  if (canvasRect.width <= 0 || canvasRect.height <= 0 || fromRect.width <= 0 || toRect.width <= 0) {
    return null;
  }
  if (
    constrainToVisibleCanvas &&
    (!isFullyVisibleConnectionEndpoint(canvas, canvasRect, from, fromRect) ||
      !isFullyVisibleConnectionEndpoint(canvas, canvasRect, to, toRect))
  ) {
    return null;
  }
  const fromCenter = {
    x: fromRect.left - canvasRect.left + fromRect.width / 2,
    y: fromRect.top - canvasRect.top + fromRect.height / 2,
  };
  const toCenter = {
    x: toRect.left - canvasRect.left + toRect.width / 2,
    y: toRect.top - canvasRect.top + toRect.height / 2,
  };
  const rawStart = rectangleBoundaryPoint(fromCenter, toCenter, fromRect.width, fromRect.height, 0);
  const rawEnd = rectangleBoundaryPoint(toCenter, fromCenter, toRect.width, toRect.height, 0);
  const availableGap = Math.hypot(rawEnd.x - rawStart.x, rawEnd.y - rawStart.y);
  // A fixed clearance can cross over when adjacent cells are only a few pixels apart, reversing
  // the apparent arrow direction. Scale both clearances to leave at least one forward pixel.
  const clearanceScale = Math.min(1, Math.max(0, availableGap - 1) / 7);
  const start = rectangleBoundaryPoint(
    fromCenter,
    toCenter,
    fromRect.width,
    fromRect.height,
    2 * clearanceScale,
  );
  const end = rectangleBoundaryPoint(
    toCenter,
    fromCenter,
    toRect.width,
    toRect.height,
    5 * clearanceScale,
  );
  const controlX = (start.x + end.x) / 2;
  const rawControlY = connectionControlY(start.x, start.y, end.x, end.y);
  const controlY = constrainToVisibleCanvas
    ? Math.min(Math.max(rawControlY, 8), Math.max(8, canvasRect.height - 8))
    : rawControlY;
  return Object.freeze({
    startX: start.x,
    startY: start.y,
    endX: end.x,
    endY: end.y,
    controlX,
    controlY,
    length: quadraticBezierLength(start.x, start.y, controlX, controlY, end.x, end.y),
  });
}

function isFullyVisibleConnectionEndpoint(
  canvas: HTMLElement,
  canvasRect: DOMRect,
  endpoint: HTMLElement,
  endpointRect: DOMRect,
): boolean {
  if (!rectContains(canvasRect, endpointRect, 1)) return false;
  const getStyle = canvas.ownerDocument.defaultView?.getComputedStyle.bind(
    canvas.ownerDocument.defaultView,
  );
  for (
    let ancestor = endpoint.parentElement;
    ancestor !== null;
    ancestor = ancestor.parentElement
  ) {
    if (getStyle === undefined) continue;
    const style = getStyle(ancestor);
    const clipsX = /^(?:auto|clip|hidden|scroll)$/u.test(style.overflowX);
    const clipsY = /^(?:auto|clip|hidden|scroll)$/u.test(style.overflowY);
    if (!clipsX && !clipsY) continue;
    const ancestorRect = ancestor.getBoundingClientRect();
    if (
      (clipsX &&
        (endpointRect.left < ancestorRect.left - 1 ||
          endpointRect.right > ancestorRect.right + 1)) ||
      (clipsY &&
        (endpointRect.top < ancestorRect.top - 1 || endpointRect.bottom > ancestorRect.bottom + 1))
    ) {
      return false;
    }
  }
  const viewport = canvas.ownerDocument.defaultView;
  if (
    viewport !== null &&
    (endpointRect.left < -1 ||
      endpointRect.right > viewport.innerWidth + 1 ||
      endpointRect.top < -1 ||
      endpointRect.bottom > viewport.innerHeight + 1)
  ) {
    return false;
  }
  return true;
}

function rectContains(outer: DOMRect, inner: DOMRect, tolerance: number): boolean {
  return (
    inner.left >= outer.left - tolerance &&
    inner.right <= outer.right + tolerance &&
    inner.top >= outer.top - tolerance &&
    inner.bottom <= outer.bottom + tolerance
  );
}

function connectionControlY(startX: number, startY: number, endX: number, endY: number): number {
  const horizontal = Math.abs(endX - startX);
  const vertical = Math.abs(endY - startY);
  if (horizontal <= vertical) return (startY + endY) / 2;
  const arc = horizontal < 80 ? horizontal / 5 : Math.min(64, Math.max(32, horizontal / 4));
  return Math.min(startY, endY) - arc;
}

function bezierTokenKeyframes(geometry: EdgeGeometry): Keyframe[] {
  return Array.from({ length: 9 }, (_, index) => {
    const progress = index / 8;
    const inverse = 1 - progress;
    const x =
      inverse * inverse * geometry.startX +
      2 * inverse * progress * geometry.controlX +
      progress * progress * geometry.endX;
    const y =
      inverse * inverse * geometry.startY +
      2 * inverse * progress * geometry.controlY +
      progress * progress * geometry.endY;
    return {
      transform: tokenTransform(x, y),
      opacity: 0.45 + progress * 0.55,
      offset: progress,
    };
  });
}

function quadraticBezierLength(
  startX: number,
  startY: number,
  controlX: number,
  controlY: number,
  endX: number,
  endY: number,
): number {
  let length = 0;
  let previousX = startX;
  let previousY = startY;
  for (let index = 1; index <= 12; index += 1) {
    const progress = index / 12;
    const inverse = 1 - progress;
    const x =
      inverse * inverse * startX + 2 * inverse * progress * controlX + progress * progress * endX;
    const y =
      inverse * inverse * startY + 2 * inverse * progress * controlY + progress * progress * endY;
    length += Math.hypot(x - previousX, y - previousY);
    previousX = x;
    previousY = y;
  }
  return length;
}

function resolveFrameSourceSelection(
  source: string,
  model: PrototypeModel,
  frame: PrototypeFrame,
  frameIndex: number,
): ResolvedFrameSource {
  const anchors = "sourceAnchors" in model ? model.sourceAnchors : model.anchors;
  const anchor = anchors.find(({ id }) => id === frame.sourceAnchorId);
  if (anchor === undefined) {
    throw new RangeError(`Missing source anchor ${frame.sourceAnchorId}`);
  }
  const offset = source.indexOf(anchor.exact);
  if (offset < 0 || source.indexOf(anchor.exact, offset + 1) >= 0) {
    throw new RangeError(`Source anchor ${frame.sourceAnchorId} must occur exactly once`);
  }
  return Object.freeze({
    frameId: frame.id,
    frameIndex,
    sourceAnchorId: frame.sourceAnchorId,
    sourceLine: source.slice(0, offset).split(/\r?\n/u).length,
    sourceText: anchor.exact,
  });
}

function rectangleBoundaryPoint(
  center: { readonly x: number; readonly y: number },
  toward: { readonly x: number; readonly y: number },
  width: number,
  height: number,
  spacing: number,
): { readonly x: number; readonly y: number } {
  const deltaX = toward.x - center.x;
  const deltaY = toward.y - center.y;
  if (Math.abs(deltaX) < 0.001 && Math.abs(deltaY) < 0.001) return center;
  const halfWidth = Math.max(1, width / 2 + spacing);
  const halfHeight = Math.max(1, height / 2 + spacing);
  const scale = 1 / Math.max(Math.abs(deltaX) / halfWidth, Math.abs(deltaY) / halfHeight);
  return Object.freeze({ x: center.x + deltaX * scale, y: center.y + deltaY * scale });
}

function rectanglesOverlap(left: DOMRect, right: DOMRect): boolean {
  const horizontal = Math.min(left.right, right.right) - Math.max(left.left, right.left);
  const vertical = Math.min(left.bottom, right.bottom) - Math.max(left.top, right.top);
  return horizontal > 1 && vertical > 1;
}

function isVisibleInsideLocalScroller(node: HTMLElement, rectangle: DOMRect): boolean {
  const localScroller =
    typeof node.closest === "function"
      ? node.closest<HTMLElement>(".foa-transition-prototype__array")
      : null;
  if (
    localScroller === null ||
    (localScroller.scrollWidth <= localScroller.clientWidth + 1 &&
      localScroller.scrollHeight <= localScroller.clientHeight + 1)
  ) {
    return true;
  }
  const viewport = localScroller.getBoundingClientRect();
  const horizontal =
    Math.min(rectangle.right, viewport.right) - Math.max(rectangle.left, viewport.left);
  const vertical =
    Math.min(rectangle.bottom, viewport.bottom) - Math.max(rectangle.top, viewport.top);
  return horizontal > 1 && vertical > 1;
}

function keepChildVisible(container: HTMLElement, child: HTMLElement): void {
  const containerRect = container.getBoundingClientRect();
  const childRect = child.getBoundingClientRect();
  if (containerRect.width <= 0 || childRect.width <= 0) return;
  if (childRect.left < containerRect.left) {
    container.scrollLeft -= containerRect.left - childRect.left;
  } else if (childRect.right > containerRect.right) {
    container.scrollLeft += childRect.right - containerRect.right;
  }
}

function tokenTransform(x: number, y: number): string {
  return `translate3d(calc(${String(x)}px - 50%), calc(${String(y)}px - 50%), 0)`;
}

function playbackDelay(frame: PrototypeFrame): number {
  const kind = motionKind(frame);
  if (kind === "compare") return 1_650;
  if (kind === "shift") return 1_550;
  if (kind === "insert") return 1_450;
  return 1_300;
}

function documentFor(host: HTMLElement): Document {
  return host.ownerDocument;
}

function subscribeToMediaQuery(
  query: MediaQueryList | null,
  listener: (matches: boolean) => void,
): () => void {
  if (query === null) return () => {};
  const onChange = (event: MediaQueryListEvent): void => listener(event.matches);
  query.addEventListener?.("change", onChange);
  return () => query.removeEventListener?.("change", onChange);
}

function createResizeObserver(
  ownerDocument: Document,
  callback: () => void,
): ResizeObserver | null {
  const Constructor = ownerDocument.defaultView?.ResizeObserver;
  return Constructor === undefined ? null : new Constructor(callback);
}

function requestFrame(ownerDocument: Document, callback: FrameRequestCallback): number {
  return (
    ownerDocument.defaultView?.requestAnimationFrame?.(callback) ??
    ownerDocument.defaultView?.setTimeout(() => callback(performance.now()), 16) ??
    -1
  );
}

function cancelFrame(ownerDocument: Document, request: number): void {
  if (request < 0) return;
  if (ownerDocument.defaultView?.cancelAnimationFrame !== undefined) {
    ownerDocument.defaultView.cancelAnimationFrame(request);
  } else {
    ownerDocument.defaultView?.clearTimeout(request);
  }
}
