import type {
  LearningFragmentKind,
  LearningStageDefinition,
  PresetAlternativeVersion,
  PresetBlockDefinition,
  PresetBlockKind,
  PresetBlockScenario,
  PresetPortDefinition,
  PresetSourceBlockDefinition,
  PresetVirtualBlockDefinition,
} from "./contracts.js";

export const BUILTIN_LEARNING_STAGES: readonly LearningStageDefinition[] = Object.freeze([
  stage("c.basics", "C 入门", 10, [], "变量、声明、赋值与基本表达式。"),
  stage("c.control-flow", "控制流", 20, ["c.basics"], "条件、循环与显式控制转移。"),
  stage(
    "c.functions-arrays",
    "函数与数组",
    30,
    ["c.control-flow"],
    "函数调用、参数、输入输出、数组、字符串、指针与本地内存。",
  ),
  stage(
    "algorithms.search",
    "搜索",
    40,
    ["c.functions-arrays"],
    "线性搜索与有序数据搜索的基本结构。",
  ),
  stage("algorithms.sort", "排序", 50, ["c.functions-arrays"], "比较、交换与逐步建立有序区间。"),
  stage(
    "algorithms.recursion",
    "递归",
    60,
    ["c.functions-arrays"],
    "基础情形、递归调用与规模缩减。",
  ),
  stage(
    "data-structures.linear",
    "线性结构",
    70,
    ["c.functions-arrays"],
    "链表、栈与队列中的局部更新。",
  ),
  stage(
    "data-structures.trees",
    "树与图结构",
    80,
    ["algorithms.recursion", "data-structures.linear"],
    "树节点、邻接结构、遍历队列与递归访问。",
  ),
  stage(
    "analysis.correctness-complexity",
    "正确性与复杂度",
    90,
    ["algorithms.search", "algorithms.sort"],
    "断言、不变量、边界案例、计时与基础操作计数。",
  ),
]);

const VIRTUAL_PRESETS: readonly PresetVirtualBlockDefinition[] = Object.freeze([
  virtualPreset(
    "builtin.flow.start",
    "开始",
    "c.control-flow",
    "定义一次流程运行的唯一入口，不生成 C 语句。",
    [controlPort("control.next", "下一步", "output", "one")],
  ),
  virtualPreset(
    "builtin.flow.end",
    "结束",
    "c.control-flow",
    "标记一条流程路径完成，不替代函数中的 return。",
    [controlPort("control.in", "进入", "input", "many")],
  ),
  virtualPreset(
    "builtin.flow.pause",
    "暂停",
    "c.control-flow",
    "暂停教学回放，等待用户继续；真实 C 执行语义保持不变。",
    [
      controlPort("control.in", "进入", "input", "one"),
      controlPort("control.next", "继续", "output", "one"),
    ],
  ),
  virtualPreset(
    "builtin.flow.checkpoint",
    "Checkpoint",
    "analysis.correctness-complexity",
    "在回放中记录局部状态与指标，不向 main.c 写入探针。",
    [
      controlPort("control.in", "进入", "input", "one"),
      controlPort("control.next", "继续", "output", "one"),
      dataPort("data.snapshot", "状态快照", "output", "many", "runtime-snapshot"),
    ],
  ),
  virtualPreset(
    "builtin.flow.merge",
    "路径汇合",
    "c.control-flow",
    "把互斥控制路径汇合到一个后继节点，不生成额外 C。",
    [
      controlPort("control.in", "进入", "input", "many"),
      controlPort("control.next", "下一步", "output", "one"),
    ],
  ),
]);

const SOURCE_PRESETS: readonly PresetSourceBlockDefinition[] = Object.freeze([
  sourcePreset(
    "builtin.control.if",
    "条件分支",
    "control",
    "c.control-flow",
    "if (condition) {\n  action();\n}",
    "条件非零时执行一个动作。",
    "control",
    "control",
    { branches: ["true", "false"], requiresSymbols: ["condition", "action"] },
  ),
  sourcePreset(
    "builtin.control.if-else",
    "双路分支",
    "control",
    "c.control-flow",
    "if (condition) {\n  when_true();\n} else {\n  when_false();\n}",
    "按条件在两个动作中选择一个。",
    "control",
    "control",
    { branches: ["true", "false"], requiresSymbols: ["condition", "when_true", "when_false"] },
  ),
  sourcePreset(
    "builtin.control.switch",
    "多路选择",
    "flow-control",
    "c.control-flow",
    "switch (choice) {\n  case 0:\n    first();\n    break;\n  default:\n    fallback();\n    break;\n}",
    "按一个整数或枚举值选择 case，并保留 default 路径。",
    "control",
    "control",
    { branches: ["case-0", "default"], requiresSymbols: ["choice", "first", "fallback"] },
  ),
  sourcePreset(
    "builtin.control.for",
    "计数循环",
    "control",
    "c.control-flow",
    "for (int i = 0; i < limit; i++) {\n  action();\n}",
    "从零开始按固定步长重复执行。",
    "control",
    "control",
    { branches: ["body", "exit"], requiresSymbols: ["limit", "action"] },
  ),
  sourcePreset(
    "builtin.control.while",
    "条件循环",
    "control",
    "c.control-flow",
    "while (condition) {\n  action();\n}",
    "只要条件非零就继续执行动作。",
    "control",
    "control",
    {
      branches: ["body", "exit"],
      requiresSymbols: ["condition", "action"],
      alternatives: [alternative("0.9.0", "先执行一次", "do {\n  action();\n} while (condition);")],
    },
  ),
  sourcePreset(
    "builtin.control.do-while",
    "先执行循环",
    "flow-control",
    "c.control-flow",
    "do {\n  action();\n} while (condition);",
    "先执行一次循环体，再检查继续条件。",
    "control",
    "control",
    { branches: ["body", "exit"], requiresSymbols: ["condition", "action"] },
  ),
  sourcePreset(
    "builtin.control.break",
    "结束当前循环",
    "flow-control",
    "c.control-flow",
    "break;",
    "立即离开最内层循环或 switch。",
    "statement",
    "control",
  ),
  sourcePreset(
    "builtin.control.continue",
    "进入下一轮",
    "flow-control",
    "c.control-flow",
    "continue;",
    "跳过本轮剩余语句并进入下一次循环判断。",
    "statement",
    "control",
  ),

  sourcePreset(
    "builtin.c.declare-integer",
    "声明整数",
    "declaration",
    "c.basics",
    "int value = 0;",
    "声明一个带初始值的整数变量。",
    "statement",
    "statement",
  ),
  sourcePreset(
    "builtin.c.declare-double",
    "声明小数",
    "c-basics",
    "c.basics",
    "double value = 0.0;",
    "声明一个双精度浮点变量。",
    "statement",
    "statement",
  ),
  sourcePreset(
    "builtin.c.declare-character",
    "声明字符",
    "c-basics",
    "c.basics",
    "char symbol = '\\0';",
    "声明一个字符并初始化为空字符。",
    "statement",
    "statement",
  ),
  sourcePreset(
    "builtin.c.declare-constant",
    "声明只读值",
    "c-basics",
    "c.basics",
    "const int limit = 10;",
    "用 const 表达初始化后不应再修改的值。",
    "statement",
    "statement",
  ),
  sourcePreset(
    "builtin.c.assign-value",
    "更新变量",
    "assignment",
    "c.basics",
    "value = expression;",
    "把表达式结果写入已有变量。",
    "statement",
    "statement",
    { requiresSymbols: ["value", "expression"] },
  ),
  sourcePreset(
    "builtin.c.add-assign",
    "累加变量",
    "c-basics",
    "c.basics",
    "total += value;",
    "把新值累加到已有总量。",
    "statement",
    "statement",
    { requiresSymbols: ["total", "value"] },
  ),
  sourcePreset(
    "builtin.c.increment",
    "增加一",
    "c-basics",
    "c.basics",
    "value++;",
    "把整数变量增加一。",
    "statement",
    "statement",
    {
      requiresSymbols: ["value"],
      alternatives: [alternative("0.9.0", "复合赋值", "value += 1;")],
    },
  ),
  sourcePreset(
    "builtin.c.arithmetic",
    "组合算术表达式",
    "c-basics",
    "c.basics",
    "result = left + right * scale;",
    "按 C 运算符优先级计算并保存结果。",
    "statement",
    "statement",
    { requiresSymbols: ["result", "left", "right", "scale"] },
  ),
  sourcePreset(
    "builtin.c.compare-flag",
    "保存比较结果",
    "c-basics",
    "c.basics",
    "int is_less = left < right;",
    "把关系表达式的 0 或 1 结果保存为整数标志。",
    "statement",
    "statement",
    { requiresSymbols: ["left", "right"] },
  ),
  sourcePreset(
    "builtin.c.cast-integer",
    "显式转为整数",
    "c-basics",
    "c.basics",
    "int truncated = (int)value;",
    "明确表达浮点值转整数时的小数截断。",
    "statement",
    "statement",
    { requiresSymbols: ["value"] },
  ),

  sourcePreset(
    "builtin.c.print-integer",
    "输出整数",
    "io",
    "c.basics",
    'printf("%d\\n", value);',
    "把一个整数和换行输出到标准输出。",
    "statement",
    "function",
    { requiresHeaders: ["stdio.h"], requiresSymbols: ["value"] },
  ),
  sourcePreset(
    "builtin.io.print-text",
    "输出文本",
    "functions-io",
    "c.functions-arrays",
    'printf("%s\\n", text);',
    "输出以 NUL 结尾的字符串。",
    "statement",
    "function",
    { requiresHeaders: ["stdio.h"], requiresSymbols: ["text"] },
  ),
  sourcePreset(
    "builtin.io.scan-integer",
    "读取整数",
    "functions-io",
    "c.functions-arrays",
    'scanf("%d", &value);',
    "从标准输入读取整数到变量地址。",
    "statement",
    "function",
    { requiresHeaders: ["stdio.h"], requiresSymbols: ["value"] },
  ),
  sourcePreset(
    "builtin.functions.call",
    "调用函数",
    "function-call",
    "c.functions-arrays",
    "result = function(argument);",
    "调用一个已有函数并保存返回值。",
    "statement",
    "function",
    { requiresSymbols: ["result", "function", "argument"] },
  ),
  sourcePreset(
    "builtin.functions.call-void",
    "调用过程",
    "function-call",
    "c.functions-arrays",
    "function(argument);",
    "调用一个已有函数，不接收返回值。",
    "statement",
    "function",
    { requiresSymbols: ["function", "argument"] },
  ),
  sourcePreset(
    "builtin.c.return-success",
    "正常返回",
    "function-control",
    "c.basics",
    "return 0;",
    "从当前函数返回成功状态。",
    "statement",
    "function",
  ),
  sourcePreset(
    "builtin.functions.return-value",
    "返回结果",
    "functions-io",
    "c.functions-arrays",
    "return value;",
    "结束当前函数并把结果交给调用者。",
    "statement",
    "function",
    { requiresSymbols: ["value"] },
  ),
  sourcePreset(
    "builtin.io.put-character",
    "输出字符",
    "functions-io",
    "c.functions-arrays",
    "fputc(symbol, stdout);",
    "向标准输出写入一个字符。",
    "statement",
    "function",
    { requiresHeaders: ["stdio.h"], requiresSymbols: ["symbol"] },
  ),
  sourcePreset(
    "builtin.io.read-character",
    "读取字符",
    "functions-io",
    "c.functions-arrays",
    "int symbol = fgetc(stdin);",
    "读取一个字符，并保留 EOF 所需的 int 范围。",
    "statement",
    "function",
    { requiresHeaders: ["stdio.h"] },
  ),
  sourcePreset(
    "builtin.io.report-error",
    "输出错误信息",
    "functions-io",
    "c.functions-arrays",
    'fprintf(stderr, "%s\\n", message);',
    "把错误信息写入标准错误流。",
    "statement",
    "function",
    { requiresHeaders: ["stdio.h"], requiresSymbols: ["message"] },
  ),

  sourcePreset(
    "builtin.arrays.declare",
    "声明数组",
    "array",
    "c.functions-arrays",
    "int values[10] = {0};",
    "声明并清零一个固定长度整数数组。",
    "statement",
    "statement",
  ),
  sourcePreset(
    "builtin.arrays.read",
    "读取数组元素",
    "arrays-strings",
    "c.functions-arrays",
    "value = values[index];",
    "按索引读取数组元素。",
    "statement",
    "statement",
    { requiresSymbols: ["value", "values", "index"] },
  ),
  sourcePreset(
    "builtin.arrays.write",
    "写入数组元素",
    "arrays-strings",
    "c.functions-arrays",
    "values[index] = value;",
    "按索引更新数组元素。",
    "statement",
    "statement",
    { requiresSymbols: ["values", "index", "value"] },
  ),
  sourcePreset(
    "builtin.arrays.length",
    "计算固定数组长度",
    "arrays-strings",
    "c.functions-arrays",
    "int length = (int)(sizeof values / sizeof values[0]);",
    "在数组仍是数组类型的作用域内计算元素个数。",
    "statement",
    "statement",
    { requiresSymbols: ["values"] },
  ),
  sourcePreset(
    "builtin.arrays.initialize-loop",
    "逐项初始化",
    "arrays-strings",
    "c.functions-arrays",
    "for (int i = 0; i < length; i++) {\n  values[i] = initial;\n}",
    "按索引给数组的有效区间赋初值。",
    "control",
    "module",
    { branches: ["body", "exit"], requiresSymbols: ["length", "values", "initial"] },
  ),
  sourcePreset(
    "builtin.strings.declare",
    "声明字符串缓冲区",
    "arrays-strings",
    "c.functions-arrays",
    'char text[32] = "";',
    "声明一个以空字符串开始的固定容量字符数组。",
    "statement",
    "statement",
  ),
  sourcePreset(
    "builtin.strings.length",
    "取得字符串长度",
    "arrays-strings",
    "c.functions-arrays",
    "int length = (int)strlen(text);",
    "取得首个 NUL 字符之前的字符数。",
    "statement",
    "function",
    { requiresHeaders: ["string.h"], requiresSymbols: ["text"] },
  ),
  sourcePreset(
    "builtin.strings.compare",
    "比较字符串",
    "arrays-strings",
    "c.functions-arrays",
    "int order = strcmp(left, right);",
    "按字典序比较两个 NUL 结尾字符串。",
    "statement",
    "function",
    { requiresHeaders: ["string.h"], requiresSymbols: ["left", "right"] },
  ),
  sourcePreset(
    "builtin.strings.copy-bounded",
    "限长复制字符串",
    "arrays-strings",
    "c.functions-arrays",
    'snprintf(destination, capacity, "%s", source);',
    "按目标容量复制并保证正常情况下以 NUL 结尾。",
    "statement",
    "function",
    {
      requiresHeaders: ["stdio.h"],
      requiresSymbols: ["destination", "capacity", "source"],
    },
  ),
  sourcePreset(
    "builtin.arrays.matrix-access",
    "访问矩阵元素",
    "arrays-strings",
    "c.functions-arrays",
    "value = matrix[row][column];",
    "用行列索引读取二维数组元素。",
    "statement",
    "statement",
    { requiresSymbols: ["value", "matrix", "row", "column"] },
  ),

  sourcePreset(
    "builtin.pointers.address",
    "取得变量地址",
    "pointers-memory",
    "c.functions-arrays",
    "int *pointer = &value;",
    "把整数变量的地址保存为指针。",
    "statement",
    "statement",
    { requiresSymbols: ["value"] },
  ),
  sourcePreset(
    "builtin.pointers.read",
    "解引用读取",
    "pointers-memory",
    "c.functions-arrays",
    "value = *pointer;",
    "读取指针指向的对象；运行前必须证明指针有效。",
    "statement",
    "statement",
    { requiresSymbols: ["value", "pointer"] },
  ),
  sourcePreset(
    "builtin.pointers.write",
    "解引用写入",
    "pointers-memory",
    "c.functions-arrays",
    "*pointer = value;",
    "写入指针指向的对象；运行前必须证明目标可写。",
    "statement",
    "statement",
    { requiresSymbols: ["pointer", "value"] },
  ),
  sourcePreset(
    "builtin.pointers.null",
    "初始化空指针",
    "pointers-memory",
    "c.functions-arrays",
    "int *pointer = NULL;",
    "用 NULL 表示当前没有可解引用目标。",
    "statement",
    "statement",
    { requiresHeaders: ["stddef.h"] },
  ),
  sourcePreset(
    "builtin.pointers.null-guard",
    "检查空指针",
    "pointers-memory",
    "c.functions-arrays",
    "if (pointer == NULL) {\n  handle_error();\n}",
    "在解引用前处理没有目标的路径。",
    "control",
    "control",
    { branches: ["null", "valid"], requiresSymbols: ["pointer", "handle_error"] },
  ),
  sourcePreset(
    "builtin.memory.malloc",
    "分配动态数组",
    "pointers-memory",
    "c.functions-arrays",
    "pointer = malloc(count * sizeof *pointer);",
    "按元素数量分配未初始化内存，并保留失败检查责任。",
    "statement",
    "function",
    { requiresHeaders: ["stdlib.h"], requiresSymbols: ["pointer", "count"] },
  ),
  sourcePreset(
    "builtin.memory.calloc",
    "分配清零数组",
    "pointers-memory",
    "c.functions-arrays",
    "pointer = calloc(count, sizeof *pointer);",
    "分配并把所有字节清零，仍需检查返回值。",
    "statement",
    "function",
    { requiresHeaders: ["stdlib.h"], requiresSymbols: ["pointer", "count"] },
  ),
  sourcePreset(
    "builtin.memory.realloc",
    "调整动态数组",
    "pointers-memory",
    "c.functions-arrays",
    "resized = realloc(pointer, new_count * sizeof *pointer);",
    "先保存 realloc 结果，成功后再替换原指针。",
    "statement",
    "function",
    {
      requiresHeaders: ["stdlib.h"],
      requiresSymbols: ["resized", "pointer", "new_count"],
    },
  ),
  sourcePreset(
    "builtin.memory.free",
    "释放动态内存",
    "pointers-memory",
    "c.functions-arrays",
    "free(pointer);",
    "释放一次仍由当前路径拥有的动态内存。",
    "statement",
    "function",
    { requiresHeaders: ["stdlib.h"], requiresSymbols: ["pointer"] },
  ),
  sourcePreset(
    "builtin.pointers.advance",
    "移动指针",
    "pointers-memory",
    "c.functions-arrays",
    "pointer++;",
    "把指针移动到同一数组对象中的下一个元素。",
    "statement",
    "statement",
    { requiresSymbols: ["pointer"] },
  ),

  sourcePreset(
    "builtin.linear.advance-node",
    "移动到下一节点",
    "linear-structure",
    "data-structures.linear",
    "node = node->next;",
    "沿链式结构移动到下一个节点。",
    "statement",
    "statement",
    { requiresSymbols: ["node"] },
  ),
  sourcePreset(
    "builtin.linear.insert-after",
    "链表后插",
    "data-structures",
    "data-structures.linear",
    "do {\n  new_node->next = node->next;\n  node->next = new_node;\n} while (0);",
    "按先接后继、再接前驱的顺序插入节点。",
    "control",
    "module",
    { requiresSymbols: ["new_node", "node"] },
  ),
  sourcePreset(
    "builtin.linear.remove-after",
    "链表后删",
    "data-structures",
    "data-structures.linear",
    "if (node != NULL && node->next != NULL) {\n  removed = node->next;\n  node->next = removed->next;\n  free(removed);\n}",
    "断开并释放当前节点的后继节点。",
    "control",
    "module",
    {
      branches: ["removed", "unchanged"],
      requiresHeaders: ["stdlib.h"],
      requiresSymbols: ["node", "removed"],
    },
  ),
  sourcePreset(
    "builtin.stack.push",
    "数组栈入栈",
    "data-structures",
    "data-structures.linear",
    "do {\n  stack[top] = value;\n  top++;\n} while (0);",
    "在容量检查通过后写入栈顶并增加 top。",
    "control",
    "module",
    { requiresSymbols: ["stack", "top", "value"] },
  ),
  sourcePreset(
    "builtin.stack.pop",
    "数组栈出栈",
    "data-structures",
    "data-structures.linear",
    "do {\n  top--;\n  value = stack[top];\n} while (0);",
    "在非空检查通过后先缩小 top，再读取原栈顶。",
    "control",
    "module",
    { requiresSymbols: ["stack", "top", "value"] },
  ),
  sourcePreset(
    "builtin.queue.enqueue",
    "循环队列入队",
    "data-structures",
    "data-structures.linear",
    "do {\n  queue[tail] = value;\n  tail = (tail + 1) % capacity;\n} while (0);",
    "写入队尾并让尾索引按容量回绕。",
    "control",
    "module",
    { requiresSymbols: ["queue", "tail", "value", "capacity"] },
  ),
  sourcePreset(
    "builtin.queue.dequeue",
    "循环队列出队",
    "data-structures",
    "data-structures.linear",
    "do {\n  value = queue[head];\n  head = (head + 1) % capacity;\n} while (0);",
    "读取队头并让头索引按容量回绕。",
    "control",
    "module",
    { requiresSymbols: ["queue", "head", "value", "capacity"] },
  ),
  sourcePreset(
    "builtin.trees.visit-left",
    "访问左子树",
    "tree",
    "data-structures.trees",
    "visit(root->left);",
    "对当前节点的左子树执行递归访问。",
    "statement",
    "function",
    { requiresSymbols: ["visit", "root"] },
  ),
  sourcePreset(
    "builtin.trees.visit-right",
    "访问右子树",
    "data-structures",
    "data-structures.trees",
    "visit(root->right);",
    "对当前节点的右子树执行递归访问。",
    "statement",
    "function",
    { requiresSymbols: ["visit", "root"] },
  ),
  sourcePreset(
    "builtin.graphs.adjacency-loop",
    "遍历邻接边",
    "data-structures",
    "data-structures.trees",
    "for (int edge = head[node]; edge != -1; edge = next[edge]) {\n  visit(to[edge]);\n}",
    "沿邻接表访问指定节点的每一条出边。",
    "control",
    "module",
    {
      branches: ["edge", "exit"],
      requiresSymbols: ["head", "node", "next", "visit", "to"],
    },
  ),

  sourcePreset(
    "builtin.search.match",
    "记录搜索命中",
    "search",
    "algorithms.search",
    "if (values[i] == target) {\n  found = i;\n  break;\n}",
    "发现目标后记录位置并停止当前循环。",
    "control",
    "control",
    { branches: ["match", "continue"], requiresSymbols: ["values", "i", "target", "found"] },
  ),
  sourcePreset(
    "builtin.search.linear-loop",
    "线性搜索",
    "algorithm-patterns",
    "algorithms.search",
    "for (int i = 0; i < length; i++) {\n  if (values[i] == target) {\n    found = i;\n    break;\n  }\n}",
    "从头到尾检查元素，命中后记录索引并停止。",
    "control",
    "module",
    { branches: ["scan", "exit"], requiresSymbols: ["length", "values", "target", "found"] },
  ),
  sourcePreset(
    "builtin.search.binary-step",
    "二分搜索一步",
    "algorithm-patterns",
    "algorithms.search",
    "if (values[middle] < target) {\n  left = middle + 1;\n} else {\n  right = middle;\n}",
    "根据中点比较结果保留仍可能含答案的一半区间。",
    "control",
    "module",
    {
      branches: ["right-half", "left-half"],
      requiresSymbols: ["values", "middle", "target", "left", "right"],
    },
  ),
  sourcePreset(
    "builtin.sort.swap-adjacent",
    "交换相邻逆序项",
    "sort",
    "algorithms.sort",
    "if (values[j] > values[j + 1]) {\n  int temp = values[j];\n  values[j] = values[j + 1];\n  values[j + 1] = temp;\n}",
    "比较并交换一对逆序的相邻元素。",
    "control",
    "module",
    { branches: ["swap", "keep"], requiresSymbols: ["values", "j"] },
  ),
  sourcePreset(
    "builtin.sort.select-minimum",
    "更新最小元素位置",
    "algorithm-patterns",
    "algorithms.sort",
    "if (values[j] < values[min_index]) {\n  min_index = j;\n}",
    "扫描未排序区间时维护当前最小元素索引。",
    "control",
    "module",
    { branches: ["update", "keep"], requiresSymbols: ["values", "j", "min_index"] },
  ),
  sourcePreset(
    "builtin.sort.insertion-shift",
    "右移较大元素",
    "algorithm-patterns",
    "algorithms.sort",
    "while (j > 0 && values[j - 1] > key) {\n  values[j] = values[j - 1];\n  j--;\n}",
    "为插入元素腾出位置，并保持已排序前缀。",
    "control",
    "module",
    { branches: ["shift", "insert"], requiresSymbols: ["j", "values", "key"] },
  ),
  sourcePreset(
    "builtin.recursion.reduce",
    "递归缩小问题",
    "recursion",
    "algorithms.recursion",
    "return n <= 1 ? 1 : n * factorial(n - 1);",
    "用基础情形结束递归，并在递归调用中缩小规模。",
    "statement",
    "function",
    { requiresSymbols: ["n", "factorial"] },
  ),
  sourcePreset(
    "builtin.algorithms.two-pointer",
    "双指针收缩",
    "algorithm-patterns",
    "algorithms.search",
    "if (sum < target) {\n  left++;\n} else {\n  right--;\n}",
    "根据当前状态移动一个边界指针。",
    "control",
    "module",
    { branches: ["move-left", "move-right"], requiresSymbols: ["sum", "target", "left", "right"] },
  ),
  sourcePreset(
    "builtin.algorithms.sliding-window",
    "滑动窗口更新",
    "algorithm-patterns",
    "algorithms.search",
    "do {\n  window_sum -= values[left];\n  left++;\n  right++;\n  window_sum += values[right];\n} while (0);",
    "移除离开窗口的元素并加入新进入的元素。",
    "control",
    "module",
    { requiresSymbols: ["window_sum", "values", "left", "right"] },
  ),
  sourcePreset(
    "builtin.graphs.bfs-step",
    "BFS 队列一步",
    "algorithm-patterns",
    "data-structures.trees",
    "do {\n  node = queue[head++];\n  visit(node);\n} while (0);",
    "从队头取出一个节点并执行访问。",
    "control",
    "module",
    { requiresSymbols: ["node", "queue", "head", "visit"] },
  ),
  sourcePreset(
    "builtin.dynamic-programming.transition",
    "动态规划转移",
    "algorithm-patterns",
    "analysis.correctness-complexity",
    "table[i] = previous[i] + cost[i];",
    "按已解决的较小状态计算当前状态。",
    "statement",
    "module",
    { requiresSymbols: ["table", "i", "previous", "cost"] },
  ),

  sourcePreset(
    "builtin.analysis.assert",
    "检查不变量",
    "correctness",
    "analysis.correctness-complexity",
    "assert(condition);",
    "在执行过程中检查预期不变量。",
    "statement",
    "function",
    { requiresHeaders: ["assert.h"], requiresSymbols: ["condition"] },
  ),
  sourcePreset(
    "builtin.analysis.count-operation",
    "记录基础操作",
    "complexity",
    "analysis.correctness-complexity",
    "operations++;",
    "记录一次选定的基础操作，用于经验复杂度分析。",
    "statement",
    "statement",
    { requiresSymbols: ["operations"] },
  ),
  sourcePreset(
    "builtin.analysis.timer-start",
    "记录开始时钟",
    "testing-analysis",
    "analysis.correctness-complexity",
    "long started_at = clock();",
    "记录一次算法测量的起始处理器时钟。",
    "statement",
    "function",
    { requiresHeaders: ["time.h"] },
  ),
  sourcePreset(
    "builtin.analysis.timer-end",
    "计算经过时钟",
    "testing-analysis",
    "analysis.correctness-complexity",
    "long elapsed_ticks = clock() - started_at;",
    "计算同一测量区间消耗的处理器时钟数。",
    "statement",
    "function",
    { requiresHeaders: ["time.h"], requiresSymbols: ["started_at"] },
  ),
  sourcePreset(
    "builtin.testing.expected-check",
    "比较预期结果",
    "testing-analysis",
    "analysis.correctness-complexity",
    "if (actual != expected) {\n  failures++;\n}",
    "记录实际值与预期值不一致的案例。",
    "control",
    "module",
    { branches: ["failed", "passed"], requiresSymbols: ["actual", "expected", "failures"] },
  ),
  sourcePreset(
    "builtin.analysis.benchmark-loop",
    "重复基准运行",
    "testing-analysis",
    "analysis.correctness-complexity",
    "for (int sample = 0; sample < repetitions; sample++) {\n  run_case();\n}",
    "重复同一案例，为中位数统计收集多次运行。",
    "control",
    "module",
    { branches: ["sample", "complete"], requiresSymbols: ["repetitions", "run_case"] },
  ),
]);

export const BUILTIN_VIRTUAL_PRESETS: readonly PresetVirtualBlockDefinition[] = VIRTUAL_PRESETS;

/** Rich, versioned definitions used by the free-flow preset library. */
export const BUILTIN_PRESET_BLOCKS: readonly PresetBlockDefinition[] = Object.freeze([
  ...VIRTUAL_PRESETS,
  ...SOURCE_PRESETS,
]);

/** Source-only compatibility surface consumed by the existing M4 assembly palette. */
export const BUILTIN_LEARNING_TEMPLATES: readonly PresetSourceBlockDefinition[] = SOURCE_PRESETS;

interface SourcePresetOptions {
  readonly branches?: readonly string[];
  readonly requiresHeaders?: readonly string[];
  readonly requiresSymbols?: readonly string[];
  readonly alternatives?: readonly PresetAlternativeVersion[];
}

function stage(
  id: string,
  label: string,
  order: number,
  prerequisites: readonly string[],
  description: string,
): LearningStageDefinition {
  return Object.freeze({
    id,
    version: "1.0.0",
    label,
    order,
    prerequisites: Object.freeze([...prerequisites]),
    description,
  });
}

function sourcePreset(
  id: string,
  label: string,
  category: string,
  stageId: string,
  source: string,
  description: string,
  fragmentKind: LearningFragmentKind,
  blockKind: Exclude<PresetBlockKind, "virtual">,
  options: SourcePresetOptions = {},
): PresetSourceBlockDefinition {
  const ports = sourcePorts(options.branches);
  return Object.freeze({
    id,
    version: "1.0.0",
    label,
    category,
    stage: stageId,
    source,
    description,
    fragmentKind,
    blockKind,
    lifecycle: "active",
    ports,
    placement: Object.freeze({
      scope: "function-body",
      allowedParentNodeTypes: Object.freeze(["compound_statement"]),
      requiresHeaders: freezeText(options.requiresHeaders),
      requiresSymbols: freezeText(options.requiresSymbols),
    }),
    explanation: explanation(description),
    scenarios: Object.freeze([scenario(id, description)]),
    alternatives: Object.freeze([...(options.alternatives ?? [])]),
  });
}

function virtualPreset(
  id: string,
  label: string,
  stageId: string,
  description: string,
  ports: readonly PresetPortDefinition[],
): PresetVirtualBlockDefinition {
  return Object.freeze({
    id,
    version: "1.0.0",
    label,
    category: "flow-control",
    stage: stageId,
    source: null,
    description,
    fragmentKind: null,
    blockKind: "virtual",
    lifecycle: "active",
    ports: Object.freeze([...ports]),
    placement: Object.freeze({
      scope: "flow-canvas",
      allowedParentNodeTypes: Object.freeze([]),
      requiresHeaders: Object.freeze([]),
      requiresSymbols: Object.freeze([]),
    }),
    explanation: explanation(description),
    scenarios: Object.freeze([scenario(id, description)]),
    alternatives: Object.freeze([]),
  });
}

function sourcePorts(branches: readonly string[] | undefined): readonly PresetPortDefinition[] {
  const outputs =
    branches === undefined
      ? [controlPort("control.next", "下一步", "output", "one")]
      : branches.map((branch) => controlPort(`control.${branch}`, branch, "output", "one", branch));
  return Object.freeze([controlPort("control.in", "进入", "input", "one"), ...outputs]);
}

function controlPort(
  id: string,
  label: string,
  direction: PresetPortDefinition["direction"],
  cardinality: PresetPortDefinition["cardinality"],
  branch?: string,
): PresetPortDefinition {
  return Object.freeze({
    id,
    label,
    direction,
    channel: "control",
    cardinality,
    ...(branch === undefined ? {} : { branch }),
  });
}

function dataPort(
  id: string,
  label: string,
  direction: PresetPortDefinition["direction"],
  cardinality: PresetPortDefinition["cardinality"],
  dataType: string,
): PresetPortDefinition {
  return Object.freeze({ id, label, direction, channel: "data", cardinality, dataType });
}

function explanation(description: string) {
  return Object.freeze({
    summary: description,
    principle: description,
    whenToUse: Object.freeze(["当当前算法步骤与该语义完全一致时使用。"]),
    pitfalls: Object.freeze(["连接前检查作用域、变量有效性与所有分支的前置条件。"]),
  });
}

function scenario(id: string, description: string): PresetBlockScenario {
  return Object.freeze({
    id: `${id}.case.basic`,
    label: "基础案例",
    description,
    mode: "teaching",
    stdin: "",
    arguments: Object.freeze([]),
  });
}

function alternative(version: string, label: string, source: string): PresetAlternativeVersion {
  return Object.freeze({
    version,
    label,
    description: "保留用于对比写法，不作为默认版本。",
    source,
    recommended: false,
  });
}

function freezeText(values: readonly string[] | undefined): readonly string[] {
  return Object.freeze([...(values ?? [])]);
}
