import type { LearningStageDefinition, LearningTemplateDefinition } from "./contracts.js";

export const BUILTIN_LEARNING_STAGES: readonly LearningStageDefinition[] = Object.freeze([
  stage("c.basics", "C 入门", 10, [], "变量、声明、赋值与基本表达式。"),
  stage("c.control-flow", "控制流", 20, ["c.basics"], "条件、循环与显式控制转移。"),
  stage(
    "c.functions-arrays",
    "函数与数组",
    30,
    ["c.control-flow"],
    "函数调用、参数与连续数组数据。",
  ),
  stage(
    "algorithms.search",
    "搜索",
    40,
    ["c.functions-arrays"],
    "线性搜索与有序数据搜索的基本结构。",
  ),
  stage("algorithms.sort", "排序", 50, ["c.functions-arrays"], "比较、交换与逐步建立有序区间。"),
  stage(
    "algorithms.recursion",
    "递归",
    60,
    ["c.functions-arrays"],
    "基础情形、递归调用与规模缩减。",
  ),
  stage(
    "data-structures.linear",
    "线性结构",
    70,
    ["c.functions-arrays"],
    "链表、栈与队列中的局部更新。",
  ),
  stage(
    "data-structures.trees",
    "树结构",
    80,
    ["algorithms.recursion", "data-structures.linear"],
    "树节点访问与递归遍历。",
  ),
  stage(
    "analysis.correctness-complexity",
    "正确性与复杂度",
    90,
    ["algorithms.search", "algorithms.sort"],
    "断言、不变量与基础操作计数。",
  ),
]);

export const BUILTIN_LEARNING_TEMPLATES: readonly LearningTemplateDefinition[] = Object.freeze([
  template(
    "builtin.c.declare-integer",
    "声明整数",
    "declaration",
    "c.basics",
    "int value = 0;",
    "声明一个带初始值的整数变量。",
    "statement",
  ),
  template(
    "builtin.c.assign-value",
    "更新变量",
    "assignment",
    "c.basics",
    "value = expression;",
    "把表达式结果写入已有变量。",
    "statement",
  ),
  template(
    "builtin.c.print-integer",
    "输出整数",
    "io",
    "c.basics",
    'printf("%d\\n", value);',
    "把一个整数和换行输出到标准输出。",
    "statement",
  ),
  template(
    "builtin.c.return-success",
    "正常返回",
    "function-control",
    "c.basics",
    "return 0;",
    "从当前函数返回成功状态。",
    "statement",
  ),
  template(
    "builtin.control.if",
    "条件分支",
    "control",
    "c.control-flow",
    "if (condition) {\n  action();\n}",
    "条件非零时执行一个动作。",
    "control",
  ),
  template(
    "builtin.control.if-else",
    "双路分支",
    "control",
    "c.control-flow",
    "if (condition) {\n  when_true();\n} else {\n  when_false();\n}",
    "按条件在两个动作中选择一个。",
    "control",
  ),
  template(
    "builtin.control.for",
    "计数循环",
    "control",
    "c.control-flow",
    "for (int i = 0; i < limit; i++) {\n  action();\n}",
    "从零开始按固定步长重复执行。",
    "control",
  ),
  template(
    "builtin.control.while",
    "条件循环",
    "control",
    "c.control-flow",
    "while (condition) {\n  action();\n}",
    "只要条件非零就继续执行动作。",
    "control",
  ),
  template(
    "builtin.functions.call",
    "调用函数",
    "function-call",
    "c.functions-arrays",
    "result = function(argument);",
    "调用一个已有函数并保存返回值。",
    "statement",
  ),
  template(
    "builtin.functions.call-void",
    "调用过程",
    "function-call",
    "c.functions-arrays",
    "function(argument);",
    "调用一个已有函数，不接收返回值。",
    "statement",
  ),
  template(
    "builtin.arrays.declare",
    "声明数组",
    "array",
    "c.functions-arrays",
    "int values[10] = {0};",
    "声明并清零一个固定长度整数数组。",
    "statement",
  ),
  template(
    "builtin.search.match",
    "记录搜索命中",
    "search",
    "algorithms.search",
    "if (values[i] == target) {\n  found = i;\n  break;\n}",
    "发现目标后记录位置并停止当前循环。",
    "control",
  ),
  template(
    "builtin.sort.swap-adjacent",
    "交换相邻逆序项",
    "sort",
    "algorithms.sort",
    "if (values[j] > values[j + 1]) {\n  int temp = values[j];\n  values[j] = values[j + 1];\n  values[j + 1] = temp;\n}",
    "比较并交换一对逆序的相邻元素。",
    "control",
  ),
  template(
    "builtin.recursion.reduce",
    "递归缩小问题",
    "recursion",
    "algorithms.recursion",
    "return n <= 1 ? 1 : n * factorial(n - 1);",
    "用基础情形结束递归，并在递归调用中缩小规模。",
    "statement",
  ),
  template(
    "builtin.linear.advance-node",
    "移动到下一节点",
    "linear-structure",
    "data-structures.linear",
    "node = node->next;",
    "沿链式结构移动到下一个节点。",
    "statement",
  ),
  template(
    "builtin.trees.visit-left",
    "访问左子树",
    "tree",
    "data-structures.trees",
    "visit(root->left);",
    "对当前节点的左子树执行递归访问。",
    "statement",
  ),
  template(
    "builtin.analysis.assert",
    "检查不变量",
    "correctness",
    "analysis.correctness-complexity",
    "assert(condition);",
    "在执行过程中检查预期不变量。",
    "statement",
  ),
  template(
    "builtin.analysis.count-operation",
    "记录基础操作",
    "complexity",
    "analysis.correctness-complexity",
    "operations++;",
    "记录一次选定的基础操作，用于经验复杂度分析。",
    "statement",
  ),
]);

function stage(
  id: string,
  label: string,
  order: number,
  prerequisites: readonly string[],
  description: string,
): LearningStageDefinition {
  return Object.freeze({
    id,
    version: "1.0.0",
    label,
    order,
    prerequisites: Object.freeze([...prerequisites]),
    description,
  });
}

function template(
  id: string,
  label: string,
  category: string,
  stage: string,
  source: string,
  description: string,
  fragmentKind: LearningTemplateDefinition["fragmentKind"],
): LearningTemplateDefinition {
  return Object.freeze({
    id,
    version: "1.0.0",
    label,
    category,
    stage,
    source,
    description,
    fragmentKind,
  });
}
