import { foaText } from "./foa-contracts.js";
import { defineFoaSceneProfile, type FoaSceneProfile } from "./foa-scene-profile.js";

/** Explicit scene contracts for the first twenty direct-manipulation lessons. */
export const FOA_SCENE_PROFILES_001_020: Readonly<Record<number, FoaSceneProfile>> = Object.freeze({
  1: defineFoaSceneProfile({
    order: 1,
    kind: "execution",
    connection: "forward",
    slots: ["entry", "call", "output", "return"],
    evidence: ["output"],
    caseMode: "none",
    special: true,
    rationale: foaText(
      "用执行游标和 stdout 纸带区分调用、输出与退出。",
      "Use an execution cursor and stdout tape to separate the call, output, and exit.",
    ),
  }),
  2: defineFoaSceneProfile({
    order: 2,
    kind: "execution",
    connection: "forward",
    slots: ["input", "state", "operation", "output"],
    evidence: ["input", "state", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "保持同一数值身份，展示输入、绑定、平方与输出。",
      "Preserve one value identity through input, binding, squaring, and output.",
    ),
  }),
  3: defineFoaSceneProfile({
    order: 3,
    kind: "execution",
    connection: "evidence",
    slots: ["input", "gate", "operation", "return"],
    evidence: ["test", "output"],
    caseMode: "none",
    special: true,
    rationale: foaText(
      "用编译与运行双闸门明确失败时后续阶段不可用。",
      "Use compile and run gates to show that later stages stay locked after failure.",
    ),
  }),
  4: defineFoaSceneProfile({
    order: 4,
    kind: "state",
    connection: "forward",
    slots: ["state", "operation", "operation", "output"],
    evidence: ["state", "output"],
    caseMode: "none",
    special: true,
    rationale: foaText(
      "total 专属写回履历逐项分开旧值、右侧结果与新值。",
      "A total-specific write-back history separates the old value, RHS result, and new value.",
    ),
  }),
  5: defineFoaSceneProfile({
    order: 5,
    kind: "branch",
    connection: "branch",
    slots: ["input", "decision", "decision", "output"],
    evidence: ["input", "condition", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "让用户输入的同一个值依次经过正数与负数判断，并显示唯一实际路径。",
      "Move the learner's single input value through the positive and negative predicates and show only its actual path.",
    ),
  }),
  6: defineFoaSceneProfile({
    order: 6,
    kind: "state",
    connection: "forward",
    slots: ["state", "state", "operation", "output"],
    evidence: ["state", "output"],
    caseMode: "none",
    special: true,
    rationale: foaText(
      "item_count 与 item_price 各自保留名字、类型和值的绑定，再汇入乘积。",
      "item_count and item_price retain separate name-type-value bindings before joining in the product.",
    ),
  }),
  7: defineFoaSceneProfile({
    order: 7,
    kind: "state",
    connection: "compare",
    slots: ["state", "operation", "decision", "output"],
    evidence: ["state", "condition", "output"],
    caseMode: "none",
    special: true,
    rationale: foaText(
      "让写入插头真实区分可变目标与被锁定的常量。",
      "Use a write plug that distinguishes a mutable target from a locked constant.",
    ),
  }),
  8: defineFoaSceneProfile({
    order: 8,
    kind: "expression",
    connection: "compare",
    slots: ["state", "operation", "operation", "output"],
    evidence: ["state", "output"],
    caseMode: "none",
    special: true,
    rationale: foaText(
      "用两棵表达式树直接呈现括号改变的求值顺序。",
      "Use two expression trees to expose how parentheses change evaluation order.",
    ),
  }),
  9: defineFoaSceneProfile({
    order: 9,
    kind: "stream",
    connection: "branch",
    slots: ["input", "gate", "decision", "output"],
    evidence: ["input", "condition", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "扫描器需同时显示赋值结果与返回计数，并保留失败路径。",
      "The scanner must expose both assignment and return count while retaining the failure path.",
    ),
  }),
  10: defineFoaSceneProfile({
    order: 10,
    kind: "evidence",
    connection: "evidence",
    slots: ["state", "operation", "operation", "output"],
    evidence: ["state", "output"],
    caseMode: "none",
    special: true,
    rationale: foaText(
      "用精度尺分开内部浮点值与格式化后的字符串。",
      "Use a precision ruler to separate the internal value from the formatted string.",
    ),
  }),
  11: defineFoaSceneProfile({
    order: 11,
    kind: "state",
    connection: "forward",
    slots: ["state", "operation", "operation", "output"],
    evidence: ["state", "output"],
    caseMode: "none",
    special: true,
    rationale: foaText(
      "score 写回舞台明确展示 +5 与 ×2 两次右侧求值及其先后顺序。",
      "The score write-back stage exposes the +5 and ×2 RHS evaluations and their order.",
    ),
  }),
  12: defineFoaSceneProfile({
    order: 12,
    kind: "expression",
    connection: "compare",
    slots: ["input", "operation", "operation", "output"],
    evidence: ["input", "state", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "用公式槽位把数学项逐一映射到 C 子表达式。",
      "Use formula slots to map each mathematical term to its C subexpression.",
    ),
  }),
  13: defineFoaSceneProfile({
    order: 13,
    kind: "expression",
    connection: "compare",
    slots: ["gate", "operation", "operation", "output"],
    evidence: ["input", "state", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "用可操作分组同时解释整数商、余数与除零约束。",
      "Use manipulable groups to explain quotient, remainder, and the nonzero-divisor constraint.",
    ),
  }),
  14: defineFoaSceneProfile({
    order: 14,
    kind: "branch",
    connection: "compare",
    slots: ["input", "decision", "state", "output"],
    evidence: ["input", "condition", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "双操作数比较尺同步展示关系方向、0/1 真值与文本输出。",
      "A two-operand comparison ruler synchronises relation direction, the 0/1 truth value, and text output.",
    ),
  }),
  15: defineFoaSceneProfile({
    order: 15,
    kind: "branch",
    connection: "branch",
    slots: ["decision", "decision", "merge", "output"],
    evidence: ["input", "condition", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "串联条件门必须显式保留短路后未求值的子句。",
      "Serial condition gates must explicitly preserve clauses skipped by short-circuiting.",
    ),
  }),
  16: defineFoaSceneProfile({
    order: 16,
    kind: "branch",
    connection: "branch",
    slots: ["decision", "true-path", "operation", "output"],
    evidence: ["input", "condition", "state", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "交互输入决定是否经过改写分支，并保持同一 value 身份。",
      "Interactive input decides whether the rewrite branch runs while preserving value identity.",
    ),
  }),
  17: defineFoaSceneProfile({
    order: 17,
    kind: "branch",
    connection: "branch",
    slots: ["decision", "true-path", "merge", "output"],
    evidence: ["input", "condition", "state", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "两条互斥值轨需要在 maximum 槽中显式汇合。",
      "Two mutually exclusive value lanes must merge explicitly into maximum.",
    ),
  }),
  18: defineFoaSceneProfile({
    order: 18,
    kind: "branch",
    connection: "branch",
    slots: ["decision", "decision", "merge", "output"],
    evidence: ["input", "condition", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "有序守卫阶梯要显示首个命中与未访问的更低门槛。",
      "The ordered-guard staircase must show the first match and lower thresholds not visited.",
    ),
  }),
  19: defineFoaSceneProfile({
    order: 19,
    kind: "plot",
    connection: "branch",
    slots: ["gate", "decision", "operation", "output"],
    evidence: ["input", "condition", "state", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "分段图应把阈值位置、适用线段与代入结果连成一体。",
      "A piecewise plot should connect the threshold, selected segment, and substituted result.",
    ),
  }),
  20: defineFoaSceneProfile({
    order: 20,
    kind: "branch",
    connection: "branch",
    slots: ["input", "decision", "operation", "merge"],
    evidence: ["input", "condition", "state", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "月份转盘需展示 case 命中、标签合并与 break 退出。",
      "A month dial must expose case matching, grouped labels, and the break exit.",
    ),
  }),
});
