import { bp, type FoaLessonBlueprint } from "./foa-catalog-builder.js";

const C1: readonly FoaLessonBlueprint[] = [
  bp(
    "1.3",
    "第一个可观察程序",
    "A first observable program",
    "语句顺序与标准输出",
    "statement order and standard output",
    `puts("Hello, algorithm!");`,
    "",
    "Hello, algorithm!\n",
    "O(1)",
    "O(1)",
    ["c.translation-unit", "c.statement", "std.formatted-io"],
  ),
  bp(
    "1.3",
    "输入、变换、输出",
    "Input, transform, output",
    "最小程序数据流",
    "the minimal program data flow",
    `int value;\nif (scanf("%d", &value) != 1) return 1;\nprintf("%d\\n", value * value);`,
    "7\n",
    "49\n",
    "O(1)",
    "O(1)",
    ["c.types", "std.formatted-io"],
  ),
  bp(
    "1.4",
    "编译与运行边界",
    "Compile and run boundary",
    "编译成功后才进入运行阶段",
    "execution beginning only after a successful compile",
    `int compiled = 1;\nprintf("%s\\n", compiled ? "run" : "stop");`,
    "",
    "run\n",
    "O(1)",
    "O(1)",
    ["execution.toolchain", "recovery.compile-failure"],
  ),
  bp(
    "1.4",
    "逐步构造状态",
    "Build state step by step",
    "赋值语句形成可追踪状态",
    "assignments forming traceable state",
    `int total = 0;\ntotal += 2;\ntotal *= 3;\nprintf("%d\\n", total);`,
    "",
    "6\n",
    "O(1)",
    "O(1)",
    ["c.statement", "execution.trace"],
  ),
  bp(
    "1.5",
    "用边界案例反驳猜测",
    "Refute a guess with a boundary case",
    "零值与负值的显式处理",
    "explicit handling of zero and negative values",
    `int value;\nif (scanf("%d", &value) != 1) return 1;\nprintf("%s\\n", value > 0 ? "positive" : value < 0 ? "negative" : "zero");`,
    "0\n",
    "zero\n",
    "O(1)",
    "O(1)",
    ["examples.test-matrix", "algorithms.correctness"],
  ),
];

const C2: readonly FoaLessonBlueprint[] = [
  bp(
    "2.1",
    "有意义的标识符",
    "Meaningful identifiers",
    "名字、类型与值的绑定",
    "binding names, types, and values",
    `int item_count = 3;\nint item_price = 4;\nprintf("%d\\n", item_count * item_price);`,
    "",
    "12\n",
    "O(1)",
    "O(1)",
    ["c.declarations-scope", "c.types"],
  ),
  bp(
    "2.2",
    "常量与可变状态",
    "Constants and mutable state",
    "常量约束与变量更新",
    "constant constraints and variable updates",
    `const int limit = 10;\nint used = 6;\nused += 2;\nprintf("%d/%d\\n", used, limit);`,
    "",
    "8/10\n",
    "O(1)",
    "O(1)",
    ["c.types", "c.declarations-scope"],
  ),
  bp(
    "2.3",
    "表达式分组",
    "Expression grouping",
    "优先级与括号表达意图",
    "precedence and parentheses expressing intent",
    `int a = 2, b = 3, c = 4;\nprintf("%d %d\\n", a + b * c, (a + b) * c);`,
    "",
    "14 20\n",
    "O(1)",
    "O(1)",
    ["c.operators"],
  ),
  bp(
    "2.4",
    "检查数字输入",
    "Validate numeric input",
    "scanf 返回值决定输入是否成立",
    "the scanf return value deciding whether input exists",
    `int value;\nif (scanf("%d", &value) != 1) { puts("invalid"); return 0; }\nprintf("%d\\n", value + 1);`,
    "41\n",
    "42\n",
    "O(1)",
    "O(1)",
    ["std.formatted-io", "tutorial.input-cases"],
  ),
  bp(
    "2.5",
    "控制数字输出",
    "Control numeric output",
    "格式说明符与可观察精度",
    "format specifiers and observable precision",
    `double value = 2.0 / 3.0;\nprintf("%.3f\\n", value);`,
    "",
    "0.667\n",
    "O(1)",
    "O(1)",
    ["std.formatted-io", "c.types"],
  ),
  bp(
    "2.6",
    "赋值与累加",
    "Assignment and accumulation",
    "右侧先求值再写回左侧",
    "evaluating the right side before writing the left side",
    `int score = 10;\nscore = score + 5;\nscore *= 2;\nprintf("%d\\n", score);`,
    "",
    "30\n",
    "O(1)",
    "O(1)",
    ["c.operators", "c.statement"],
  ),
  bp(
    "2.7",
    "球体体积",
    "Volume of a sphere",
    "公式到浮点表达式的翻译",
    "translating a formula into a floating-point expression",
    `double radius;\nif (scanf("%lf", &radius) != 1 || radius < 0.0) return 1;\nconst double pi = 3.141592653589793;\ndouble volume = 4.0 / 3.0 * pi * radius * radius * radius;\nprintf("%.2f\\n", volume);`,
    "2\n",
    "33.51\n",
    "O(1)",
    "O(1)",
    ["c.operators", "std.formatted-io", "algorithms.numeric-stability"],
  ),
  bp(
    "2.3",
    "商与余数",
    "Quotient and remainder",
    "整数除法与取模",
    "integer division and remainder",
    `int numerator, denominator;\nif (scanf("%d%d", &numerator, &denominator) != 2 || denominator == 0) return 1;\nprintf("%d %d\\n", numerator / denominator, numerator % denominator);`,
    "7 3\n",
    "2 1\n",
    "O(1)",
    "O(1)",
    ["c.operators", "c.undefined-behavior"],
  ),
];

const C3: readonly FoaLessonBlueprint[] = [
  bp(
    "3.1",
    "比较产生真假",
    "Comparisons produce truth values",
    "关系表达式",
    "relational expressions",
    `int left, right;\nif (scanf("%d%d", &left, &right) != 2) return 1;\nprintf("%s\\n", left < right ? "true" : "false");`,
    "3 8\n",
    "true\n",
    "O(1)",
    "O(1)",
    ["c.operators", "c.control-flow"],
  ),
  bp(
    "3.1",
    "组合范围条件",
    "Compose a range condition",
    "短路逻辑与闭区间",
    "short-circuit logic and a closed interval",
    `int value;\nif (scanf("%d", &value) != 1) return 1;\nprintf("%s\\n", value >= 1 && value <= 10 ? "inside" : "outside");`,
    "10\n",
    "inside\n",
    "O(1)",
    "O(1)",
    ["c.operators", "c.control-flow"],
  ),
  bp(
    "3.2",
    "单分支绝对值",
    "One-branch absolute value",
    "只在条件成立时改写状态",
    "mutating state only when a condition holds",
    `int value;\nif (scanf("%d", &value) != 1) return 1;\nif (value < 0) value = -value;\nprintf("%d\\n", value);`,
    "-7\n",
    "7\n",
    "O(1)",
    "O(1)",
    ["c.control-flow", "canvas.branching"],
  ),
  bp(
    "3.2",
    "二选一求较大值",
    "Choose the larger value",
    "if-else 的互斥路径",
    "mutually exclusive if-else paths",
    `int a, b;\nif (scanf("%d%d", &a, &b) != 2) return 1;\nint maximum = a > b ? a : b;\nprintf("%d\\n", maximum);`,
    "-4 -2\n",
    "-2\n",
    "O(1)",
    "O(1)",
    ["c.control-flow", "examples.branch-scenario"],
  ),
  bp(
    "3.2",
    "级联成绩分类",
    "Classify a grade with an else-if chain",
    "有序守卫的优先级",
    "priority in ordered guards",
    `int score;\nif (scanf("%d", &score) != 1) return 1;\nchar grade = score >= 80 ? 'A' : score >= 70 ? 'B' : score >= 60 ? 'C' : 'F';\nprintf("%c\\n", grade);`,
    "74\n",
    "B\n",
    "O(1)",
    "O(1)",
    ["c.control-flow", "examples.test-matrix"],
  ),
  bp(
    "3.4",
    "分段税额",
    "Piecewise tax calculation",
    "分段公式与阈值边界",
    "piecewise formulas and threshold boundaries",
    `double income;\nif (scanf("%lf", &income) != 1 || income < 0.0) return 1;\ndouble tax = income > 45000.0 ? (income - 45000.0) * 0.30 : 0.0;\nprintf("%.2f\\n", tax);`,
    "60000\n",
    "4500.00\n",
    "O(1)",
    "O(1)",
    ["c.control-flow", "algorithms.correctness"],
  ),
  bp(
    "3.5",
    "月份天数选择",
    "Select days in a month",
    "switch 标签与 break",
    "switch labels and break",
    `int month;\nif (scanf("%d", &month) != 1) return 1;\nint days;\nswitch (month) { case 2: days = 28; break; case 4: case 6: case 9: case 11: days = 30; break; default: days = 31; }\nprintf("%d\\n", days);`,
    "2\n",
    "28\n",
    "O(1)",
    "O(1)",
    ["c.control-flow"],
  ),
  bp(
    "3.3",
    "用守卫拒绝非法状态",
    "Reject invalid state with a guard",
    "提前返回与失败路径",
    "early return and failure paths",
    `int count;\nif (scanf("%d", &count) != 1 || count <= 0) { puts("invalid"); return 0; }\nprintf("count=%d\\n", count);`,
    "0\n",
    "invalid\n",
    "O(1)",
    "O(1)",
    ["c.control-flow", "execution.diagnostics"],
  ),
];

const C4: readonly FoaLessonBlueprint[] = [
  bp(
    "4.1",
    "计数循环求和",
    "Counted-loop sum",
    "for 循环的初始化、条件与更新",
    "for-loop initialization, condition, and update",
    `int n;\nif (scanf("%d", &n) != 1 || n < 0) return 1;\nint sum = 0;\nfor (int i = 1; i <= n; i++) sum += i;\nprintf("%d\\n", sum);`,
    "5\n",
    "15\n",
    "O(n)",
    "O(1)",
    ["c.loops", "algorithms.big-o"],
  ),
  bp(
    "4.1",
    "阶乘累乘",
    "Factorial by accumulation",
    "循环不变量与乘法累积",
    "a loop invariant and multiplicative accumulation",
    `int n;\nif (scanf("%d", &n) != 1 || n < 0 || n > 12) return 1;\nint result = 1;\nfor (int i = 2; i <= n; i++) result *= i;\nprintf("%d\\n", result);`,
    "5\n",
    "120\n",
    "O(n)",
    "O(1)",
    ["c.loops", "algorithms.correctness"],
  ),
  bp(
    "4.2",
    "逐期复利",
    "Compound interest by periods",
    "重复状态转移",
    "repeated state transitions",
    `int cents = 1000;\nfor (int year = 0; year < 3; year++) cents = cents * 105 / 100;\nprintf("%d\\n", cents);`,
    "",
    "1157\n",
    "O(n)",
    "O(1)",
    ["c.loops", "algorithms.numeric-stability"],
  ),
  bp(
    "4.4",
    "哨兵值输入",
    "Sentinel-controlled input",
    "由数据值终止的 while 循环",
    "a while loop terminated by a data value",
    `int value, sum = 0;\nwhile (scanf("%d", &value) == 1 && value != -1) sum += value;\nprintf("%d\\n", sum);`,
    "3 4 -1\n",
    "7\n",
    "O(n)",
    "O(1)",
    ["c.loops", "tutorial.input-cases"],
  ),
  bp(
    "4.4",
    "至少执行一次",
    "Execute at least once",
    "do-while 的后置检查",
    "the post-test in do-while",
    `int value;\nif (scanf("%d", &value) != 1) return 1;\nint digits = 0;\ndo { digits++; value /= 10; } while (value != 0);\nprintf("%d\\n", digits);`,
    "1203\n",
    "4\n",
    "O(log n)",
    "O(1)",
    ["c.loops"],
  ),
  bp(
    "4.5",
    "按数量读取并求均值",
    "Read a counted sequence and average it",
    "输入规模驱动循环次数",
    "input size driving iteration count",
    `int count;\nif (scanf("%d", &count) != 1 || count <= 0) return 1;\nint sum = 0;\nfor (int i = 0, value; i < count; i++) { if (scanf("%d", &value) != 1) return 1; sum += value; }\nprintf("%.2f\\n", (double)sum / count);`,
    "4 2 4 6 8\n",
    "5.00\n",
    "O(n)",
    "O(1)",
    ["c.loops", "std.formatted-io"],
  ),
  bp(
    "4.5",
    "扫描全负数最大值",
    "Scan a maximum from all-negative data",
    "用首个输入初始化扫描状态",
    "initializing scan state from the first input",
    `int count, maximum;\nif (scanf("%d%d", &count, &maximum) != 2 || count <= 0) return 1;\nfor (int i = 1, value; i < count; i++) { if (scanf("%d", &value) != 1) return 1; if (value > maximum) maximum = value; }\nprintf("%d\\n", maximum);`,
    "5 -4 -9 -2 -7 -3\n",
    "-2\n",
    "O(n)",
    "O(1)",
    ["c.loops", "tutorial.maximum-stream"],
  ),
  bp(
    "4.1",
    "嵌套循环画三角",
    "Draw a triangle with nested loops",
    "外层控制行、内层控制列",
    "the outer loop controlling rows and the inner loop columns",
    `int rows;\nif (scanf("%d", &rows) != 1 || rows < 0) return 1;\nfor (int row = 1; row <= rows; row++) { for (int col = 0; col < row; col++) putchar('*'); putchar('\\n'); }`,
    "4\n",
    "*\n**\n***\n****\n",
    "O(n^2)",
    "O(1)",
    ["c.loops", "algorithms.big-o"],
  ),
  bp(
    "4.1",
    "试除判断素数",
    "Primality by trial division",
    "提前终止减少无效比较",
    "early termination avoiding unnecessary comparisons",
    `int n;\nif (scanf("%d", &n) != 1) return 1;\nint prime = n >= 2;\nfor (int divisor = 2; prime && divisor <= n / divisor; divisor++) if (n % divisor == 0) prime = 0;\nputs(prime ? "prime" : "composite");`,
    "29\n",
    "prime\n",
    "O(sqrt(n))",
    "O(1)",
    ["c.loops", "algorithms.correctness"],
  ),
  bp(
    "4.4",
    "欧几里得算法的进度量",
    "A progress measure for Euclid's algorithm",
    "余数严格缩小保证终止",
    "strictly decreasing remainders ensuring termination",
    `int a, b;\nif (scanf("%d%d", &a, &b) != 2 || a <= 0 || b <= 0) return 1;\nwhile (b != 0) { int remainder = a % b; a = b; b = remainder; }\nprintf("%d\\n", a);`,
    "48 18\n",
    "6\n",
    "O(log n)",
    "O(1)",
    ["c.loops", "algorithms.correctness"],
  ),
];

const C5: readonly FoaLessonBlueprint[] = [
  bp(
    "5.1",
    "把平方封装为函数",
    "Encapsulate squaring in a function",
    "函数抽象",
    "function abstraction",
    `static int square(int x) { return x * x; }\n@@main@@\nint value;\nif (scanf("%d", &value) != 1) return 1;\nprintf("%d\\n", square(value));`,
    "6\n",
    "36\n",
    "O(1)",
    "O(1)",
    ["c.functions"],
  ),
  bp(
    "5.2",
    "原型先于调用",
    "Declare a prototype before a call",
    "函数声明与定义的一致性",
    "consistency between function declarations and definitions",
    `static int add(int left, int right);\nstatic int add(int left, int right) { return left + right; }\n@@main@@\nprintf("%d\\n", add(7, 5));`,
    "",
    "12\n",
    "O(1)",
    "O(1)",
    ["c.functions", "c.translation-unit"],
  ),
  bp(
    "5.3",
    "复用标准库函数",
    "Reuse a standard-library function",
    "库函数契约",
    "a library function contract",
    `int value;\nif (scanf("%d", &value) != 1) return 1;\nprintf("%d\\n", abs(value));`,
    "-9\n",
    "9\n",
    "O(1)",
    "O(1)",
    ["c.functions", "std.stdlib"],
  ),
  bp(
    "5.4",
    "泛化区间截断",
    "Generalise clamping",
    "参数化抽象",
    "parameterised abstraction",
    `static int clamp(int value, int low, int high) { if (value < low) return low; if (value > high) return high; return value; }\n@@main@@\nprintf("%d\\n", clamp(14, 0, 10));`,
    "",
    "10\n",
    "O(1)",
    "O(1)",
    ["c.functions", "c.control-flow"],
  ),
  bp(
    "5.5",
    "递归阶乘与基例",
    "Recursive factorial and its base case",
    "递归调用逼近基例",
    "recursive calls approaching a base case",
    `static int factorial(int n) { return n <= 1 ? 1 : n * factorial(n - 1); }\n@@main@@\nprintf("%d\\n", factorial(5));`,
    "",
    "120\n",
    "O(n)",
    "O(n)",
    ["c.recursion", "c.functions"],
  ),
  bp(
    "5.6",
    "牛顿法求立方根",
    "Cube root with Newton iteration",
    "数值近似的收敛迭代",
    "convergent numerical approximation",
    `static double cube_root(double value) { double guess = value > 1.0 ? value : 1.0; for (int i = 0; i < 20; i++) guess = (2.0 * guess + value / (guess * guess)) / 3.0; return guess; }\n@@main@@\nprintf("%.3f\\n", cube_root(27.0));`,
    "",
    "3.000\n",
    "O(k)",
    "O(1)",
    ["c.functions", "algorithms.numeric-stability"],
  ),
  bp(
    "5.7",
    "用表驱动测试函数",
    "Test a function with a table",
    "多个输入共同约束函数行为",
    "multiple inputs constraining function behaviour",
    `static int minimum(int a, int b) { return a < b ? a : b; }\n@@main@@\nint tests[][3] = {{3, 4, 3}, {-2, -7, -7}, {5, 5, 5}};\nint passed = 0;\nfor (size_t i = 0; i < 3; i++) passed += minimum(tests[i][0], tests[i][1]) == tests[i][2];\nprintf("%d/3\\n", passed);`,
    "",
    "3/3\n",
    "O(n)",
    "O(1)",
    ["c.functions", "examples.test-matrix"],
  ),
  bp(
    "5.4",
    "值参数不会改写调用者",
    "Value parameters do not mutate the caller",
    "按值传参",
    "pass-by-value",
    `static void increment_copy(int value) { value++; printf("inside=%d\\n", value); }\n@@main@@\nint value = 5;\nincrement_copy(value);\nprintf("outside=%d\\n", value);`,
    "",
    "inside=6\noutside=5\n",
    "O(1)",
    "O(1)",
    ["c.functions", "c.declarations-scope"],
  ),
  bp(
    "5.4",
    "返回计算结果",
    "Return a computed result",
    "return 把值交还调用点",
    "return passing a value back to the call site",
    `static int distance_from_zero(int value) { return value < 0 ? -value : value; }\n@@main@@\nint distance = distance_from_zero(-12);\nprintf("%d\\n", distance);`,
    "",
    "12\n",
    "O(1)",
    "O(1)",
    ["c.functions"],
  ),
  bp(
    "5.4",
    "组合小函数",
    "Compose small functions",
    "调用图中的数据传递",
    "data transfer through a call graph",
    `static int twice(int x) { return x * 2; }\nstatic int plus_one(int x) { return x + 1; }\n@@main@@\nprintf("%d\\n", plus_one(twice(10)));`,
    "",
    "21\n",
    "O(1)",
    "O(1)",
    ["c.functions", "execution.trace"],
  ),
];

const C6: readonly FoaLessonBlueprint[] = [
  bp(
    "6.1",
    "main 的退出状态",
    "The exit status of main",
    "进程成功与失败的约定",
    "the process success/failure convention",
    `int ok = 1;\nprintf("%s\\n", ok ? "success" : "failure");\nreturn ok ? EXIT_SUCCESS : EXIT_FAILURE;`,
    "",
    "success\n",
    "O(1)",
    "O(1)",
    ["c.functions", "execution.diagnostics"],
  ),
  bp(
    "6.2",
    "void 函数产生副作用",
    "A void function produces a side effect",
    "无返回值函数与输出副作用",
    "a no-result function and its output side effect",
    `static void print_separator(void) { puts("---"); }\n@@main@@\nprint_separator();`,
    "",
    "---\n",
    "O(1)",
    "O(1)",
    ["c.functions", "std.formatted-io"],
  ),
  bp(
    "6.3",
    "块作用域遮蔽",
    "Block-scope shadowing",
    "内层声明与外层名字",
    "an inner declaration and an outer name",
    `int value = 3;\n{ int value = 8; printf("%d ", value); }\nprintf("%d\\n", value);`,
    "",
    "8 3\n",
    "O(1)",
    "O(1)",
    ["c.declarations-scope"],
  ),
  bp(
    "6.4",
    "文件作用域状态",
    "File-scope state",
    "全局对象的共享可见性",
    "shared visibility of a global object",
    `static int counter = 0;\nstatic void count_once(void) { counter++; }\n@@main@@\ncount_once(); count_once();\nprintf("%d\\n", counter);`,
    "",
    "2\n",
    "O(1)",
    "O(1)",
    ["c.declarations-scope", "c.functions"],
  ),
  bp(
    "6.5",
    "静态局部状态",
    "Static local state",
    "跨调用保留的局部对象",
    "a local object retained across calls",
    `static int next_id(void) { static int id = 0; return ++id; }\n@@main@@\nint first = next_id();\nint second = next_id();\nprintf("%d %d\\n", first, second);`,
    "",
    "1 2\n",
    "O(1)",
    "O(1)",
    ["c.declarations-scope", "c.functions"],
  ),
  bp(
    "6.6",
    "取地址与解引用",
    "Address and dereference",
    "指针引用对象位置",
    "a pointer referring to an object's location",
    `int value = 7;\nint *address = &value;\n*address = 9;\nprintf("%d\\n", value);`,
    "",
    "9\n",
    "O(1)",
    "O(1)",
    ["c.pointers"],
  ),
  bp(
    "6.7",
    "指针参数交换",
    "Swap through pointer parameters",
    "可写地址传递副作用",
    "a writable address carrying a side effect",
    `static void swap(int *left, int *right) { int temporary = *left; *left = *right; *right = temporary; }\n@@main@@\nint a = 2, b = 9;\nswap(&a, &b);\nprintf("%d %d\\n", a, b);`,
    "",
    "9 2\n",
    "O(1)",
    "O(1)",
    ["c.pointers", "tutorial.pointer-memory"],
  ),
  bp(
    "6.7",
    "两个输出参数",
    "Two output parameters",
    "函数通过指针返回多个结果",
    "a function returning multiple results through pointers",
    `static void minmax(int a, int b, int *minimum, int *maximum) { *minimum = a < b ? a : b; *maximum = a > b ? a : b; }\n@@main@@\nint low, high;\nminmax(8, 3, &low, &high);\nprintf("%d %d\\n", low, high);`,
    "",
    "3 8\n",
    "O(1)",
    "O(1)",
    ["c.pointers", "c.functions"],
  ),
  bp(
    "6.8",
    "封装安全读取",
    "Encapsulate safe reading",
    "读取函数同时报告成功状态",
    "a reader reporting both value and success",
    `static int read_int(int *out) { return scanf("%d", out) == 1; }\n@@main@@\nint value;\nif (!read_int(&value)) { puts("invalid"); return 0; }\nprintf("%d\\n", value * 2);`,
    "11\n",
    "22\n",
    "O(1)",
    "O(1)",
    ["c.pointers", "std.formatted-io"],
  ),
];

const C7: readonly FoaLessonBlueprint[] = [
  bp(
    "7.1",
    "数组线性求和",
    "Linear sum over an array",
    "索引与连续同类元素",
    "indices over a contiguous homogeneous collection",
    `int values[] = {2, 4, 6, 8};\nint sum = 0;\nfor (size_t i = 0; i < 4; i++) sum += values[i];\nprintf("%d\\n", sum);`,
    "",
    "20\n",
    "O(n)",
    "O(n)",
    ["c.arrays", "data.dynamic-array"],
  ),
  bp(
    "7.2",
    "按容量读取数组",
    "Read an array within capacity",
    "容量与有效长度",
    "capacity and logical length",
    `enum { CAPACITY = 5 };\nint values[CAPACITY], count;\nif (scanf("%d", &count) != 1 || count < 0 || count > CAPACITY) return 1;\nfor (int i = 0; i < count; i++) if (scanf("%d", &values[i]) != 1) return 1;\nprintf("%d\\n", count == 0 ? 0 : values[count - 1]);`,
    "3 9 8 7\n",
    "7\n",
    "O(n)",
    "O(n)",
    ["c.arrays", "tutorial.input-cases"],
  ),
  bp(
    "7.3",
    "数组参数必须配长度",
    "Array parameters need a length",
    "数组参数调整为指针",
    "array parameters adjusting to pointers",
    `static int array_max(const int values[], size_t length) { int maximum = values[0]; for (size_t i = 1; i < length; i++) if (values[i] > maximum) maximum = values[i]; return maximum; }\n@@main@@\nint values[] = {-3, -8, -1, -4};\nprintf("%d\\n", array_max(values, 4));`,
    "",
    "-1\n",
    "O(n)",
    "O(1)",
    ["c.arrays", "c.functions"],
  ),
  bp(
    "7.4",
    "二维数组行和",
    "Row sums in a two-dimensional array",
    "行列索引与存储形状",
    "row/column indices and storage shape",
    `int matrix[2][3] = {{1, 2, 3}, {4, 5, 6}};\nfor (size_t row = 0; row < 2; row++) { int sum = 0; for (size_t col = 0; col < 3; col++) sum += matrix[row][col]; printf("%d%c", sum, row == 1 ? '\\n' : ' '); }`,
    "",
    "6 15\n",
    "O(rows*cols)",
    "O(1)",
    ["c.arrays", "algorithms.big-o"],
  ),
  bp(
    "7.5",
    "指定初始化值",
    "Designated initial values",
    "初始化器建立确定初态",
    "an initializer establishing deterministic initial state",
    `int counts[5] = {[1] = 3, [4] = 2};\nfor (size_t i = 0; i < 5; i++) printf("%d%c", counts[i], i == 4 ? '\\n' : ' ');`,
    "",
    "0 3 0 0 2\n",
    "O(n)",
    "O(n)",
    ["c.arrays", "c.declarations-scope"],
  ),
  bp(
    "7.6",
    "数组名与指针遍历",
    "Array names and pointer traversal",
    "指针算术与元素顺序",
    "pointer arithmetic and element order",
    `int values[] = {3, 1, 4};\nfor (int *cursor = values; cursor != values + 3; cursor++) printf("%d%c", *cursor, cursor == values + 2 ? '\\n' : ' ');`,
    "",
    "3 1 4\n",
    "O(n)",
    "O(1)",
    ["c.arrays", "c.pointers"],
  ),
  bp(
    "7.7",
    "寻找字符串终止符",
    "Find the string terminator",
    "NUL 终止与字符计数",
    "NUL termination and character counting",
    `char word[] = "algorithm";\nsize_t length = 0;\nwhile (word[length] != '\\0') length++;\nprintf("%zu\\n", length);`,
    "",
    "9\n",
    "O(n)",
    "O(1)",
    ["c.strings", "std.string"],
  ),
  bp(
    "7.8",
    "顺序收集不重复单词",
    "Collect distinct words in order",
    "字符串比较与线性去重",
    "string comparison and linear deduplication",
    `const char *input[] = {"red", "blue", "red", "green", "blue"};\nconst char *unique[5]; size_t used = 0;\nfor (size_t i = 0; i < 5; i++) { size_t j = 0; while (j < used && strcmp(input[i], unique[j]) != 0) j++; if (j == used) unique[used++] = input[i]; }\nfor (size_t i = 0; i < used; i++) printf("%s%c", unique[i], i + 1 == used ? '\\n' : ' ');`,
    "",
    "red blue green\n",
    "O(n^2 * m)",
    "O(n)",
    ["c.strings", "algorithms.linear-search", "data.set"],
  ),
  bp(
    "7.9",
    "字符串表查找",
    "Look up a table of strings",
    "字符串数组与索引选择",
    "an array of strings and indexed selection",
    `const char *days[] = {"Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"};\nint index;\nif (scanf("%d", &index) != 1 || index < 0 || index >= 7) return 1;\nputs(days[index]);`,
    "3\n",
    "Wed\n",
    "O(1)",
    "O(1)",
    ["c.strings", "c.arrays"],
  ),
  bp(
    "7.10",
    "插入排序的已排序前缀",
    "Insertion sort's sorted prefix",
    "相邻交换恢复已排序前缀",
    "restoring the sorted prefix through adjacent swaps",
    `int values[] = {5, 2, 4, 6, 1};\nsize_t count = 5;\nfor (size_t i = 1; i < count; i++) { size_t j = i; while (j > 0 && values[j - 1] > values[j]) { int temporary = values[j - 1]; values[j - 1] = values[j]; values[j] = temporary; j--; } }\nfor (size_t i = 0; i < count; i++) printf("%d%c", values[i], i + 1 == count ? '\\n' : ' ');`,
    "",
    "1 2 4 5 6\n",
    "O(n^2)",
    "O(1)",
    ["c.arrays", "algorithms.sorting", "tutorial.insertion-sort-lab"],
  ),
];

export const FOA_FOUNDATION_GROUPS = Object.freeze([
  Object.freeze({ chapter: 1, lessons: C1 }),
  Object.freeze({ chapter: 2, lessons: C2 }),
  Object.freeze({ chapter: 3, lessons: C3 }),
  Object.freeze({ chapter: 4, lessons: C4 }),
  Object.freeze({ chapter: 5, lessons: C5 }),
  Object.freeze({ chapter: 6, lessons: C6 }),
  Object.freeze({ chapter: 7, lessons: C7 }),
]);
