import { foaText } from "./foa-contracts.js";
import type { FoaSceneProfile } from "./foa-scene-profile.js";
import { defineFoaSceneProfile } from "./foa-scene-profile.js";

export const FOA_SCENE_PROFILES_041_060: Readonly<Record<number, FoaSceneProfile>> = Object.freeze({
  41: defineFoaSceneProfile({
    order: 41,
    kind: "call-stack",
    connection: "unwind",
    slots: ["call", "return", "call", "output"],
    evidence: ["state", "output"],
    caseMode: "fixed",
    special: true,
    rationale: foaText(
      "嵌套调用需要显示内层返回值如何进入外层调用。",
      "Nested calls need to show the inner return value entering the outer call.",
    ),
  }),
  42: defineFoaSceneProfile({
    order: 42,
    kind: "execution",
    connection: "evidence",
    slots: ["entry", "output", "return", "evidence"],
    evidence: ["output", "test"],
    caseMode: "fixed",
    special: true,
    rationale: foaText(
      "标准输出与进程退出状态必须作为两个独立证据通道。",
      "Standard output and process exit status must remain separate evidence channels.",
    ),
  }),
  43: defineFoaSceneProfile({
    order: 43,
    kind: "call-stack",
    connection: "unwind",
    slots: ["call", "operation", "output", "return"],
    evidence: ["output"],
    caseMode: "fixed",
    special: true,
    rationale: foaText(
      "void 调用应突出副作用，而不是制造不存在的返回值。",
      "A void call should emphasize its side effect without inventing a return value.",
    ),
  }),
  44: defineFoaSceneProfile({
    order: 44,
    kind: "scope",
    connection: "alias",
    slots: ["scope", "scope", "object", "object"],
    evidence: ["state"],
    caseMode: "fixed",
    special: true,
    rationale: foaText(
      "遮蔽需要稳定的作用域框和从使用点到声明的绑定边。",
      "Shadowing needs stable scope boxes and binding edges from each use to its declaration.",
    ),
  }),
  45: defineFoaSceneProfile({
    order: 45,
    kind: "state",
    connection: "forward",
    slots: ["state", "call", "call", "output"],
    evidence: ["state", "output"],
    caseMode: "fixed",
    special: true,
    rationale: foaText(
      "两次调用必须连接到同一个文件作用域对象。",
      "Both calls must connect to the same file-scope object.",
    ),
  }),
  46: defineFoaSceneProfile({
    order: 46,
    kind: "state",
    connection: "unwind",
    slots: ["call", "state", "frame", "return"],
    evidence: ["state"],
    caseMode: "fixed",
    special: true,
    rationale: foaText(
      "静态对象应跨调用帧保留身份和值。",
      "The static object must preserve its identity and value across call frames.",
    ),
  }),
  47: defineFoaSceneProfile({
    order: 47,
    kind: "pointer",
    connection: "alias",
    slots: ["object", "pointer", "pointer", "state"],
    edges: [
      [0, 1],
      [1, 2],
      [2, 3],
      [1, 0],
      [2, 0],
    ],
    evidence: ["memory", "state"],
    pointerAlias: {
      objectName: "value",
      pointerName: "address",
      initialValue: "7",
      writtenValue: "9",
      revealAfterConfirmedCount: 2,
      writeAfterConfirmedCount: 3,
    },
    caseMode: "fixed",
    special: true,
    rationale: foaText(
      "取地址、解引用与写入必须沿同一条真实别名边。",
      "Addressing, dereferencing, and writing must follow one real alias edge.",
    ),
  }),
  48: defineFoaSceneProfile({
    order: 48,
    kind: "pointer",
    connection: "alias",
    slots: ["state", "pointer", "pointer", "output"],
    evidence: ["memory", "state", "output"],
    caseMode: "fixed",
    special: true,
    rationale: foaText(
      "交换必须保留两个别名目标和 temporary 的赋值顺序。",
      "Swapping must preserve both aliased targets and the assignment order through temporary.",
    ),
  }),
  49: defineFoaSceneProfile({
    order: 49,
    kind: "pointer",
    connection: "alias",
    slots: ["decision", "pointer", "pointer", "output"],
    evidence: ["condition", "memory", "output"],
    caseMode: "fixed",
    special: true,
    rationale: foaText(
      "两个输出参数需要两条独立且命名清楚的写入路径。",
      "Two output parameters need separate, clearly named write paths.",
    ),
  }),
  50: defineFoaSceneProfile({
    order: 50,
    kind: "pointer",
    connection: "branch",
    slots: ["input", "evidence", "pointer", "decision"],
    evidence: ["input", "condition", "state"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "输出指针只有在读取成功分支上才获得有效值。",
      "The output pointer becomes valid only on the successful-read branch.",
    ),
  }),
  51: defineFoaSceneProfile({
    order: 51,
    kind: "array",
    connection: "forward",
    slots: ["cursor", "array", "state", "update"],
    evidence: ["state", "iteration", "output"],
    caseMode: "fixed",
    special: true,
    rationale: foaText(
      "数组求和舞台让单一扫描游标逐格驱动 sum，并记录每格恰好消费一次。",
      "The array-sum stage lets one scan cursor drive sum cell by cell and records that every cell is consumed once.",
    ),
  }),
  52: defineFoaSceneProfile({
    order: 52,
    kind: "array",
    connection: "branch",
    slots: ["input", "gate", "array", "output"],
    evidence: ["input", "condition", "memory", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "容量与逻辑长度必须同时显示，越界路径不能进入数组。",
      "Capacity and logical length must remain visible, and an invalid path must not enter the array.",
    ),
  }),
  53: defineFoaSceneProfile({
    order: 53,
    kind: "pointer",
    connection: "alias",
    slots: ["pointer", "state", "array", "return"],
    evidence: ["memory", "state", "output"],
    caseMode: "fixed",
    special: true,
    rationale: foaText(
      "首元素指针与独立 length 共同限定合法访问区间。",
      "The first-element pointer and a separate length jointly bound the valid access range.",
    ),
  }),
  54: defineFoaSceneProfile({
    order: 54,
    kind: "matrix",
    connection: "grid",
    slots: ["cursor", "body", "output", "update"],
    edges: [
      [0, 1],
      [1, 2],
      [2, 3],
      [3, 0],
    ],
    evidence: ["state", "iteration", "output"],
    matrixCase: {
      values: [
        [1, 2, 3],
        [4, 5, 6],
      ],
      rowSums: [6, 15],
    },
    caseMode: "fixed",
    special: true,
    rationale: foaText(
      "二维遍历需要行列游标和逐行重置的累加状态。",
      "Two-dimensional traversal needs row and column cursors plus a per-row accumulator reset.",
    ),
  }),
  55: defineFoaSceneProfile({
    order: 55,
    kind: "array",
    connection: "grid",
    slots: ["array", "object", "object", "state"],
    evidence: ["memory", "state"],
    caseMode: "fixed",
    special: true,
    rationale: foaText(
      "指定初始化应把命名写入与其余零初始化同时呈现。",
      "Designated initialization should show named writes together with zero-initialized remainder cells.",
    ),
  }),
  56: defineFoaSceneProfile({
    order: 56,
    kind: "pointer",
    connection: "alias",
    slots: ["pointer", "object", "update", "gate"],
    evidence: ["memory", "condition", "iteration"],
    caseMode: "fixed",
    special: true,
    rationale: foaText(
      "指针游标必须保持对数组对象的别名关系，并停在尾后位置。",
      "The pointer cursor must remain aliased to the array object and stop at one-past-the-end.",
    ),
  }),
  57: defineFoaSceneProfile({
    order: 57,
    kind: "array",
    connection: "cycle",
    slots: ["cursor", "condition", "update", "gate"],
    evidence: ["condition", "iteration", "state"],
    caseMode: "fixed",
    special: true,
    rationale: foaText(
      "字符扫描必须把 NUL 显示为停止边界而不是普通字符。",
      "Character scanning must display NUL as the stopping boundary rather than a regular character.",
    ),
  }),
  58: defineFoaSceneProfile({
    order: 58,
    kind: "search",
    connection: "compare",
    slots: ["input", "cursor", "decision", "output"],
    evidence: ["input", "condition", "state", "output"],
    caseMode: "fixed",
    special: true,
    rationale: foaText(
      "去重需要同时显示当前输入、已有序列和命中或追加决策。",
      "Deduplication needs the current input, existing sequence, and match-or-append decision visible together.",
    ),
  }),
  59: defineFoaSceneProfile({
    order: 59,
    kind: "search",
    connection: "branch",
    slots: ["input", "gate", "array", "output"],
    evidence: ["input", "condition", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "表查找必须先验证索引范围，再显示被选中的唯一表项。",
      "Table lookup must validate the index range before exposing the single selected entry.",
    ),
  }),
  60: defineFoaSceneProfile({
    order: 60,
    kind: "sorting",
    connection: "compare",
    slots: ["array", "decision", "update", "merge"],
    evidence: ["state", "condition", "iteration", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "教材插入排序先直接操作相邻比较与交换，再把 key+右移作为优化对照。",
      "Textbook insertion sort starts with adjacent comparisons and swaps, then uses key-and-shift as an optimization contrast.",
    ),
  }),
});
