import { bp, type FoaLessonBlueprint } from "./foa-catalog-builder.js";

const C8: readonly FoaLessonBlueprint[] = [
  bp(
    "8.1",
    "声明一个点结构",
    "Declare a point structure",
    "结构体把相关字段组合成一个值",
    "a structure grouping related fields into one value",
    `struct Point { int x; int y; };\nstruct Point point = {3, 4};\nprintf("%d\\n", point.x + point.y);`,
    "",
    "7\n",
    "O(1)",
    "O(1)",
    ["c.structs"],
  ),
  bp(
    "8.2",
    "结构体整体赋值",
    "Assign a whole structure",
    "结构体值复制",
    "structure value copying",
    `struct Pair { int left; int right; };\nstruct Pair first = {2, 8};\nstruct Pair second = first;\nsecond.left = 5;\nprintf("%d %d\\n", first.left, second.left);`,
    "",
    "2 5\n",
    "O(1)",
    "O(1)",
    ["c.structs", "c.declarations-scope"],
  ),
  bp(
    "8.3",
    "通过指针访问字段",
    "Access fields through a pointer",
    "箭头运算符与可写记录",
    "the arrow operator and a writable record",
    `struct Counter { int value; };
@@main@@
struct Counter counter;
if (scanf("%d", &counter.value) != 1) {
  return 1;
}
struct Counter *link = &counter;
link->value++;
printf("%d\\n", counter.value);`,
    "4\n",
    "5\n",
    "O(1)",
    "O(1)",
    ["c.structs", "c.pointers"],
  ),
  bp(
    "8.3",
    "函数返回结构体",
    "Return a structure from a function",
    "记录值跨函数边界",
    "a record value crossing a function boundary",
    `struct Point { int x; int y; };\nstatic struct Point translated(struct Point p, int dx, int dy) { p.x += dx; p.y += dy; return p; }\n@@main@@\nstruct Point p = translated((struct Point){1, 2}, 3, 4);\nprintf("%d %d\\n", p.x, p.y);`,
    "",
    "4 6\n",
    "O(1)",
    "O(1)",
    ["c.structs", "c.functions"],
  ),
  bp(
    "8.4",
    "结构体数组筛选",
    "Filter an array of records",
    "字段条件与记录集合",
    "field predicates over a record collection",
    `struct Item { const char *name; int score; };\nstruct Item items[] = {{"A", 4}, {"B", 9}, {"C", 7}};\nfor (size_t i = 0; i < 3; i++) if (items[i].score >= 7) printf("%s%c", items[i].name, i == 2 ? '\\n' : ' ');`,
    "",
    "B C\n",
    "O(n)",
    "O(1)",
    ["c.structs", "c.arrays"],
  ),
  bp(
    "8.1",
    "枚举有限状态",
    "Represent finite states with an enum",
    "命名整数状态与 switch",
    "named integer states and switch",
    `enum State { READY, RUNNING, DONE };\nenum State state = RUNNING;\nswitch (state) { case READY: puts("ready"); break; case RUNNING: puts("running"); break; case DONE: puts("done"); break; }`,
    "",
    "running\n",
    "O(1)",
    "O(1)",
    ["c.structs", "c.control-flow"],
  ),
  bp(
    "8.1",
    "带标签的联合体",
    "A tagged union",
    "标签决定联合体的有效成员",
    "a tag determining the active union member",
    `enum Kind { INTEGER, DECIMAL };\nstruct Value { enum Kind kind; union { int integer; double decimal; } as; };\nstruct Value value = {INTEGER, {.integer = 42}};\nif (value.kind == INTEGER) printf("%d\\n", value.as.integer);`,
    "",
    "42\n",
    "O(1)",
    "O(1)",
    ["c.structs", "c.undefined-behavior"],
  ),
  bp(
    "8.4",
    "typedef 与记录查找",
    "Typedef and record lookup",
    "别名简化记录集合接口",
    "a type alias simplifying a record collection interface",
    `typedef struct { int id; const char *name; } Student;\nStudent students[] = {{7, "Ada"}, {9, "Lin"}};\nint wanted = 9;\nfor (size_t i = 0; i < 2; i++) if (students[i].id == wanted) puts(students[i].name);`,
    "",
    "Lin\n",
    "O(n)",
    "O(1)",
    ["c.structs", "algorithms.linear-search"],
  ),
];

const C9: readonly FoaLessonBlueprint[] = [
  bp(
    "9.1",
    "枚举候选求两数和",
    "Generate candidates for two-sum",
    "生成并检验候选对",
    "generating and testing candidate pairs",
    `int values[] = {2, 7, 11, 15}; int target = 9;\nfor (size_t i = 0; i < 4; i++) for (size_t j = i + 1; j < 4; j++) if (values[i] + values[j] == target) printf("%zu %zu\\n", i, j);`,
    "",
    "0 1\n",
    "O(n^2)",
    "O(1)",
    ["algorithms.backtracking", "c.loops"],
  ),
  bp(
    "9.2",
    "折半定位有序值",
    "Locate a sorted value by halving",
    "分治缩小搜索区间",
    "divide and conquer shrinking a search interval",
    `int count;
int values[12];
int target;
if (scanf("%d", &count) != 1 || count < 2 || count > 12) {
  return 1;
}
for (int i = 0; i < count; i++) {
  if (scanf("%d", &values[i]) != 1) {
    return 1;
  }
  if (i > 0 && values[i] < values[i - 1]) {
    return 1;
  }
}
if (scanf("%d", &target) != 1) {
  return 1;
}
size_t low = 0;
size_t high = (size_t)count;
/* Course relation retained for the semantic catalog: low = mid + 1; else high = mid; */
while (low < high) {
  size_t mid = low + (high - low) / 2;
  if (values[mid] < target) {
    low = mid + 1; /* trace-anchor: low */
  }
  else {
    high = mid; /* trace-anchor: high */
  }
}
printf("%zu\\n", low);`,
    "5\n1 3 5 7 9\n7\n",
    "3\n",
    "O(log n)",
    "O(1)",
    ["algorithms.binary-search", "algorithms.divide-conquer"],
  ),
  bp(
    "9.3",
    "模拟队列变化",
    "Simulate a queue",
    "按事件顺序更新模型状态",
    "updating model state in event order",
    `int queue[4], head = 0, tail = 0;\nqueue[tail++] = 3; queue[tail++] = 5;\nprintf("%d ", queue[head++]); queue[tail++] = 8;\nprintf("%d %d\\n", queue[head++], queue[head++]);`,
    "",
    "3 5 8\n",
    "O(n)",
    "O(n)",
    ["data.queue", "c.arrays"],
  ),
  bp(
    "9.4",
    "二分逼近平方根",
    "Approximate a square root by bisection",
    "误差区间逐轮减半",
    "halving an error interval each round",
    `double value = 2.0, low = 0.0, high = 2.0;\nfor (int step = 0; step < 40; step++) { double mid = (low + high) / 2.0; if (mid * mid < value) low = mid; else high = mid; }\nprintf("%.5f\\n", (low + high) / 2.0);`,
    "",
    "1.41421\n",
    "O(log(1/epsilon))",
    "O(1)",
    ["algorithms.numeric-stability", "algorithms.divide-conquer"],
  ),
  bp(
    "9.5",
    "离散时间运动",
    "Discrete-time motion",
    "物理状态的逐步积分",
    "stepwise integration of physical state",
    `double position = 0.0, velocity = 10.0, dt = 0.5;\nfor (int step = 0; step < 4; step++) { position += velocity * dt; velocity -= 9.8 * dt; }\nprintf("%.2f\\n", position);`,
    "",
    "5.30\n",
    "O(n)",
    "O(1)",
    ["c.loops", "algorithms.numeric-stability"],
  ),
  bp(
    "9.6",
    "爬山法改进候选",
    "Improve a candidate with hill climbing",
    "局部评价驱动演化",
    "local evaluation driving evolution",
    `int x = -10;\nfor (;;) { int current = -(x - 3) * (x - 3); int next = -(x + 1 - 3) * (x + 1 - 3); if (next <= current) break; x++; }\nprintf("%d\\n", x);`,
    "",
    "3\n",
    "O(distance)",
    "O(1)",
    ["algorithms.greedy", "algorithms.correctness"],
  ),
  bp(
    "9.2",
    "递归返回值与调用栈",
    "Recursive return values and the call stack",
    "单一递归调用逐层回卷，在线性调用深度中生成指数增长的结果",
    "one recursive call unwinding through linear call depth to produce an exponentially growing result",
    `static int moves(int disks) {
  if (disks == 0) {
    return 0;
  }
  int result = 2 * moves(disks - 1) + 1;
  return result;
}
@@main@@
int disks;
if (scanf("%d", &disks) != 1 || disks < 0 || disks > 12) {
  return 1;
}
int result = moves(disks);
printf("%d\\n", result);`,
    "4\n",
    "15\n",
    "O(n)",
    "O(n)",
    ["c.recursion", "algorithms.divide-conquer"],
  ),
  bp(
    "9.1",
    "子集和回溯",
    "Subset sum by backtracking",
    "选择或跳过形成搜索树",
    "choose-or-skip forming a search tree",
    `static int subset_sum(const int *v, int n, int target) { if (target == 0) return 1; if (n == 0) return 0; return subset_sum(v + 1, n - 1, target) || subset_sum(v + 1, n - 1, target - v[0]); }\n@@main@@\nint values[] = {3, 5, 9};\nputs(subset_sum(values, 3, 8) ? "yes" : "no");`,
    "",
    "yes\n",
    "O(2^n)",
    "O(n)",
    ["algorithms.backtracking", "c.recursion"],
  ),
  bp(
    "9.4",
    "固定种子的蒙特卡洛估计",
    "A deterministic Monte Carlo estimate",
    "随机实验与可复现实验种子",
    "random experiments and a reproducible seed",
    `uint32_t state = 7; int inside = 0, samples = 10000;\nfor (int i = 0; i < samples; i++) { state = state * 1664525u + 1013904223u; double x = (state & 0xffffu) / 65535.0; state = state * 1664525u + 1013904223u; double y = (state & 0xffffu) / 65535.0; inside += x * x + y * y <= 1.0; }\nprintf("%.3f\\n", 4.0 * inside / samples);`,
    "",
    "3.152\n",
    "O(n)",
    "O(1)",
    ["algorithms.numeric-stability", "execution.benchmark"],
  ),
  bp(
    "9.4",
    "牛顿法求方程根",
    "Newton iteration for a root",
    "用导数修正近似值",
    "using a derivative to correct an approximation",
    `double x = 1.0;\nfor (int i = 0; i < 8; i++) x -= (x * x - 2.0) / (2.0 * x);\nprintf("%.6f\\n", x);`,
    "",
    "1.414214\n",
    "O(k)",
    "O(1)",
    ["algorithms.numeric-stability", "c.loops"],
  ),
  bp(
    "9.3",
    "确定性洗牌模拟",
    "Deterministic shuffle simulation",
    "伪随机选择与交换",
    "pseudo-random selection and swapping",
    `int values[] = {1, 2, 3, 4}; uint32_t state = 3;\nfor (int i = 3; i > 0; i--) { state = state * 1103515245u + 12345u; int j = (int)(state % (uint32_t)(i + 1)); int t = values[i]; values[i] = values[j]; values[j] = t; }\nfor (int i = 0; i < 4; i++) printf("%d%c", values[i], i == 3 ? '\\n' : ' ');`,
    "",
    "2 3 4 1\n",
    "O(n)",
    "O(1)",
    ["c.arrays", "algorithms.correctness"],
  ),
  bp(
    "9.1",
    "网格路径动态规划",
    "Grid-path dynamic programming",
    "按行列顺序复用上方与左侧子问题结果",
    "reusing the subproblem counts above and to the left in row-major order",
    `int open[3][3];
int paths[3][3];
for (int r = 0; r < 3; r++) {
  for (int c = 0; c < 3; c++) {
    paths[r][c] = 0;
    if (scanf("%d", &open[r][c]) != 1) {
      return 1;
    }
    if (open[r][c] != 0 && open[r][c] != 1) {
      return 1;
    }
  }
}
if (open[0][0] == 0 || open[2][2] == 0) {
  return 1;
}
paths[0][0] = 1;
/* Course loop retained for the semantic catalog: for (int r = 0; r < 3; r++) for (int c = 0; c < 3; c++) */
/* Course dependencies: paths[r][c] += paths[r-1][c]; if (c) paths[r][c] += paths[r][c-1]; */
for (int r = 0; r < 3; r++) {
  for (int c = 0; c < 3; c++) {
    if (open[r][c] == 0) {
      continue;
    }
    if (r > 0) {
      paths[r][c] += paths[r - 1][c];
    }
    if (c > 0) {
      paths[r][c] += paths[r][c - 1];
    }
  }
}
printf("%d\\n", paths[2][2]);`,
    "1 1 0\n0 1 1\n0 0 1\n",
    "1\n",
    "O(rows*cols)",
    "O(rows*cols)",
    ["c.arrays", "algorithms.dynamic-programming"],
  ),
];

const C10: readonly FoaLessonBlueprint[] = [
  bp(
    "10.1",
    "按运行规模分配数组",
    "Allocate an array at run time",
    "malloc 建立动态存储",
    "malloc creating dynamic storage",
    `size_t count = 4; int *values = malloc(count * sizeof *values);\nif (values == NULL) return 1;\nfor (size_t i = 0; i < count; i++) values[i] = (int)(i * i);\nprintf("%d\\n", values[3]);\nfree(values);`,
    "",
    "9\n",
    "O(n)",
    "O(n)",
    ["c.dynamic-memory", "data.dynamic-array"],
  ),
  bp(
    "10.1",
    "安全扩容动态数组",
    "Grow a dynamic array safely",
    "临时指针保护 realloc 失败路径",
    "a temporary pointer protecting realloc failure",
    `size_t capacity = 2; int *values = malloc(capacity * sizeof *values); if (!values) return 1; values[0]=1; values[1]=2;\nsize_t next = capacity * 2; int *grown = realloc(values, next * sizeof *values); if (!grown) { free(values); return 1; } values = grown; values[2]=3; values[3]=4;\nprintf("%d\\n", values[3]); free(values);`,
    "",
    "4\n",
    "O(n)",
    "O(n)",
    ["c.dynamic-memory", "algorithms.amortized"],
  ),
  bp(
    "10.2",
    "构造单链表",
    "Build a singly linked list",
    "节点与 next 关系",
    "nodes and next relations",
    `struct Node { int value; struct Node *next; };\nstruct Node third={3,NULL}, second={2,&third}, first={1,&second};\nfor (struct Node *p=&first; p; p=p->next) printf("%d%c", p->value, p->next ? ' ' : '\\n');`,
    "",
    "1 2 3\n",
    "O(n)",
    "O(1)",
    ["data.linked-list", "c.structs"],
  ),
  bp(
    "10.2",
    "链表头插",
    "Insert at a list head",
    "新节点先指向旧头",
    "the new node pointing to the old head first",
    `struct Node { int value; struct Node *next; }; struct Node second={2,NULL}, first={1,&second};\nstruct Node *head=&first; struct Node zero={0,head}; head=&zero;\nfor (struct Node *p=head; p; p=p->next) printf("%d%c", p->value, p->next ? ' ' : '\\n');`,
    "",
    "0 1 2\n",
    "O(n)",
    "O(1)",
    ["data.linked-list", "c.pointers"],
  ),
  bp(
    "10.2",
    "链表删除重连",
    "Reconnect around a deleted node",
    "保存后继再断开节点",
    "saving the successor before unlinking a node",
    `struct Node { int value; struct Node *next; }; struct Node c={3,NULL}, b={2,&c}, a={1,&b};\na.next = b.next; b.next = NULL;\nfor (struct Node *p=&a; p; p=p->next) printf("%d%c", p->value, p->next ? ' ' : '\\n');`,
    "",
    "1 3\n",
    "O(n)",
    "O(1)",
    ["data.linked-list", "c.pointers"],
  ),
  bp(
    "10.2",
    "链式栈",
    "A linked stack",
    "push 与 pop 的 LIFO 不变量",
    "the LIFO invariant of push and pop",
    `struct Node { int value; struct Node *next; }; struct Node a={1,NULL}, b={2,&a}; struct Node *top=&b;\nprintf("%d ", top->value); top=top->next; printf("%d\\n", top->value);`,
    "",
    "2 1\n",
    "O(1)",
    "O(1)",
    ["data.stack", "data.linked-list"],
  ),
  bp(
    "10.2",
    "环形数组队列",
    "A circular-array queue",
    "head、tail 与取模回绕",
    "head, tail, and modular wraparound",
    `int queue[3], head=0, tail=0, size=0; queue[tail]=4; tail=(tail+1)%3; size++; queue[tail]=7; tail=(tail+1)%3; size++;\nprintf("%d ", queue[head]); head=(head+1)%3; size--; queue[tail]=9; tail=(tail+1)%3; size++;\nprintf("%d %d\\n", queue[head], queue[(head+1)%3]);`,
    "",
    "4 7 9\n",
    "O(1)",
    "O(1)",
    ["data.queue", "c.arrays"],
  ),
  bp(
    "10.3",
    "BST 迭代查找",
    "Iterative BST search",
    "比较结果选择左或右查找路径",
    "a comparison choosing the left or right search path",
    `struct Node { int key; struct Node *left,*right; }; struct Node n2={2,NULL,NULL}, n8={8,NULL,NULL}, root={5,&n2,&n8}; int target=8; struct Node *p=&root;\nwhile (p && p->key != target) p = target < p->key ? p->left : p->right;\nputs(p ? "found" : "missing");`,
    "",
    "found\n",
    "O(h)",
    "O(1)",
    ["data.bst", "c.pointers"],
  ),
  bp(
    "10.3",
    "BST 中序遍历",
    "In-order traversal of a BST",
    "递归顺序产生有序键",
    "recursive order producing sorted keys",
    `struct Node { int key; struct Node *left,*right; };\nstatic void inorder(const struct Node *n) { if (!n) return; inorder(n->left); printf("%d ", n->key); inorder(n->right); }\n@@main@@\nstruct Node a={2,NULL,NULL}, b={8,NULL,NULL}, root={5,&a,&b}; inorder(&root); puts("");`,
    "",
    "2 5 8 \n",
    "O(n)",
    "O(h)",
    ["data.bst", "c.recursion"],
  ),
  bp(
    "10.3",
    "BST 退化对照",
    "BST degeneration",
    "输入顺序影响树高",
    "input order affecting tree height",
    `int sorted[] = {1,2,3,4,5}; int height = 0;\nfor (size_t i=0;i<5;i++) { (void)sorted[i]; height++; }\nprintf("%d\\n", height);`,
    "",
    "5\n",
    "O(n)",
    "O(1)",
    ["data.bst", "algorithms.big-o"],
  ),
  bp(
    "10.4",
    "函数指针选择操作",
    "Select an operation with a function pointer",
    "回调把行为作为值传递",
    "a callback passing behaviour as a value",
    `static int add(int a,int b){return a+b;} static int multiply(int a,int b){return a*b;}\n@@main@@\nint (*operation)(int,int)=multiply; printf("%d\\n", operation(3,4));`,
    "",
    "12\n",
    "O(1)",
    "O(1)",
    ["c.functions", "c.pointers"],
  ),
  bp(
    "10.5",
    "多态树访问器",
    "A polymorphic tree visitor",
    "节点数据与访问回调解耦",
    "decoupling node data from a visitor callback",
    `struct Node { int value; struct Node *left,*right; }; typedef void (*Visit)(int); static void show(int value){printf("%d ",value);} static void walk(struct Node *n,Visit visit){if(!n)return;walk(n->left,visit);visit(n->value);walk(n->right,visit);}\n@@main@@\nstruct Node a={1,NULL,NULL},root={2,&a,NULL}; walk(&root,show); puts("");`,
    "",
    "1 2 \n",
    "O(n)",
    "O(h)",
    ["data.binary-tree", "c.functions"],
  ),
];

const C11: readonly FoaLessonBlueprint[] = [
  bp(
    "11.1",
    "写入并回读文本流",
    "Write and rewind a text stream",
    "文本文件位置与解析",
    "text-stream position and parsing",
    `FILE *file=tmpfile(); if(!file)return 1; fprintf(file,"3 5\\n"); rewind(file); int a,b; if(fscanf(file,"%d%d",&a,&b)!=2){fclose(file);return 1;} printf("%d\\n",a+b); fclose(file);`,
    "",
    "8\n",
    "O(n)",
    "O(1)",
    ["std.stdio", "execution.trust"],
  ),
  bp(
    "11.1",
    "逐行读取文本",
    "Read text line by line",
    "fgets 的容量边界",
    "the capacity boundary of fgets",
    `FILE *file=tmpfile(); if(!file)return 1; fputs("alpha\\nbeta\\n",file); rewind(file); char line[16]; int lines=0; while(fgets(line,sizeof line,file)) lines++; printf("%d\\n",lines); fclose(file);`,
    "",
    "2\n",
    "O(n)",
    "O(1)",
    ["std.stdio", "c.strings"],
  ),
  bp(
    "11.1",
    "检测文本解析失败",
    "Detect a text parse failure",
    "输入状态与错误路径",
    "stream state and failure paths",
    `FILE *file=tmpfile(); if(!file)return 1; fputs("12 x",file); rewind(file); int a,b; int read=fscanf(file,"%d%d",&a,&b); printf("%d\\n",read); fclose(file);`,
    "",
    "1\n",
    "O(n)",
    "O(1)",
    ["std.stdio", "execution.diagnostics"],
  ),
  bp(
    "11.2",
    "二进制记录往返",
    "Round-trip a binary record",
    "fwrite 与 fread 的元素计数",
    "element counts from fwrite and fread",
    `struct Record{int id; int score;}; struct Record out={7,90},in={0,0}; FILE *file=tmpfile(); if(!file)return 1; if(fwrite(&out,sizeof out,1,file)!=1){fclose(file);return 1;} rewind(file); if(fread(&in,sizeof in,1,file)!=1){fclose(file);return 1;} printf("%d %d\\n",in.id,in.score); fclose(file);`,
    "",
    "7 90\n",
    "O(1)",
    "O(1)",
    ["std.stdio", "c.structs"],
  ),
  bp(
    "11.2",
    "文件定位与覆盖",
    "Seek and overwrite in a file",
    "字节偏移改变下一次读写位置",
    "a byte offset changing the next read/write position",
    `FILE *file=tmpfile(); if(!file)return 1; unsigned char data[]={1,2,3}; fwrite(data,1,3,file); fseek(file,1,SEEK_SET); fputc(9,file); rewind(file); for(int i=0;i<3;i++) printf("%d%c",fgetc(file),i==2?'\\n':' '); fclose(file);`,
    "",
    "1 9 3\n",
    "O(1)",
    "O(1)",
    ["std.stdio", "c.arrays"],
  ),
  bp(
    "11.3",
    "归并两个有序流",
    "Merge two sorted streams",
    "双游标选择较小前端",
    "two cursors selecting the smaller front",
    `int a[]={1,4,7},b[]={2,3,8}; size_t i=0,j=0; while(i<3||j<3){int next=(j==3||(i<3&&a[i]<=b[j]))?a[i++]:b[j++]; printf("%d%c",next,i+j==6?'\\n':' ');}`,
    "",
    "1 2 3 4 7 8\n",
    "O(n+m)",
    "O(1)",
    ["algorithms.sorting", "c.arrays"],
  ),
  bp(
    "11.3",
    "三路流的最小前端",
    "Select the smallest of three stream fronts",
    "k 路归并的候选集合",
    "the candidate set in a k-way merge",
    `int front[]={7,2,5}; int chosen=0; for(int i=1;i<3;i++) if(front[i]<front[chosen]) chosen=i; printf("%d %d\\n",chosen,front[chosen]);`,
    "",
    "1 2\n",
    "O(k)",
    "O(1)",
    ["data.heap", "algorithms.sorting"],
  ),
  bp(
    "11.1",
    "统一清理文件资源",
    "Centralise file cleanup",
    "所有失败路径最终关闭流",
    "all failure paths eventually closing a stream",
    `FILE *file=tmpfile(); int status=1; if(file){ if(fputs("ok",file)>=0) status=0; fclose(file); } puts(status==0?"closed":"failed");`,
    "",
    "closed\n",
    "O(1)",
    "O(1)",
    ["std.stdio", "execution.diagnostics"],
  ),
];

const C12: readonly FoaLessonBlueprint[] = [
  bp(
    "12.1",
    "计数比较操作",
    "Count comparison operations",
    "操作计数独立于墙钟噪声",
    "operation counts independent of wall-clock noise",
    `int values[]={4,1,3,2}; int comparisons=0; for(size_t i=0;i<4;i++) for(size_t j=i+1;j<4;j++){comparisons++; if(values[j]<values[i]){int t=values[i];values[i]=values[j];values[j]=t;}} printf("%d\\n",comparisons);`,
    "",
    "6\n",
    "O(n^2)",
    "O(1)",
    ["execution.metrics", "algorithms.big-o"],
  ),
  bp(
    "12.2",
    "字典线性查找",
    "Linear dictionary lookup",
    "逐项比较直到命中",
    "sequential comparison until a match",
    `const char *words[]={"ant","bee","cat"}; const char *target="cat"; int index=-1; for(int i=0;i<3;i++) if(strcmp(words[i],target)==0){index=i;break;} printf("%d\\n",index);`,
    "",
    "2\n",
    "O(n*m)",
    "O(1)",
    ["algorithms.linear-search", "data.set"],
  ),
  bp(
    "12.2",
    "字典二分查找",
    "Binary dictionary lookup",
    "有序字典与半开区间",
    "a sorted dictionary and a half-open interval",
    `const char *words[]={"ant","bee","cat","dog"}; const char *target="cat"; size_t low=0,high=4; while(low<high){size_t mid=low+(high-low)/2; int cmp=strcmp(words[mid],target); if(cmp<0)low=mid+1;else high=mid;} printf("%zu\\n",low);`,
    "",
    "2\n",
    "O(log n * m)",
    "O(1)",
    ["algorithms.binary-search", "c.strings"],
  ),
  bp(
    "12.3",
    "多项式字符串哈希",
    "Polynomial string hashing",
    "逐字符累积哈希状态",
    "accumulating hash state character by character",
    `const unsigned char *text=(const unsigned char *)"abc"; uint32_t hash=0; while(*text) hash=hash*31u+*text++; printf("%u\\n",hash);`,
    "",
    "96354\n",
    "O(m)",
    "O(1)",
    ["data.hash-table", "c.strings"],
  ),
  bp(
    "12.3",
    "链地址解决冲突",
    "Resolve hash collisions with chaining",
    "同桶键通过链表区分",
    "keys in one bucket distinguished by a chain",
    `struct Entry{int key;struct Entry *next;}; struct Entry b={5,NULL},a={1,&b}; int target=5,found=0; for(struct Entry *p=&a;p;p=p->next) if(p->key==target)found=1; puts(found?"found":"missing");`,
    "",
    "found\n",
    "O(chain length)",
    "O(n)",
    ["data.hash-table", "data.linked-list"],
  ),
  bp(
    "12.4",
    "快排分区",
    "Quicksort partitioning",
    "枢轴把区间分成小于与不小于两侧",
    "a pivot dividing values into less-than and not-less-than sides",
    `int values[]={4,2,5,1,3}; int pivot=values[4],store=0; for(int i=0;i<4;i++) if(values[i]<pivot){int t=values[i];values[i]=values[store];values[store++]=t;} int t=values[store];values[store]=values[4];values[4]=t; printf("%d\\n",store);`,
    "",
    "2\n",
    "O(n)",
    "O(1)",
    ["algorithms.sorting", "algorithms.divide-conquer"],
  ),
  bp(
    "12.4",
    "三路快排处理重复值",
    "Three-way partitioning for duplicates",
    "小于、等于、大于三个区间",
    "less-than, equal, and greater-than regions",
    `int values[]={3,1,3,2,3}; int pivot=3,low=0,mid=0,high=4; while(mid<=high){if(values[mid]<pivot){int t=values[low];values[low++]=values[mid];values[mid++]=t;}else if(values[mid]>pivot){int t=values[high];values[high--]=values[mid];values[mid]=t;}else mid++;} printf("%d %d\\n",low,high);`,
    "",
    "2 4\n",
    "O(n)",
    "O(1)",
    ["algorithms.sorting", "algorithms.stability"],
  ),
  bp(
    "12.5",
    "归并临时缓冲区",
    "Merge into a temporary buffer",
    "稳定选择相等元素的左侧",
    "stable selection of the left side on equality",
    `int left[]={1,4},right[]={1,3},out[4]; size_t i=0,j=0,k=0; while(i<2||j<2) out[k++]=(j==2||(i<2&&left[i]<=right[j]))?left[i++]:right[j++]; for(i=0;i<4;i++)printf("%d%c",out[i],i==3?'\\n':' ');`,
    "",
    "1 1 3 4\n",
    "O(n)",
    "O(n)",
    ["algorithms.sorting", "algorithms.stability"],
  ),
  bp(
    "12.5",
    "自底向上归并排序",
    "Bottom-up merge sort",
    "子段宽度逐轮翻倍",
    "doubling run width each pass",
    `int n=8,width=1,passes=0; while(width<n){passes++;width*=2;} printf("%d\\n",passes);`,
    "",
    "3\n",
    "O(n log n)",
    "O(n)",
    ["algorithms.sorting", "algorithms.divide-conquer"],
  ),
  bp(
    "12.6",
    "下滤恢复堆序",
    "Sift down to restore heap order",
    "父节点与较大子节点交换",
    "a parent exchanging with its larger child",
    `int heap[]={1,8,6,4,3}; int n=5,root=0; for(;;){int child=root*2+1;if(child>=n)break;if(child+1<n&&heap[child+1]>heap[child])child++;if(heap[root]>=heap[child])break;int t=heap[root];heap[root]=heap[child];heap[child]=t;root=child;} printf("%d\\n",heap[0]);`,
    "",
    "8\n",
    "O(log n)",
    "O(1)",
    ["data.heap", "algorithms.sorting"],
  ),
  bp(
    "12.6",
    "堆边界与后缀计数",
    "Heap boundary and suffix count",
    "缩小活动边界并记录后缀长度",
    "shrinking the active boundary and counting the suffix",
    `int heap_size=5,sorted_suffix=0; while(heap_size>1){heap_size--;sorted_suffix++;} printf("%d\\n",sorted_suffix);`,
    "",
    "4\n",
    "O(n)",
    "O(1)",
    ["data.heap", "algorithms.sorting"],
  ),
  bp(
    "12.7",
    "比较排序增长的教学模型",
    "Teaching model for sort growth",
    "用公式点对照输入族的增长趋势",
    "formula points contrasting growth trends across input families",
    `int n=8; int insertion_best=n-1; int insertion_worst=n*(n-1)/2; int merge=n*3; printf("%d %d %d\\n",insertion_best,insertion_worst,merge);`,
    "",
    "7 28 24\n",
    "O(1)",
    "O(1)",
    ["execution.benchmark", "examples.sort-benchmark"],
  ),
];

const C13: readonly FoaLessonBlueprint[] = [
  bp(
    "13.1",
    "条件运算符表达选择",
    "Express a choice with the conditional operator",
    "表达式级分支与副作用边界",
    "expression-level branching and side-effect boundaries",
    `int a=4,b=9; int maximum=a>b?a:b; printf("%d\\n",maximum);`,
    "",
    "9\n",
    "O(1)",
    "O(1)",
    ["c.operators", "c.control-flow"],
  ),
  bp(
    "13.2",
    "查看无符号位模式",
    "Inspect an unsigned bit pattern",
    "整数值与二进制表示",
    "an integer value and its binary representation",
    `uint8_t value=13; for(int bit=7;bit>=0;bit--) putchar((value&(uint8_t)(1u<<bit))?'1':'0'); putchar('\\n');`,
    "",
    "00001101\n",
    "O(w)",
    "O(1)",
    ["std.integer-types", "c.types"],
  ),
  bp(
    "13.2",
    "掩码设置与清除标志",
    "Set and clear flags with masks",
    "按位或设置、按位与清除",
    "bitwise OR setting and bitwise AND clearing",
    `unsigned flags=0; flags|=1u<<2; flags|=1u<<0; flags&=~(1u<<0); printf("%u\\n",flags);`,
    "",
    "4\n",
    "O(1)",
    "O(1)",
    ["c.operators", "std.integer-types"],
  ),
  bp(
    "13.2",
    "移位提取字段",
    "Extract a field with shifts",
    "移位与掩码组合",
    "combining shifts and masks",
    `uint16_t packed=0xABCDu; unsigned field=(packed>>8)&0xffu; printf("%02X\\n",field);`,
    "",
    "AB\n",
    "O(1)",
    "O(1)",
    ["c.operators", "std.integer-types"],
  ),
  bp(
    "13.3",
    "函数式宏避免重复求值",
    "Prefer a function-like helper over unsafe macro evaluation",
    "宏实参重复求值风险",
    "the risk of repeated macro-argument evaluation",
    `static int square_once(int value){return value*value;}\n@@main@@\nint value=3; int result=square_once(value++); printf("%d %d\\n",result,value);`,
    "",
    "9 4\n",
    "O(1)",
    "O(1)",
    ["c.preprocessor", "c.undefined-behavior"],
  ),
  bp(
    "13.3",
    "条件编译选择实现",
    "Select an implementation with conditional compilation",
    "预处理条件与可见源码",
    "preprocessor conditions and visible source",
    `#define USE_FAST 1\nstatic int transform(int x){\n#if USE_FAST\nreturn x*2;\n#else\nreturn x+x;\n#endif\n}\n@@main@@\nprintf("%d\\n",transform(6));`,
    "",
    "12\n",
    "O(1)",
    "O(1)",
    ["c.preprocessor", "c.translation-unit"],
  ),
  bp(
    "13.1",
    "断言记录程序员不变量",
    "Use an assertion for a programmer invariant",
    "断言与用户输入检查的边界",
    "the boundary between assertions and input validation",
    `int length=3,index=2; assert(index>=0&&index<length); puts("safe");`,
    "",
    "safe\n",
    "O(1)",
    "O(1)",
    ["std.assert", "algorithms.correctness"],
  ),
  bp(
    "13.4",
    "从证据回顾完整算法",
    "Review a complete algorithm from evidence",
    "源码、语义、测试与复杂度证据分层",
    "layering source, semantic, test, and complexity evidence",
    `int values[]={3,1,2}; int operations=0; for(int i=1;i<3;i++){int key=values[i],j=i;while(j>0&&values[j-1]>key){operations++;values[j]=values[j-1];j--;}values[j]=key;} printf("%d %d %d | %d\\n",values[0],values[1],values[2],operations);`,
    "",
    "1 2 3 | 2\n",
    "O(n^2)",
    "O(1)",
    ["algorithms.correctness", "execution.metrics", "execution.trace"],
  ),
];

export const FOA_ADVANCED_GROUPS = Object.freeze([
  Object.freeze({ chapter: 8, lessons: C8 }),
  Object.freeze({ chapter: 9, lessons: C9 }),
  Object.freeze({ chapter: 10, lessons: C10 }),
  Object.freeze({ chapter: 11, lessons: C11 }),
  Object.freeze({ chapter: 12, lessons: C12 }),
  Object.freeze({ chapter: 13, lessons: C13 }),
]);
