import type { FoaLessonExperience } from "./foa-contracts.js";
import { defineFoaLessonExperience } from "./foa-lesson-experience.js";

export const FOA_LESSON_EXPERIENCES_041_080: Readonly<Record<number, FoaLessonExperience>> =
  Object.freeze({
    41: defineFoaLessonExperience({
      visualFamily: "pipeline",
      visualModelZh: "横向函数管道：10 → twice → 20 → plus_one → 21。",
      visualModelEn: "A horizontal function pipeline: 10 → twice → 20 → plus_one → 21.",
      primaryActionZh: "把值依次拖过两个函数门，保持嵌套调用顺序。",
      primaryActionEn: "Drag the value through both function gates in nested-call order.",
      sequence: [
        ["计算内层 twice(10)。", "Evaluate the inner call twice(10)."],
        ["把返回值交给外层函数。", "Pass the return value to the outer function."],
        ["计算 plus_one(20)。", "Evaluate plus_one(20)."],
        ["输出 21。", "Output 21."],
      ],
      playbackMs: 1200,
      playbackPolicy: "guided",
      persistentEvidenceZh: "当前值及产生它的函数。",
      persistentEvidenceEn: "The current value and the function that produced it.",
      hiddenByDefaultZh: "函数元数据、复杂度、调用栈表与完整源码。",
      hiddenByDefaultEn: "Function metadata, complexity, the call-stack table, and full source.",
      researchUrls: ["https://pythontutor.com/c.html"],
    }),
    42: defineFoaLessonExperience({
      visualFamily: "execution",
      visualModelZh: "程序边界的双通道出口：标准输出与退出状态彼此独立。",
      visualModelEn:
        "Two independent channels at the program boundary: standard output and exit status.",
      primaryActionZh: "分别预测屏幕文字和进程状态，再运行核对。",
      primaryActionEn:
        "Predict the displayed text and process status separately, then run to check.",
      sequence: [
        ["启动程序。", "Start the program."],
        ["写入标准输出。", "Write to standard output."],
        ["main 返回。", "Return from main."],
        ["宿主接收状态码。", "Let the host receive the status code."],
      ],
      playbackMs: 1400,
      playbackPolicy: "guided",
      persistentEvidenceZh: "退出状态为 0 或非 0。",
      persistentEvidenceEn: "Whether the exit status is zero or non-zero.",
      hiddenByDefaultZh: "进程树、信号、Shell 语法和完整编译信息。",
      hiddenByDefaultEn: "Process trees, signals, shell syntax, and full compilation details.",
      researchUrls: ["https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf"],
    }),
    43: defineFoaLessonExperience({
      visualFamily: "execution",
      visualModelZh: "无返回插槽的函数框；调用时只向输出纸带追加一行。",
      visualModelEn:
        "A function box with no return slot; calling it only appends a line to the output tape.",
      primaryActionZh: "调用一次函数，观察没有返回值但输出发生变化。",
      primaryActionEn: "Call the function once and observe output changing without a return value.",
      sequence: [
        ["进入 print_separator。", "Enter print_separator."],
        ["执行 puts。", "Execute puts."],
        ["输出纸带新增 ---。", "Append --- to the output tape."],
        ["无值返回调用点。", "Return to the call site without a value."],
      ],
      playbackMs: 1300,
      playbackPolicy: "guided",
      persistentEvidenceZh: "输出纸带新增的一行 ---。",
      persistentEvidenceEn: "The newly appended --- line on the output tape.",
      hiddenByDefaultZh: "返回值占位符、栈地址、stdio 缓冲实现和长解释。",
      hiddenByDefaultEn:
        "Return-value placeholders, stack addresses, stdio buffering details, and long explanations.",
      researchUrls: ["https://pythontutor.com/c.html"],
    }),
    44: defineFoaLessonExperience({
      visualFamily: "memory",
      visualModelZh: "嵌套作用域框中各有一个独立 value，使用点连向实际声明。",
      visualModelEn:
        "Nested scope boxes each contain a distinct value, with each use linked to its declaration.",
      primaryActionZh: "为两处 printf(value) 选择其实际声明来源。",
      primaryActionEn: "Choose the declaration resolved by each printf(value) use.",
      sequence: [
        ["建立外层 value=3。", "Create the outer value=3."],
        ["进入块并建立内层 value=8。", "Enter the block and create the inner value=8."],
        ["内层使用绑定到 8。", "Bind the inner use to 8."],
        ["离开块后重新绑定到 3。", "After leaving the block, resolve the use to 3."],
      ],
      playbackMs: 1500,
      playbackPolicy: "guided",
      persistentEvidenceZh: "当前使用点到声明对象的绑定箭头。",
      persistentEvidenceEn: "The binding arrow from the current use to its declaration object.",
      hiddenByDefaultZh: "地址、存储布局、编译器符号表和完整作用域定义。",
      hiddenByDefaultEn:
        "Addresses, storage layout, compiler symbol tables, and the full definition of scope.",
      researchUrls: ["https://clang.llvm.org/docs/DiagnosticsReference.html#wshadow"],
    }),
    45: defineFoaLessonExperience({
      visualFamily: "state",
      visualModelZh: "函数框外的共享 counter；两个调用都连接到同一对象。",
      visualModelEn:
        "A shared counter outside the function box, referenced by both calls as one object.",
      primaryActionZh: "连续触发两次 count_once，确认写入的是同一共享对象。",
      primaryActionEn:
        "Trigger count_once twice and confirm that both calls write the same shared object.",
      sequence: [
        ["文件级 counter 初始化为 0。", "Initialize the file-scope counter to 0."],
        ["第一次调用写成 1。", "The first call writes 1."],
        ["第二次调用写成 2。", "The second call writes 2."],
        ["main 读取 2。", "main reads 2."],
      ],
      playbackMs: 1400,
      playbackPolicy: "guided",
      persistentEvidenceZh: "共享 counter 的单一对象身份和当前值。",
      persistentEvidenceEn: "The shared counter's single object identity and current value.",
      hiddenByDefaultZh: "链接器、多翻译单元、线程安全和符号可见性细节。",
      hiddenByDefaultEn:
        "Linker behavior, multiple translation units, thread safety, and symbol visibility details.",
      researchUrls: ["https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf"],
    }),
    46: defineFoaLessonExperience({
      visualFamily: "state",
      visualModelZh: "next_id 内固定一格 static id；调用帧消失时它仍保留。",
      visualModelEn:
        "A fixed static id cell inside next_id that remains when individual call frames disappear.",
      primaryActionZh: "调用两次，观察调用帧重建而 id 连续递增。",
      primaryActionEn: "Call twice and observe frames being recreated while id keeps increasing.",
      sequence: [
        ["首次进入并读取静态 id。", "Enter the first call and read the static id."],
        ["递增并返回 1。", "Increment and return 1."],
        ["建立新的调用帧。", "Create a new call frame."],
        ["同一 id 递增并返回 2。", "Increment the same id and return 2."],
      ],
      playbackMs: 1500,
      playbackPolicy: "guided",
      persistentEvidenceZh: "静态格的连续历史 0→1→2。",
      persistentEvidenceEn: "The static cell's continuous history, 0→1→2.",
      hiddenByDefaultZh: "静态区地址、内存分段、重入和并发问题。",
      hiddenByDefaultEn:
        "Static-region addresses, memory segments, reentrancy, and concurrency concerns.",
      researchUrls: ["https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2328.pdf"],
    }),
    47: defineFoaLessonExperience({
      visualFamily: "pointer-graph",
      visualModelZh: "一个 value 对象和一条由 address 指向它的稳定箭头。",
      visualModelEn: "One value object with a stable arrow to it from address.",
      primaryActionZh: "沿指针箭头找到目标，把目标值从 7 改为 9。",
      primaryActionEn: "Follow the pointer arrow and change the target value from 7 to 9.",
      sequence: [
        ["创建 value。", "Create value."],
        ["用 &value 建立指针。", "Create the pointer with &value."],
        ["用 *address 定位目标。", "Locate the target with *address."],
        ["通过目标写入 9。", "Write 9 through the target."],
      ],
      playbackMs: 1600,
      playbackPolicy: "guided",
      persistentEvidenceZh: "address → value 的别名边。",
      persistentEvidenceEn: "The address → value alias edge.",
      hiddenByDefaultZh: "十六进制地址、字节序、指针算术和多余端口。",
      hiddenByDefaultEn:
        "Hexadecimal addresses, byte order, pointer arithmetic, and unnecessary ports.",
      researchUrls: ["https://pythontutor.com/c.html"],
    }),
    48: defineFoaLessonExperience({
      visualFamily: "pointer-graph",
      visualModelZh: "a、b 两个稳定对象，left/right 两条别名边和一个 temporary 槽。",
      visualModelEn:
        "Two stable objects a and b, two alias edges left/right, and one temporary slot.",
      primaryActionZh: "按正确顺序完成三次赋值，避免原值丢失。",
      primaryActionEn:
        "Perform the three assignments in the order that preserves both original values.",
      sequence: [
        ["temporary 保存 *left。", "Save *left in temporary."],
        ["把 *right 写入 *left。", "Write *right into *left."],
        ["把 temporary 写入 *right。", "Write temporary into *right."],
        ["返回后核对 a 与 b。", "Check a and b after returning."],
      ],
      playbackMs: 1700,
      playbackPolicy: "guided",
      persistentEvidenceZh: "a、b、temporary 三个槽位的当前值。",
      persistentEvidenceEn: "The current values in the a, b, and temporary slots.",
      hiddenByDefaultZh: "通用 swap、宏、真实地址和完整函数说明。",
      hiddenByDefaultEn: "Generic swap variants, macros, real addresses, and full function notes.",
      researchUrls: ["https://pythontutor.com/c.html"],
    }),
    49: defineFoaLessonExperience({
      visualFamily: "pipeline",
      visualModelZh: "minmax 盒子接收一个输入对，并提供 minimum 与 maximum 两个命名输出口。",
      visualModelEn:
        "A minmax box accepts one input pair and exposes named minimum and maximum output ports.",
      primaryActionZh: "把 3 和 8 分别路由到 low 与 high。",
      primaryActionEn: "Route 3 and 8 to low and high respectively.",
      sequence: [
        ["比较 a 与 b。", "Compare a and b."],
        ["较小值写入 minimum。", "Write the smaller value to minimum."],
        ["较大值写入 maximum。", "Write the larger value to maximum."],
        ["调用者读取 low 与 high。", "Let the caller read low and high."],
      ],
      playbackMs: 1500,
      playbackPolicy: "guided",
      persistentEvidenceZh: "minimum→low=3 与 maximum→high=8 的输出映射。",
      persistentEvidenceEn: "The output mapping minimum→low=3 and maximum→high=8.",
      hiddenByDefaultZh: "三元表达式展开、地址数字和 ABI 返回约定。",
      hiddenByDefaultEn:
        "Expanded conditional expressions, numeric addresses, and ABI return conventions.",
      researchUrls: ["https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf"],
    }),
    50: defineFoaLessonExperience({
      visualFamily: "decision",
      visualModelZh: "输入门同时产生状态灯和 out 槽；失败时 out 保持不可用。",
      visualModelEn:
        "An input gate produces both a status light and an out slot; out remains unavailable on failure.",
      primaryActionZh: "分别投放合法整数与非法 token，决定是否允许后续计算。",
      primaryActionEn:
        "Submit a valid integer and an invalid token, then decide whether computation may continue.",
      sequence: [
        ["scanf 尝试匹配。", "Let scanf attempt a match."],
        ["读取匹配项数量。", "Read the number of matched items."],
        ["成功时才写 out。", "Write out only on success."],
        ["调用者按状态分支。", "Branch in the caller using the status."],
      ],
      playbackMs: 1600,
      playbackPolicy: "guided",
      persistentEvidenceZh: "状态值与 out 是否有效组成的二元契约。",
      persistentEvidenceEn: "The two-part contract: status value and whether out is valid.",
      hiddenByDefaultZh: "输入缓冲残留、locale、EOF 细分和后续乘法结果。",
      hiddenByDefaultEn:
        "Input-buffer leftovers, locale, detailed EOF cases, and the downstream multiplication result.",
      researchUrls: ["https://pubs.opengroup.org/onlinepubs/9799919799/functions/fscanf.html"],
    }),
    51: defineFoaLessonExperience({
      visualFamily: "sequence",
      visualModelZh: "四格数组、单一扫描游标和右侧累加器。",
      visualModelEn: "A four-cell array, one scan cursor, and an accumulator on the right.",
      primaryActionZh: "逐格把当前元素加入 sum，不能跳格或重复加入。",
      primaryActionEn: "Add each current element to sum without skipping or counting a cell twice.",
      sequence: [
        ["游标指向当前元素。", "Point the cursor at the current element."],
        ["读取当前值。", "Read the current value."],
        ["累加到 sum。", "Accumulate it into sum."],
        ["游标前进直到边界。", "Advance the cursor to the boundary."],
      ],
      playbackMs: 1100,
      playbackPolicy: "guided",
      persistentEvidenceZh: "sum 当前值和本次短算式。",
      persistentEvidenceEn: "The current sum and the short equation for this step.",
      hiddenByDefaultZh: "完整变量表、复杂度、代码块连线和全部历史算式。",
      hiddenByDefaultEn:
        "The full variable table, complexity, block wiring, and the complete equation history.",
      researchUrls: ["https://pythontutor.com/c.html"],
    }),
    52: defineFoaLessonExperience({
      visualFamily: "memory",
      visualModelZh: "五个物理槽和一条标出 count 有效区的边界尺。",
      visualModelEn: "Five physical slots with a boundary ruler marking the valid count region.",
      primaryActionZh: "先设置 count，再依次把输入放入有效槽；越界输入会被挡回。",
      primaryActionEn:
        "Set count first, then place inputs in valid slots; reject anything beyond capacity.",
      sequence: [
        ["读取 count。", "Read count."],
        ["验证 0≤count≤5。", "Validate 0≤count≤5."],
        ["只填充 [0,count)。", "Fill only [0,count)."],
        ["读取最后一个有效元素或空数组结果。", "Read the last valid element or the empty result."],
      ],
      playbackMs: 1300,
      playbackPolicy: "guided",
      persistentEvidenceZh: "count / CAPACITY 边界尺。",
      persistentEvidenceEn: "The count / CAPACITY boundary ruler.",
      hiddenByDefaultZh: "未初始化槽内容、栈布局和 scanf 结果列表。",
      hiddenByDefaultEn:
        "Uninitialized slot contents, stack layout, and a full list of scanf results.",
      researchUrls: [
        "https://wiki.sei.cmu.edu/confluence/spaces/c/pages/87152051/Rule%2B06.%2BArrays%2BARR",
      ],
    }),
    53: defineFoaLessonExperience({
      visualFamily: "pointer-graph",
      visualModelZh: "函数调用口只接收首元素指针与独立 length 标签，数组外框不被复制。",
      visualModelEn:
        "The function receives only a first-element pointer and a separate length; the array container is not copied.",
      primaryActionZh: "把数组指针与正确 length 配对后启动最大值扫描。",
      primaryActionEn:
        "Pair the array pointer with the correct length before starting the maximum scan.",
      sequence: [
        ["数组参数成为首元素指针。", "Adjust the array parameter to a first-element pointer."],
        ["length 建立合法范围。", "Use length to establish the valid range."],
        ["扫描 [0,length)。", "Scan [0,length)."],
        ["返回 maximum。", "Return maximum."],
      ],
      playbackMs: 1500,
      playbackPolicy: "guided",
      persistentEvidenceZh: "函数内合法访问区间 [0,length)。",
      persistentEvidenceEn: "The valid access interval [0,length) inside the function.",
      hiddenByDefaultZh: "sizeof 陷阱全文、ABI 和会暗示数组复制的动画。",
      hiddenByDefaultEn:
        "The full sizeof warning, ABI details, and any animation implying that the array is copied.",
      researchUrls: ["https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87151963"],
    }),
    54: defineFoaLessonExperience({
      visualFamily: "sequence",
      visualModelZh: "2×3 网格，每次只框一行，并用横向列游标累加当前行。",
      visualModelEn:
        "A 2×3 grid that frames one row at a time, with a horizontal column cursor accumulating it.",
      primaryActionZh: "横扫第一行后切换第二行，不跨行跳转。",
      primaryActionEn: "Sweep the first row, then move to the second without crossing rows early.",
      sequence: [
        ["选定 row。", "Select a row."],
        ["逐列累加。", "Accumulate across its columns."],
        ["输出该行和。", "Output that row's sum."],
        ["清零 sum 并进入下一行。", "Reset sum and enter the next row."],
      ],
      playbackMs: 1150,
      playbackPolicy: "guided",
      persistentEvidenceZh: "当前行括号和该行 sum。",
      persistentEvidenceEn: "The current-row bracket and that row's sum.",
      hiddenByDefaultZh: "线性地址、行主序公式、完整双层循环变量表。",
      hiddenByDefaultEn:
        "Linear addresses, row-major formulas, and the complete nested-loop variable table.",
      researchUrls: ["https://pythontutor.com/c.html"],
    }),
    55: defineFoaLessonExperience({
      visualFamily: "memory",
      visualModelZh: "五格初始化板；指定位置写入后，其余格统一显现为 0。",
      visualModelEn:
        "A five-cell initialization board where unspecified cells resolve uniformly to zero.",
      primaryActionZh: "把 [1]=3 和 [4]=2 拖到对应索引。",
      primaryActionEn: "Drag [1]=3 and [4]=2 to their designated indices.",
      sequence: [
        ["建立五个元素。", "Create five elements."],
        ["应用索引 1 的指定值。", "Apply the designated value at index 1."],
        ["应用索引 4 的指定值。", "Apply the designated value at index 4."],
        ["其余元素零初始化。", "Zero-initialize the remaining elements."],
      ],
      playbackMs: 1400,
      playbackPolicy: "guided",
      persistentEvidenceZh: "最终完整初态 [0,3,0,0,2]。",
      persistentEvidenceEn: "The complete final initial state [0,3,0,0,2].",
      hiddenByDefaultZh: "运行循环、对象表示、初始化规则长文和重复默认标签。",
      hiddenByDefaultEn:
        "The runtime loop, object representation, long initialization rules, and repeated default labels.",
      researchUrls: ["https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf"],
    }),
    56: defineFoaLessonExperience({
      visualFamily: "pointer-graph",
      visualModelZh: "数组下方一支 cursor 箭头，右侧固定 one-past-end 终点。",
      visualModelEn:
        "A cursor arrow under the array with a fixed one-past-the-end marker on the right.",
      primaryActionZh: "每次将 cursor 推进一格并解引用当前值。",
      primaryActionEn: "Advance cursor one cell at a time and dereference the current value.",
      sequence: [
        ["cursor 接收首元素地址。", "Set cursor to the first element."],
        ["解引用并输出。", "Dereference and output."],
        ["cursor++ 指向下一元素。", "Advance cursor to the next element."],
        ["到达 one-past-end 时停止。", "Stop at the one-past-the-end marker."],
      ],
      playbackMs: 1450,
      playbackPolicy: "guided",
      persistentEvidenceZh: "cursor 相对 values 的偏移和终点边界。",
      persistentEvidenceEn: "The cursor offset from values and the end boundary.",
      hiddenByDefaultZh: "真实地址、字节跨度、跨数组比较和泛化指针算术。",
      hiddenByDefaultEn:
        "Real addresses, byte strides, cross-array comparisons, and generalized pointer arithmetic.",
      researchUrls: ["https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf"],
    }),
    57: defineFoaLessonExperience({
      visualFamily: "sequence",
      visualModelZh: "字符格末尾有一个空心 NUL 终止格，length 标尺停在它之前。",
      visualModelEn:
        "Character cells end in a hollow NUL terminator, with the length ruler stopping before it.",
      primaryActionZh: "移动 length 标尺，并在 NUL 前停止计数。",
      primaryActionEn: "Advance the length ruler and stop counting before NUL.",
      sequence: [
        ["查看当前字符。", "Inspect the current character."],
        ["非 NUL 时递增 length。", "Increment length when it is not NUL."],
        ["移动到下一格。", "Move to the next cell."],
        ["遇到 NUL 时停止。", "Stop on reaching NUL."],
      ],
      playbackMs: 1200,
      playbackPolicy: "guided",
      persistentEvidenceZh: "NUL 边界格及其前方的 length 标尺。",
      persistentEvidenceEn: "The NUL boundary cell and the length ruler before it.",
      hiddenByDefaultZh: "编码体系、EOF 混淆说明、字符串库实现和每格索引。",
      hiddenByDefaultEn:
        "Character encodings, EOF comparisons, string-library internals, and per-cell indices.",
      researchUrls: [
        "https://wiki.sei.cmu.edu/confluence/spaces/c/pages/87152051/Rule%2B06.%2BArrays%2BARR",
      ],
    }),
    58: defineFoaLessonExperience({
      visualFamily: "search",
      visualModelZh: "上方输入带和下方 unique 架；当前词依次与已有唯一词比较。",
      visualModelEn:
        "An input tape above a unique shelf, with the current word compared against existing entries.",
      primaryActionZh: "对每个词判断已有或新增，再略过或追加。",
      primaryActionEn: "Classify each word as present or new, then skip or append it.",
      sequence: [
        ["取下一个输入词。", "Take the next input word."],
        ["从 unique 开头顺序比较。", "Compare from the start of unique."],
        ["命中则略过，否则追加。", "Skip on a match; otherwise append."],
        ["按首次出现顺序输出。", "Output in first-appearance order."],
      ],
      playbackMs: 1350,
      playbackPolicy: "guided",
      persistentEvidenceZh: "当前 unique 序列。",
      persistentEvidenceEn: "The current unique sequence.",
      hiddenByDefaultZh: "完整比较历史、字符串地址、逐字符 strcmp 和集合长解释。",
      hiddenByDefaultEn:
        "The full comparison history, string addresses, character-level strcmp, and long set explanations.",
      researchUrls: [
        "https://opendsa-server.cs.vt.edu/ODSA/Books/pubbook/odsa-all/fall-2019/Public_Instance/html/BinarySearch.html",
      ],
    }),
    59: defineFoaLessonExperience({
      visualFamily: "search",
      visualModelZh: "七格 weekday 查找表，输入 index 作为直接落到一格的选择器。",
      visualModelEn: "A seven-cell weekday table with the input index acting as a direct selector.",
      primaryActionZh: "输入索引，先验证其属于 [0,7)，再取对应字符串。",
      primaryActionEn: "Enter an index, validate that it lies in [0,7), then retrieve the string.",
      sequence: [
        ["读取 index。", "Read index."],
        ["验证范围。", "Validate the range."],
        ["选择 days[index]。", "Select days[index]."],
        ["输出字符串。", "Output the string."],
      ],
      playbackMs: 1250,
      playbackPolicy: "guided",
      persistentEvidenceZh: "范围条件 0≤index<7 和当前选中格。",
      persistentEvidenceEn: "The condition 0≤index<7 and the selected cell.",
      hiddenByDefaultZh: "顺序搜索动画、字符串地址和未选项解释。",
      hiddenByDefaultEn:
        "Sequential-search animation, string addresses, and explanations for unselected entries.",
      researchUrls: ["https://pythontutor.com/c.html"],
    }),
    60: defineFoaLessonExperience({
      visualFamily: "sorting",
      visualModelZh: "稳定元素卡、相邻比较窗口和清晰的已排序前缀边界。",
      visualModelEn:
        "Stable element cards, an adjacent-comparison window, and a clear sorted-prefix boundary.",
      primaryActionZh: "比较相邻元素；若逆序则交换并继续向左。",
      primaryActionEn: "Compare adjacent values; if out of order, swap and continue left.",
      sequence: [
        ["选中已排序前缀右侧元素。", "Select the value to the right of the sorted prefix."],
        ["比较它与左侧相邻元素。", "Compare it with its left neighbour."],
        ["若逆序则交换相邻元素。", "Swap the adjacent values when out of order."],
        ["停止交换并扩大已排序前缀。", "Stop swapping and extend the sorted prefix."],
      ],
      playbackMs: 1500,
      playbackPolicy: "guided",
      persistentEvidenceZh: "已排序前缀边界。",
      persistentEvidenceEn: "The sorted-prefix boundary.",
      hiddenByDefaultZh: "key+右移优化对照、课程元信息、完整计数和复杂度。",
      hiddenByDefaultEn:
        "The key-and-shift optimization contrast, lesson metadata, full counts, and complexity.",
      researchUrls: [
        "https://visualgo.net/en/sorting?slide=8",
        "https://opendsa-server.cs.vt.edu/embed",
      ],
    }),
    61: defineFoaLessonExperience({
      visualFamily: "memory",
      visualModelZh: "一张 Point 记录卡，内部只有 x、y 两个命名字段。",
      visualModelEn: "One Point record card containing only the named fields x and y.",
      primaryActionZh: "把 x=3、y=4 放入对应字段，再选择字段构造 x+y。",
      primaryActionEn: "Place x=3 and y=4 in their fields, then select them to form x+y.",
      sequence: [
        ["声明字段形状。", "Declare the field shape."],
        ["创建 point 实例。", "Create the point instance."],
        ["写入 x 与 y。", "Write x and y."],
        ["按字段名读取并求和。", "Read by field name and add."],
      ],
      playbackMs: 1250,
      playbackPolicy: "guided",
      persistentEvidenceZh: "记录卡 point { x:3, y:4 }。",
      persistentEvidenceEn: "The record card point { x:3, y:4 }.",
      hiddenByDefaultZh: "padding、对齐、字节布局、typedef 和数组类比。",
      hiddenByDefaultEn: "Padding, alignment, byte layout, typedef, and analogies to arrays.",
      researchUrls: ["https://pythontutor.com/c.html"],
    }),
    62: defineFoaLessonExperience({
      visualFamily: "memory",
      visualModelZh: "first 与 second 两张独立 Pair 卡；整体赋值复制字段值但不建立别名。",
      visualModelEn:
        "Independent first and second Pair cards; whole assignment copies fields without aliasing.",
      primaryActionZh: "整体复制后只修改 second.left，并预测 first 是否变化。",
      primaryActionEn:
        "After the whole-record copy, change only second.left and predict whether first changes.",
      sequence: [
        ["建立 first。", "Create first."],
        ["整体复制到 second。", "Copy the whole value to second."],
        ["只写 second.left=5。", "Write only second.left=5."],
        [
          "并排核对 first.left 与 second.left。",
          "Compare first.left and second.left side by side.",
        ],
      ],
      playbackMs: 1500,
      playbackPolicy: "guided",
      persistentEvidenceZh: "两张记录的独立身份与最终 left 值。",
      persistentEvidenceEn: "The two records' independent identities and final left values.",
      hiddenByDefaultZh: "逐字节复制、padding、地址和深浅拷贝泛化。",
      hiddenByDefaultEn:
        "Byte-by-byte copying, padding, addresses, and generalized deep/shallow-copy discussion.",
      researchUrls: ["https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf"],
    }),
    63: defineFoaLessonExperience({
      visualFamily: "pointer-graph",
      visualModelZh: "Counter 记录卡与 link 箭头；箭头落到记录，当前 value 字段单独突出。",
      visualModelEn:
        "A Counter card and link arrow; the arrow lands on the record while value is emphasized.",
      primaryActionZh: "沿 link->value 路径找到字段并执行一次递增。",
      primaryActionEn: "Follow link->value to the field and perform one increment.",
      sequence: [
        ["创建尚未赋值的 counter。", "Create counter before assigning its field."],
        ["把本次输入写入 counter.value。", "Write the current input into counter.value."],
        ["link 指向 counter。", "Point link to counter."],
        ["沿箭头访问 value。", "Follow the arrow to value."],
        ["把 value 递增 1 并写回。", "Increment value by one and write it back."],
      ],
      playbackMs: 1600,
      playbackPolicy: "guided",
      persistentEvidenceZh: "link → counter.value 的别名路径。",
      persistentEvidenceEn: "The alias path link → counter.value.",
      hiddenByDefaultZh: "等价展开式、十六进制地址和其他字段端口。",
      hiddenByDefaultEn:
        "Equivalent expanded syntax, hexadecimal addresses, and extra field ports.",
      researchUrls: ["https://pythontutor.com/c.html"],
    }),
    64: defineFoaLessonExperience({
      visualFamily: "call-stack",
      visualModelZh: "调用前记录、函数参数副本和返回记录依次接力，同时最多显示两张卡。",
      visualModelEn:
        "The input record, parameter copy, and return record form a relay with at most two cards visible.",
      primaryActionZh: "在参数副本上应用 dx、dy，再把完整记录返回调用者。",
      primaryActionEn:
        "Apply dx and dy to the parameter copy, then return the complete record to the caller.",
      sequence: [
        ["Point 值进入参数 p。", "Pass the Point value into parameter p."],
        ["修改 p.x 与 p.y。", "Modify p.x and p.y."],
        ["返回整个 p。", "Return the whole p value."],
        ["调用者接收 {4,6}。", "Let the caller receive {4,6}."],
      ],
      playbackMs: 1550,
      playbackPolicy: "guided",
      persistentEvidenceZh: "调用前 {1,2} 与返回后 {4,6} 的对照。",
      persistentEvidenceEn: "The before/after comparison {1,2} → {4,6}.",
      hiddenByDefaultZh: "ABI、返回值优化、并列全部调用帧和复合字面量讲解。",
      hiddenByDefaultEn:
        "ABI details, return-value optimization, all simultaneous frames, and compound-literal notes.",
      researchUrls: ["https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf"],
    }),
    65: defineFoaLessonExperience({
      visualFamily: "search",
      visualModelZh: "三行 name/score 表格和固定阈值线 7；合格行进入输出带。",
      visualModelEn:
        "A three-row name/score table with a threshold at 7; qualifying rows enter the output tape.",
      primaryActionZh: "逐行判断 score≥7，并选择保留或略过。",
      primaryActionEn: "Test score≥7 for each row and choose keep or skip.",
      sequence: [
        ["读取一条记录。", "Read one record."],
        ["读取 score 字段。", "Read its score field."],
        ["与阈值 7 比较。", "Compare with the threshold 7."],
        ["合格时输出 name。", "Output name when it qualifies."],
      ],
      playbackMs: 1200,
      playbackPolicy: "guided",
      persistentEvidenceZh: "已输出名称带 B C。",
      persistentEvidenceEn: "The output-name tape B C.",
      hiddenByDefaultZh: "记录布局、每轮全部字段、筛选 API 类比和复杂度。",
      hiddenByDefaultEn:
        "Record layout, all fields every iteration, filtering-API analogies, and complexity.",
      researchUrls: ["https://pythontutor.com/c.html"],
    }),
    66: defineFoaLessonExperience({
      visualFamily: "state",
      visualModelZh: "READY—RUNNING—DONE 三状态文字轨，任一时刻只突出一个状态。",
      visualModelEn: "A READY—RUNNING—DONE text track with exactly one state emphasized at a time.",
      primaryActionZh: "选择 RUNNING，再选择应执行的唯一 switch 分支。",
      primaryActionEn: "Select RUNNING, then choose the single switch branch that should execute.",
      sequence: [
        ["state 取得命名值。", "Assign a named value to state."],
        ["switch 读取 state。", "Let switch read state."],
        ["选择匹配 case。", "Select the matching case."],
        ["输出并 break。", "Output and break."],
      ],
      playbackMs: 1400,
      playbackPolicy: "guided",
      persistentEvidenceZh: "唯一活动状态 RUNNING。",
      persistentEvidenceEn: "The single active state RUNNING.",
      hiddenByDefaultZh: "底层整数、复杂状态图、层级/并发状态和完整 switch。",
      hiddenByDefaultEn:
        "Underlying integers, complex state charts, hierarchical/parallel states, and the full switch.",
      researchUrls: ["https://www.w3.org/TR/scxml/"],
    }),
    67: defineFoaLessonExperience({
      visualFamily: "memory",
      visualModelZh: "Value 卡上方是 kind 标签，下方是共用载荷槽；非活动成员折叠。",
      visualModelEn:
        "A Value card with a kind tag above one shared payload slot; inactive members stay collapsed.",
      primaryActionZh: "先设置 kind，再选择与它匹配的唯一合法载荷成员。",
      primaryActionEn: "Set kind first, then choose the only payload member compatible with it.",
      sequence: [
        ["写 kind=INTEGER。", "Write kind=INTEGER."],
        ["在共用槽写 integer=42。", "Write integer=42 in the shared slot."],
        ["守卫检查 kind。", "Check kind with the guard."],
        ["只读取活动成员。", "Read only the active member."],
      ],
      playbackMs: 1700,
      playbackPolicy: "guided",
      persistentEvidenceZh: "不变量 kind=INTEGER ⇒ as.integer 活动。",
      persistentEvidenceEn: "The invariant kind=INTEGER ⇒ as.integer is active.",
      hiddenByDefaultZh: "非活动成员伪值、字节重解释、对齐和类型双关。",
      hiddenByDefaultEn:
        "Pseudo-values for inactive members, byte reinterpretation, alignment, and type punning.",
      researchUrls: ["https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf"],
    }),
    68: defineFoaLessonExperience({
      visualFamily: "search",
      visualModelZh: "两行 Student 表和 id/name 列；typedef 只作一次性类型标签。",
      visualModelEn:
        "A two-row Student table with id/name columns; typedef appears only as a type label.",
      primaryActionZh: "用 wanted=9 顺序比较 id，命中后读取同一行 name。",
      primaryActionEn: "Compare ids against wanted=9 and read the name from the matching row.",
      sequence: [
        ["建立 wanted。", "Establish wanted."],
        ["比较当前 Student.id。", "Compare the current Student.id."],
        ["未命中则前进。", "Advance on a miss."],
        ["命中后输出 Lin。", "Output Lin on the match."],
      ],
      playbackMs: 1250,
      playbackPolicy: "guided",
      persistentEvidenceZh: '命中记录 Student{id:9,name:"Lin"}。',
      persistentEvidenceEn: 'The matched record Student{id:9,name:"Lin"}.',
      hiddenByDefaultZh: "typedef 展开链、完整声明语法、地址和比较历史。",
      hiddenByDefaultEn:
        "The typedef expansion chain, full declaration syntax, addresses, and comparison history.",
      researchUrls: [
        "https://opendsa-server.cs.vt.edu/ODSA/Books/pubbook/odsa-all/fall-2019/Public_Instance/html/BinarySearch.html",
      ],
    }),
    69: defineFoaLessonExperience({
      visualFamily: "search",
      visualModelZh: "4×4 上三角候选矩阵，每格代表一对 (i,j)，不绘制交叉连线。",
      visualModelEn: "A 4×4 upper-triangular candidate matrix where each cell is one (i,j) pair.",
      primaryActionZh: "按嵌套循环顺序点亮候选格，直到命中 (0,1)。",
      primaryActionEn: "Activate candidate cells in nested-loop order until (0,1) matches.",
      sequence: [
        ["固定 i。", "Fix i."],
        ["枚举 j>i。", "Enumerate j>i."],
        ["计算候选和。", "Compute the candidate sum."],
        ["与 target 比较并报告命中。", "Compare with target and report a match."],
      ],
      playbackMs: 1300,
      playbackPolicy: "guided",
      persistentEvidenceZh: "当前等式 values[i]+values[j] ? target。",
      persistentEvidenceEn: "The current equation values[i]+values[j] ? target.",
      hiddenByDefaultZh: "全部失败等式、哈希优化、完整源码和复杂度。",
      hiddenByDefaultEn: "All failed equations, hash optimization, full source, and complexity.",
      researchUrls: [
        "https://ocw.mit.edu/courses/6-0002-introduction-to-computational-thinking-and-data-science-fall-2016/3edc8db04a770f3da51086320c8fe4da_MIT6_0002F16_lec2.pdf",
      ],
    }),
    70: defineFoaLessonExperience({
      visualFamily: "search",
      visualModelZh: "有序数组上的 [low,high) 可行区间；区间外弱化，mid 仅显示一个。",
      visualModelEn:
        "A [low,high) feasible interval over a sorted array, with one mid and dimmed exclusions.",
      primaryActionZh: "根据 values[mid] 与 target 的比较选择保留哪一半。",
      primaryActionEn: "Use the comparison at mid to choose which half remains feasible.",
      sequence: [
        ["计算 mid。", "Compute mid."],
        ["比较中值与 target。", "Compare the middle value with target."],
        ["移动 low 或 high。", "Move low or high."],
        ["区间收敛时报告位置。", "Report the position when the interval converges."],
      ],
      playbackMs: 1450,
      playbackPolicy: "guided",
      persistentEvidenceZh: "当前可行区间 [low,high)。",
      persistentEvidenceEn: "The current feasible interval [low,high).",
      hiddenByDefaultZh: "搜索树、历史 mid、递归版本和复杂度证明。",
      hiddenByDefaultEn:
        "The search tree, previous mid values, recursive variants, and the complexity proof.",
      researchUrls: [
        "https://opendsa-server.cs.vt.edu/ODSA/Books/pubbook/odsa-all/fall-2019/Public_Instance/html/BinarySearch.html",
      ],
    }),
    71: defineFoaLessonExperience({
      visualFamily: "stream",
      visualModelZh: "水平队列带，左端 head、右端 tail；离队元素不保留幽灵节点。",
      visualModelEn:
        "A horizontal queue tape with head on the left and tail on the right, without ghost nodes.",
      primaryActionZh: "按事件脚本依次执行入队和出队。",
      primaryActionEn: "Perform enqueue and dequeue operations in the scripted event order.",
      sequence: [
        ["3、5 从 tail 入队。", "Enqueue 3 and 5 at tail."],
        ["3 从 head 出队。", "Dequeue 3 from head."],
        ["8 从 tail 入队。", "Enqueue 8 at tail."],
        ["5、8 依次出队。", "Dequeue 5 and then 8."],
      ],
      playbackMs: 1250,
      playbackPolicy: "guided",
      persistentEvidenceZh: "当前逻辑队列及 head/tail 位置。",
      persistentEvidenceEn: "The current logical queue and head/tail positions.",
      hiddenByDefaultZh: "底层数组废弃槽、链表实现、复杂度和完整事件日志。",
      hiddenByDefaultEn:
        "Unused backing-array cells, linked-list implementation, complexity, and the full event log.",
      researchUrls: ["https://visualgo.net/en/list?mode=LL"],
    }),
    72: defineFoaLessonExperience({
      visualFamily: "search",
      visualModelZh: "0–2 数轴上的 [low,high] 区间、mid 点和 mid² 与 2 的比较。",
      visualModelEn:
        "A [low,high] interval on the 0–2 number line, with mid and the comparison mid² versus 2.",
      primaryActionZh: "根据 mid² 与 2 的关系选择更新 low 或 high。",
      primaryActionEn: "Choose whether to update low or high from the comparison mid² versus 2.",
      sequence: [
        ["取区间中点。", "Take the interval midpoint."],
        ["计算 mid²。", "Compute mid²."],
        ["保留仍夹住根的半区。", "Keep the half that still brackets the root."],
        ["显示减半后的误差宽度。", "Display the halved error width."],
      ],
      playbackMs: 1500,
      playbackPolicy: "guided",
      persistentEvidenceZh: "当前误差区间宽度 high-low。",
      persistentEvidenceEn: "The current error interval width high-low.",
      hiddenByDefaultZh: "40 行历史、全部小数位、其他求根法和收敛阶表。",
      hiddenByDefaultEn:
        "Forty history rows, all decimal digits, other root solvers, and convergence-rate tables.",
      researchUrls: ["https://docs.scipy.org/doc/scipy-1.12.0/reference/optimize.html"],
    }),
    73: defineFoaLessonExperience({
      visualFamily: "state",
      visualModelZh: "一维位置轨道上的物体，下方只显示当前 t、position、velocity。",
      visualModelEn:
        "An object on a one-dimensional track with only current t, position, and velocity below.",
      primaryActionZh: "推进一次 dt，先更新位置，再更新速度。",
      primaryActionEn: "Advance one dt step, updating position before velocity.",
      sequence: [
        ["读取当前状态。", "Read the current state."],
        ["用 velocity·dt 更新 position。", "Update position with velocity·dt."],
        ["用重力更新 velocity。", "Update velocity with gravity."],
        ["推进时间并留下淡轨迹点。", "Advance time and leave a faint trail point."],
      ],
      playbackMs: 1700,
      playbackPolicy: "guided",
      persistentEvidenceZh: "当前状态三元组 (t, position, velocity)。",
      persistentEvidenceEn: "The current state tuple (t, position, velocity).",
      hiddenByDefaultZh: "连续曲线、空气阻力、积分器比较和完整历史表。",
      hiddenByDefaultEn:
        "Continuous curves, air resistance, integrator comparisons, and the complete history table.",
      researchUrls: ["https://cs184.eecs.berkeley.edu/sp26/assets/discussions/dis_13.pdf"],
    }),
    74: defineFoaLessonExperience({
      visualFamily: "search",
      visualModelZh: "离散 x 轴上的目标曲线，只显示 current 与 next 两个评价点。",
      visualModelEn:
        "An objective curve over discrete x, showing only the current and next evaluated points.",
      primaryActionZh: "比较 next 与 current，选择移动或停止。",
      primaryActionEn: "Compare next with current and choose whether to move or stop.",
      sequence: [
        ["评价 current。", "Evaluate current."],
        ["评价相邻 next。", "Evaluate the neighboring next."],
        ["next 更好则移动。", "Move when next is better."],
        ["没有改进时停止。", "Stop when there is no improvement."],
      ],
      playbackMs: 1500,
      playbackPolicy: "guided",
      persistentEvidenceZh: "score(next)-score(current) 的符号。",
      persistentEvidenceEn: "The sign of score(next)-score(current).",
      hiddenByDefaultZh: "完整访问历史、随机重启、梯度术语和全局最优保证。",
      hiddenByDefaultEn:
        "The full visit history, random restarts, gradient terminology, and global-optimum claims.",
      researchUrls: ["https://github.com/aimacode/aima-python/blob/master/search.ipynb"],
    }),
    75: defineFoaLessonExperience({
      visualFamily: "call-stack",
      visualModelZh: "从 moves(n) 到 moves(0) 的单链调用栈；返回时逐层应用 2·child+1。",
      visualModelEn:
        "A single call stack from moves(n) to moves(0), applying 2·child+1 at each return.",
      primaryActionZh: "逐帧压入调用，再按后进先出顺序填写每层返回值。",
      primaryActionEn: "Push each call, then fill each return value in last-in-first-out order.",
      sequence: [
        ["进入 moves(n)，建立第一帧。", "Enter moves(n) and create the first frame."],
        ["每层只调用一次 moves(disks-1)。", "Each frame calls moves(disks-1) exactly once."],
        ["moves(0) 命中基例并返回 0。", "moves(0) reaches the base case and returns 0."],
        [
          "逐层计算 2·child+1，得到本次输入的结果。",
          "Compute 2·child+1 while unwinding to obtain the result for this input.",
        ],
      ],
      playbackMs: 1800,
      playbackPolicy: "guided",
      persistentEvidenceZh: "实际调用深度为 n+1；返回值 2^n-1 不等于执行了 2^n 次调用。",
      persistentEvidenceEn:
        "Actual call depth is n+1; the return value 2^n-1 does not mean 2^n calls were executed.",
      hiddenByDefaultZh: "不存在于本实现的双分支递归树、装饰性圆盘动画和完整源码。",
      hiddenByDefaultEn:
        "A two-branch recursion tree not executed by this implementation, decorative disk animation, and full source.",
      researchUrls: [
        "https://visualgo.net/en/recursion/print",
        "https://opendsa-server.cs.vt.edu/ODSA/Books/Everything/html/RecIntro.html",
      ],
    }),
    76: defineFoaLessonExperience({
      visualFamily: "tree",
      visualModelZh: "小型 choose/skip 决策树，节点只显示剩余元素与 target。",
      visualModelEn:
        "A small choose/skip decision tree whose nodes show only remaining elements and target.",
      primaryActionZh: "对当前元素选择跳过或选入，观察 target 是否降到 0。",
      primaryActionEn: "Skip or choose the current element and watch whether target reaches zero.",
      sequence: [
        ["检查 target==0 或 n==0。", "Check target==0 or n==0."],
        ["探索 skip 分支。", "Explore the skip branch."],
        ["必要时选入并减少 target。", "Choose the element and reduce target when needed."],
        ["任一成功即返回 true。", "Return true as soon as either branch succeeds."],
      ],
      playbackMs: 1700,
      playbackPolicy: "guided",
      persistentEvidenceZh: "当前剩余 target 与已选择集合。",
      persistentEvidenceEn: "The current remaining target and chosen subset.",
      hiddenByDefaultZh: "完整指数树、同时高亮两分支、回溯日志和 DP 优化。",
      hiddenByDefaultEn:
        "The full exponential tree, simultaneous branch highlights, backtracking logs, and DP optimization.",
      researchUrls: [
        "https://opendsa-server.cs.vt.edu/ODSA/Books/Everything/html/WritingEx.html",
        "https://visualgo.net/en/recursion?mode=MT",
      ],
    }),
    77: defineFoaLessonExperience({
      visualFamily: "evidence",
      visualModelZh: "单位正方形与四分之一圆；样本按 1、10、100、1000、10000 成批累积。",
      visualModelEn:
        "A unit square and quarter circle, accumulating samples in batches of 1, 10, 100, 1000, and 10000.",
      primaryActionZh: "推进一个样本批次，并判断估计是否必须单调。",
      primaryActionEn: "Advance one sample batch and judge whether the estimate must be monotonic.",
      sequence: [
        ["用固定 seed 生成 (x,y)。", "Generate (x,y) from the fixed seed."],
        ["按 x²+y²≤1 分类。", "Classify using x²+y²≤1."],
        ["更新 inside/samples。", "Update inside/samples."],
        ["计算 π 估计。", "Compute the estimate of π."],
      ],
      playbackMs: 1500,
      playbackPolicy: "guided",
      persistentEvidenceZh: "inside / samples → π estimate 的比例。",
      persistentEvidenceEn: "The ratio inside / samples → π estimate.",
      hiddenByDefaultZh: "逐点播放、PRNG 位运算、置信区间和真实性能历史。",
      hiddenByDefaultEn:
        "Per-point playback, PRNG bit operations, confidence intervals, and real performance history.",
      researchUrls: ["https://www.nist.gov/news-events/news/2020/01/new-tool-account-uncertainty"],
    }),
    78: defineFoaLessonExperience({
      visualFamily: "state",
      visualModelZh: "y=x²-2 曲线、当前点、该点切线及切线的 x 截距。",
      visualModelEn:
        "The curve y=x²-2 with the current point, its tangent, and the tangent's x-intercept.",
      primaryActionZh: "把切线截距设为下一次 x，并核对残差。",
      primaryActionEn: "Use the tangent's intercept as the next x and check the residual.",
      sequence: [
        ["计算 f(x)。", "Compute f(x)."],
        ["计算 f′(x)。", "Compute f′(x)."],
        ["用 x-f/f′ 修正 x。", "Correct x with x-f/f′."],
        ["显示新残差。", "Display the new residual."],
      ],
      playbackMs: 1800,
      playbackPolicy: "guided",
      persistentEvidenceZh: "当前残差 |x²-2|。",
      persistentEvidenceEn: "The current residual |x²-2|.",
      hiddenByDefaultZh: "八行小数表、其他求根法、收敛阶证明和全部切线残影。",
      hiddenByDefaultEn:
        "Eight decimal-history rows, other solvers, convergence proofs, and all old tangents.",
      researchUrls: [
        "https://docs.scipy.org/doc/scipy-0.17.0/reference/generated/scipy.optimize.newton.html",
      ],
    }),
    79: defineFoaLessonExperience({
      visualFamily: "sorting",
      visualModelZh: "四张稳定身份卡和从右向左收缩的未固定区；每轮只突出 i、j。",
      visualModelEn:
        "Four stable cards and an unfixed region shrinking right-to-left, highlighting only i and j.",
      primaryActionZh: "根据 seed 生成的 j，交换位置 i 与 j。",
      primaryActionEn: "Swap positions i and j using the j generated from the seed.",
      sequence: [
        ["在 [0,i] 生成 j。", "Generate j in [0,i]."],
        ["选择 i 与 j。", "Select i and j."],
        ["交换两张卡。", "Swap the two cards."],
        ["缩小未固定区。", "Shrink the unfixed region."],
      ],
      playbackMs: 1450,
      playbackPolicy: "guided",
      persistentEvidenceZh: "未固定区边界 [0,i]。",
      persistentEvidenceEn: "The unfixed-region boundary [0,i].",
      hiddenByDefaultZh: "LCG 乘加细节、所有排列、概率证明和多余交换连线。",
      hiddenByDefaultEn:
        "LCG arithmetic, all permutations, probability proofs, and extra swap wires.",
      researchUrls: ["https://xlinux.nist.gov/dads/HTML/fisherYatesShuffle.html"],
    }),
    80: defineFoaLessonExperience({
      visualFamily: "evidence",
      visualModelZh: "3×3 网格；开放格只保留来自上方和左侧的短入边与一个路径数。",
      visualModelEn:
        "A 3×3 grid where each open cell keeps only short incoming edges from above and left plus one path count.",
      primaryActionZh: "按行列顺序填写下一个开放格的路径数，并跳过障碍。",
      primaryActionEn:
        "Fill the next open cell's path count in row-major order and skip obstacles.",
      sequence: [
        ["起点置 1。", "Set the start cell to 1."],
        ["选择下一个网格单元。", "Select the next grid cell."],
        ["开放时相加上方与左侧路径数。", "For an open cell, add counts from above and left."],
        ["在终点读取总数。", "Read the total at the destination."],
      ],
      playbackMs: 1500,
      playbackPolicy: "guided",
      persistentEvidenceZh: "当前格的局部等式 paths[r][c]=up+left。",
      persistentEvidenceEn: "The current cell's local equation paths[r][c]=up+left.",
      hiddenByDefaultZh: "全部路径折线、穷举树、完整代码和无关寻路算法；本课不是穷举生成。",
      hiddenByDefaultEn:
        "All path polylines, the exhaustive tree, full code, and unrelated pathfinding algorithms; this lesson does not enumerate paths.",
      researchUrls: [
        "https://cs.nyu.edu/~joannakl/aps_s21/slides/11-dynamic_programming_1.html",
        "https://utw11041.utweb.utexas.edu/ORMM/methods/unit/dynamic/subunits/teach_dp/model_path.html",
      ],
    }),
  });
