import { foaText } from "./foa-contracts.js";
import { defineFoaSceneProfile, type FoaSceneProfile } from "./foa-scene-profile.js";

export const FOA_SCENE_PROFILES_021_040: Readonly<Record<number, FoaSceneProfile>> = Object.freeze({
  21: defineFoaSceneProfile({
    order: 21,
    kind: "branch",
    connection: "branch",
    slots: ["input", "decision", "output", "return"],
    evidence: ["input", "condition", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "守卫失败必须直达退出，并把未执行的核心流程降为背景。",
      "A failed guard must exit directly and demote the unexecuted core flow.",
    ),
  }),
  22: defineFoaSceneProfile({
    order: 22,
    kind: "loop",
    connection: "cycle",
    slots: ["state", "condition", "body", "update"],
    evidence: ["input", "state", "condition", "iteration", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "学习者输入 n，并逐轮观察条件、累加和回边。",
      "The learner enters n and observes each condition, accumulation, and back edge.",
    ),
  }),
  23: defineFoaSceneProfile({
    order: 23,
    kind: "loop",
    connection: "cycle",
    slots: ["state", "operation", "update", "condition"],
    evidence: ["state", "condition", "iteration", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "乘积链需持续显示当前因子和循环头不变量。",
      "The product chain must preserve the current factor and loop-head invariant.",
    ),
  }),
  24: defineFoaSceneProfile({
    order: 24,
    kind: "loop",
    connection: "cycle",
    slots: ["state", "operation", "operation", "update"],
    evidence: ["state", "iteration", "output"],
    caseMode: "none",
    special: true,
    rationale: foaText(
      "逐期复利账本同时保留余额、当期利息与整数除法舍弃部分。",
      "The compound-interest ledger retains balance, period interest, and discarded integer remainders.",
    ),
  }),
  25: defineFoaSceneProfile({
    order: 25,
    kind: "stream",
    connection: "branch",
    slots: ["input", "decision", "body", "output"],
    evidence: ["input", "state", "condition", "iteration", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "哨兵 token 必须在比较器处分流，不能进入累加器。",
      "The sentinel token must branch at the comparator and never enter the accumulator.",
    ),
  }),
  26: defineFoaSceneProfile({
    order: 26,
    kind: "loop",
    connection: "cycle",
    slots: ["body", "update", "condition", "output"],
    evidence: ["input", "state", "condition", "iteration", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "后测循环必须先执行循环体，再决定是否回环。",
      "A post-test loop must execute its body before deciding whether to repeat.",
    ),
  }),
  27: defineFoaSceneProfile({
    order: 27,
    kind: "stream",
    connection: "cycle",
    slots: ["gate", "input", "update", "output"],
    evidence: ["input", "state", "iteration", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "计数输入流应同步显示消费进度、总和与最终均值。",
      "The counted stream should synchronize consumption, sum, and final average.",
    ),
  }),
  28: defineFoaSceneProfile({
    order: 28,
    kind: "search",
    connection: "compare",
    slots: ["state", "input", "decision", "output"],
    evidence: ["input", "state", "condition", "iteration", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "冠军必须由首个真实输入建立，再逐个比较挑战者。",
      "The champion must start from the first real input before comparing challengers.",
    ),
  }),
  29: defineFoaSceneProfile({
    order: 29,
    kind: "matrix",
    connection: "grid",
    slots: ["condition", "body", "output", "update"],
    evidence: ["state", "iteration", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "二维字符画需同时保留行列光标和已生成输出。",
      "The character grid must retain row and column cursors alongside generated output.",
    ),
  }),
  30: defineFoaSceneProfile({
    order: 30,
    kind: "search",
    connection: "compare",
    slots: ["state", "condition", "operation", "decision"],
    evidence: ["input", "state", "condition", "iteration", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "除数刻度需同时解释余数与提前停止边界。",
      "The divisor scale must explain both remainders and the early-stop boundary.",
    ),
  }),
  31: defineFoaSceneProfile({
    order: 31,
    kind: "loop",
    connection: "cycle",
    slots: ["operation", "update", "update", "output"],
    evidence: ["input", "state", "iteration", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "稳定寄存器应呈现余数计算、轮换和严格下降。",
      "Stable registers should show remainder calculation, rotation, and strict decrease.",
    ),
  }),
  32: defineFoaSceneProfile({
    order: 32,
    kind: "call-stack",
    connection: "unwind",
    slots: ["call", "frame", "operation", "return"],
    evidence: ["input", "state", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "square 调用帧专门连接实参、形参副本、平方结果与返回值。",
      "The square call frame connects the argument, parameter copy, squared result, and return value.",
    ),
  }),
  33: defineFoaSceneProfile({
    order: 33,
    kind: "evidence",
    connection: "compare",
    slots: ["entry", "call", "gate", "return"],
    evidence: ["state", "test", "output"],
    caseMode: "none",
    special: true,
    rationale: foaText(
      "当前步骤只显示需要核对的两个字段，已完成连线保留为证据。",
      "Each step shows only the two fields being checked; completed routes remain as evidence.",
    ),
  }),
  34: defineFoaSceneProfile({
    order: 34,
    kind: "execution",
    connection: "forward",
    slots: ["gate", "call", "return", "output"],
    evidence: ["input", "output"],
    caseMode: "interactive",
    special: true,
    rationale: foaText(
      "标准库函数只显示公开契约，不展开头文件或内部实现。",
      "A library function should expose only its public contract, not headers or internals.",
    ),
  }),
  35: defineFoaSceneProfile({
    order: 35,
    kind: "branch",
    connection: "branch",
    slots: ["decision", "decision", "true-path", "return"],
    evidence: ["input", "condition", "output"],
    caseMode: "none",
    special: true,
    rationale: foaText(
      "clamp 三段数轴把下界守卫、原值区与上界守卫映射到三个返回口。",
      "The clamp number line maps its lower guard, pass-through zone, and upper guard to three return ports.",
    ),
  }),
  36: defineFoaSceneProfile({
    order: 36,
    kind: "call-stack",
    connection: "unwind",
    slots: ["call", "base-case", "return", "output"],
    edges: [
      [0, 1],
      [1, 2],
      [2, 0],
      [2, 3],
    ],
    evidence: ["state", "iteration", "output"],
    caseMode: "none",
    special: true,
    rationale: foaText(
      "递归必须区分下潜、基例和逐层回卷乘法。",
      "Recursion must distinguish descent, the base case, and multiplication while unwinding.",
    ),
  }),
  37: defineFoaSceneProfile({
    order: 37,
    kind: "plot",
    connection: "cycle",
    slots: ["state", "operation", "update", "condition"],
    evidence: ["state", "iteration", "output"],
    caseMode: "none",
    special: true,
    rationale: foaText(
      "收敛图需同步当前 guess、更新公式与残差。",
      "The convergence plot must synchronize the current guess, update formula, and residual.",
    ),
  }),
  38: defineFoaSceneProfile({
    order: 38,
    kind: "evidence",
    connection: "evidence",
    slots: ["input", "call", "decision", "evidence"],
    evidence: ["state", "test", "output"],
    caseMode: "none",
    special: true,
    rationale: foaText(
      "测试必须逐行产生 actual、expected 与通过证据。",
      "Each test row must produce actual, expected, and pass evidence in place.",
    ),
  }),
  39: defineFoaSceneProfile({
    order: 39,
    kind: "call-stack",
    connection: "unwind",
    slots: ["call", "frame", "output", "return"],
    evidence: ["state", "output"],
    caseMode: "none",
    special: true,
    rationale: foaText(
      "调用者和形参副本必须同时可见，且生命周期分离。",
      "Caller state and the parameter copy must remain visible with separate lifetimes.",
    ),
  }),
  40: defineFoaSceneProfile({
    order: 40,
    kind: "call-stack",
    connection: "unwind",
    slots: ["call", "operation", "return", "output"],
    evidence: ["input", "state", "output"],
    caseMode: "none",
    special: true,
    rationale: foaText(
      "计算结果 token 经过 return 槽抵达调用点后，调用者变量才允许绑定。",
      "The caller may bind the computed token only after it traverses the return slot to the call site.",
    ),
  }),
});
